package org.bread_experts_group.eam.minecraft.feature.v1x21x1.net.minecraft.world.item

import org.bread_experts_group.eam.loadClass
import org.bread_experts_group.eam.minecraft.feature.MimickedClass
import org.bread_experts_group.eam.minecraft.feature.v1x21x1.net.minecraft.resources.ResourceLocation
import org.bread_experts_group.eam.minecraft.feature.v1x21x1.net_minecraft_world_item_Items

/*
    net.minecraft.world.item.Item STONE -> b
    net.minecraft.world.item.Item GRANITE -> c
    net.minecraft.world.item.Item POLISHED_GRANITE -> d
    net.minecraft.world.item.Item DIORITE -> e
    net.minecraft.world.item.Item POLISHED_DIORITE -> f
    net.minecraft.world.item.Item ANDESITE -> g
    net.minecraft.world.item.Item POLISHED_ANDESITE -> h
    net.minecraft.world.item.Item DEEPSLATE -> i
    net.minecraft.world.item.Item COBBLED_DEEPSLATE -> j
    net.minecraft.world.item.Item POLISHED_DEEPSLATE -> k
    net.minecraft.world.item.Item CALCITE -> l
    net.minecraft.world.item.Item TUFF -> m
    net.minecraft.world.item.Item TUFF_SLAB -> n
    net.minecraft.world.item.Item TUFF_STAIRS -> o
    net.minecraft.world.item.Item TUFF_WALL -> p
    net.minecraft.world.item.Item CHISELED_TUFF -> q
    net.minecraft.world.item.Item POLISHED_TUFF -> r
    net.minecraft.world.item.Item POLISHED_TUFF_SLAB -> s
    net.minecraft.world.item.Item POLISHED_TUFF_STAIRS -> t
    net.minecraft.world.item.Item POLISHED_TUFF_WALL -> u
    net.minecraft.world.item.Item TUFF_BRICKS -> v
    net.minecraft.world.item.Item TUFF_BRICK_SLAB -> w
    net.minecraft.world.item.Item TUFF_BRICK_STAIRS -> x
    net.minecraft.world.item.Item TUFF_BRICK_WALL -> y
    net.minecraft.world.item.Item CHISELED_TUFF_BRICKS -> z
    net.minecraft.world.item.Item DRIPSTONE_BLOCK -> A
    net.minecraft.world.item.Item GRASS_BLOCK -> B
    net.minecraft.world.item.Item DIRT -> C
    net.minecraft.world.item.Item COARSE_DIRT -> D
    net.minecraft.world.item.Item PODZOL -> E
    net.minecraft.world.item.Item ROOTED_DIRT -> F
    net.minecraft.world.item.Item MUD -> G
    net.minecraft.world.item.Item CRIMSON_NYLIUM -> H
    net.minecraft.world.item.Item WARPED_NYLIUM -> I
    net.minecraft.world.item.Item COBBLESTONE -> J
    net.minecraft.world.item.Item OAK_PLANKS -> K
    net.minecraft.world.item.Item SPRUCE_PLANKS -> L
    net.minecraft.world.item.Item BIRCH_PLANKS -> M
    net.minecraft.world.item.Item JUNGLE_PLANKS -> N
    net.minecraft.world.item.Item ACACIA_PLANKS -> O
    net.minecraft.world.item.Item CHERRY_PLANKS -> P
    net.minecraft.world.item.Item DARK_OAK_PLANKS -> Q
    net.minecraft.world.item.Item MANGROVE_PLANKS -> R
    net.minecraft.world.item.Item BAMBOO_PLANKS -> S
    net.minecraft.world.item.Item CRIMSON_PLANKS -> T
    net.minecraft.world.item.Item WARPED_PLANKS -> U
    net.minecraft.world.item.Item BAMBOO_MOSAIC -> V
    net.minecraft.world.item.Item OAK_SAPLING -> W
    net.minecraft.world.item.Item SPRUCE_SAPLING -> X
    net.minecraft.world.item.Item BIRCH_SAPLING -> Y
    net.minecraft.world.item.Item JUNGLE_SAPLING -> Z
    net.minecraft.world.item.Item ACACIA_SAPLING -> aa
    net.minecraft.world.item.Item CHERRY_SAPLING -> ab
    net.minecraft.world.item.Item DARK_OAK_SAPLING -> ac
    net.minecraft.world.item.Item MANGROVE_PROPAGULE -> ad
    net.minecraft.world.item.Item BEDROCK -> ae
    net.minecraft.world.item.Item SAND -> af
    net.minecraft.world.item.Item SUSPICIOUS_SAND -> ag
    net.minecraft.world.item.Item SUSPICIOUS_GRAVEL -> ah
    net.minecraft.world.item.Item RED_SAND -> ai
    net.minecraft.world.item.Item GRAVEL -> aj
    net.minecraft.world.item.Item COAL_ORE -> ak
    net.minecraft.world.item.Item DEEPSLATE_COAL_ORE -> al
    net.minecraft.world.item.Item IRON_ORE -> am
    net.minecraft.world.item.Item DEEPSLATE_IRON_ORE -> an
    net.minecraft.world.item.Item COPPER_ORE -> ao
    net.minecraft.world.item.Item DEEPSLATE_COPPER_ORE -> ap
    net.minecraft.world.item.Item GOLD_ORE -> aq
    net.minecraft.world.item.Item DEEPSLATE_GOLD_ORE -> ar
    net.minecraft.world.item.Item REDSTONE_ORE -> as
    net.minecraft.world.item.Item DEEPSLATE_REDSTONE_ORE -> at
    net.minecraft.world.item.Item EMERALD_ORE -> au
    net.minecraft.world.item.Item DEEPSLATE_EMERALD_ORE -> av
    net.minecraft.world.item.Item LAPIS_ORE -> aw
    net.minecraft.world.item.Item DEEPSLATE_LAPIS_ORE -> ax
    net.minecraft.world.item.Item DIAMOND_ORE -> ay
    net.minecraft.world.item.Item DEEPSLATE_DIAMOND_ORE -> az
    net.minecraft.world.item.Item NETHER_GOLD_ORE -> aA
    net.minecraft.world.item.Item NETHER_QUARTZ_ORE -> aB
    net.minecraft.world.item.Item ANCIENT_DEBRIS -> aC
    net.minecraft.world.item.Item COAL_BLOCK -> aD
    net.minecraft.world.item.Item RAW_IRON_BLOCK -> aE
    net.minecraft.world.item.Item RAW_COPPER_BLOCK -> aF
    net.minecraft.world.item.Item RAW_GOLD_BLOCK -> aG
    net.minecraft.world.item.Item HEAVY_CORE -> aH
    net.minecraft.world.item.Item AMETHYST_BLOCK -> aI
    net.minecraft.world.item.Item BUDDING_AMETHYST -> aJ
    net.minecraft.world.item.Item IRON_BLOCK -> aK
    net.minecraft.world.item.Item COPPER_BLOCK -> aL
    net.minecraft.world.item.Item GOLD_BLOCK -> aM
    net.minecraft.world.item.Item DIAMOND_BLOCK -> aN
    net.minecraft.world.item.Item NETHERITE_BLOCK -> aO
    net.minecraft.world.item.Item EXPOSED_COPPER -> aP
    net.minecraft.world.item.Item WEATHERED_COPPER -> aQ
    net.minecraft.world.item.Item OXIDIZED_COPPER -> aR
    net.minecraft.world.item.Item CHISELED_COPPER -> aS
    net.minecraft.world.item.Item EXPOSED_CHISELED_COPPER -> aT
    net.minecraft.world.item.Item WEATHERED_CHISELED_COPPER -> aU
    net.minecraft.world.item.Item OXIDIZED_CHISELED_COPPER -> aV
    net.minecraft.world.item.Item CUT_COPPER -> aW
    net.minecraft.world.item.Item EXPOSED_CUT_COPPER -> aX
    net.minecraft.world.item.Item WEATHERED_CUT_COPPER -> aY
    net.minecraft.world.item.Item OXIDIZED_CUT_COPPER -> aZ
    net.minecraft.world.item.Item CUT_COPPER_STAIRS -> ba
    net.minecraft.world.item.Item EXPOSED_CUT_COPPER_STAIRS -> bb
    net.minecraft.world.item.Item WEATHERED_CUT_COPPER_STAIRS -> bc
    net.minecraft.world.item.Item OXIDIZED_CUT_COPPER_STAIRS -> bd
    net.minecraft.world.item.Item CUT_COPPER_SLAB -> be
    net.minecraft.world.item.Item EXPOSED_CUT_COPPER_SLAB -> bf
    net.minecraft.world.item.Item WEATHERED_CUT_COPPER_SLAB -> bg
    net.minecraft.world.item.Item OXIDIZED_CUT_COPPER_SLAB -> bh
    net.minecraft.world.item.Item WAXED_COPPER_BLOCK -> bi
    net.minecraft.world.item.Item WAXED_EXPOSED_COPPER -> bj
    net.minecraft.world.item.Item WAXED_WEATHERED_COPPER -> bk
    net.minecraft.world.item.Item WAXED_OXIDIZED_COPPER -> bl
    net.minecraft.world.item.Item WAXED_CHISELED_COPPER -> bm
    net.minecraft.world.item.Item WAXED_EXPOSED_CHISELED_COPPER -> bn
    net.minecraft.world.item.Item WAXED_WEATHERED_CHISELED_COPPER -> bo
    net.minecraft.world.item.Item WAXED_OXIDIZED_CHISELED_COPPER -> bp
    net.minecraft.world.item.Item WAXED_CUT_COPPER -> bq
    net.minecraft.world.item.Item WAXED_EXPOSED_CUT_COPPER -> br
    net.minecraft.world.item.Item WAXED_WEATHERED_CUT_COPPER -> bs
    net.minecraft.world.item.Item WAXED_OXIDIZED_CUT_COPPER -> bt
    net.minecraft.world.item.Item WAXED_CUT_COPPER_STAIRS -> bu
    net.minecraft.world.item.Item WAXED_EXPOSED_CUT_COPPER_STAIRS -> bv
    net.minecraft.world.item.Item WAXED_WEATHERED_CUT_COPPER_STAIRS -> bw
    net.minecraft.world.item.Item WAXED_OXIDIZED_CUT_COPPER_STAIRS -> bx
    net.minecraft.world.item.Item WAXED_CUT_COPPER_SLAB -> by
    net.minecraft.world.item.Item WAXED_EXPOSED_CUT_COPPER_SLAB -> bz
    net.minecraft.world.item.Item WAXED_WEATHERED_CUT_COPPER_SLAB -> bA
    net.minecraft.world.item.Item WAXED_OXIDIZED_CUT_COPPER_SLAB -> bB
    net.minecraft.world.item.Item OAK_LOG -> bC
    net.minecraft.world.item.Item SPRUCE_LOG -> bD
    net.minecraft.world.item.Item BIRCH_LOG -> bE
    net.minecraft.world.item.Item JUNGLE_LOG -> bF
    net.minecraft.world.item.Item ACACIA_LOG -> bG
    net.minecraft.world.item.Item CHERRY_LOG -> bH
    net.minecraft.world.item.Item DARK_OAK_LOG -> bI
    net.minecraft.world.item.Item MANGROVE_LOG -> bJ
    net.minecraft.world.item.Item MANGROVE_ROOTS -> bK
    net.minecraft.world.item.Item MUDDY_MANGROVE_ROOTS -> bL
    net.minecraft.world.item.Item CRIMSON_STEM -> bM
    net.minecraft.world.item.Item WARPED_STEM -> bN
    net.minecraft.world.item.Item BAMBOO_BLOCK -> bO
    net.minecraft.world.item.Item STRIPPED_OAK_LOG -> bP
    net.minecraft.world.item.Item STRIPPED_SPRUCE_LOG -> bQ
    net.minecraft.world.item.Item STRIPPED_BIRCH_LOG -> bR
    net.minecraft.world.item.Item STRIPPED_JUNGLE_LOG -> bS
    net.minecraft.world.item.Item STRIPPED_ACACIA_LOG -> bT
    net.minecraft.world.item.Item STRIPPED_CHERRY_LOG -> bU
    net.minecraft.world.item.Item STRIPPED_DARK_OAK_LOG -> bV
    net.minecraft.world.item.Item STRIPPED_MANGROVE_LOG -> bW
    net.minecraft.world.item.Item STRIPPED_CRIMSON_STEM -> bX
    net.minecraft.world.item.Item STRIPPED_WARPED_STEM -> bY
    net.minecraft.world.item.Item STRIPPED_OAK_WOOD -> bZ
    net.minecraft.world.item.Item STRIPPED_SPRUCE_WOOD -> ca
    net.minecraft.world.item.Item STRIPPED_BIRCH_WOOD -> cb
    net.minecraft.world.item.Item STRIPPED_JUNGLE_WOOD -> cc
    net.minecraft.world.item.Item STRIPPED_ACACIA_WOOD -> cd
    net.minecraft.world.item.Item STRIPPED_CHERRY_WOOD -> ce
    net.minecraft.world.item.Item STRIPPED_DARK_OAK_WOOD -> cf
    net.minecraft.world.item.Item STRIPPED_MANGROVE_WOOD -> cg
    net.minecraft.world.item.Item STRIPPED_CRIMSON_HYPHAE -> ch
    net.minecraft.world.item.Item STRIPPED_WARPED_HYPHAE -> ci
    net.minecraft.world.item.Item STRIPPED_BAMBOO_BLOCK -> cj
    net.minecraft.world.item.Item OAK_WOOD -> ck
    net.minecraft.world.item.Item SPRUCE_WOOD -> cl
    net.minecraft.world.item.Item BIRCH_WOOD -> cm
    net.minecraft.world.item.Item JUNGLE_WOOD -> cn
    net.minecraft.world.item.Item ACACIA_WOOD -> co
    net.minecraft.world.item.Item CHERRY_WOOD -> cp
    net.minecraft.world.item.Item DARK_OAK_WOOD -> cq
    net.minecraft.world.item.Item MANGROVE_WOOD -> cr
    net.minecraft.world.item.Item CRIMSON_HYPHAE -> cs
    net.minecraft.world.item.Item WARPED_HYPHAE -> ct
    net.minecraft.world.item.Item OAK_LEAVES -> cu
    net.minecraft.world.item.Item SPRUCE_LEAVES -> cv
    net.minecraft.world.item.Item BIRCH_LEAVES -> cw
    net.minecraft.world.item.Item JUNGLE_LEAVES -> cx
    net.minecraft.world.item.Item ACACIA_LEAVES -> cy
    net.minecraft.world.item.Item CHERRY_LEAVES -> cz
    net.minecraft.world.item.Item DARK_OAK_LEAVES -> cA
    net.minecraft.world.item.Item MANGROVE_LEAVES -> cB
    net.minecraft.world.item.Item AZALEA_LEAVES -> cC
    net.minecraft.world.item.Item FLOWERING_AZALEA_LEAVES -> cD
    net.minecraft.world.item.Item SPONGE -> cE
    net.minecraft.world.item.Item WET_SPONGE -> cF
    net.minecraft.world.item.Item GLASS -> cG
    net.minecraft.world.item.Item TINTED_GLASS -> cH
    net.minecraft.world.item.Item LAPIS_BLOCK -> cI
    net.minecraft.world.item.Item SANDSTONE -> cJ
    net.minecraft.world.item.Item CHISELED_SANDSTONE -> cK
    net.minecraft.world.item.Item CUT_SANDSTONE -> cL
    net.minecraft.world.item.Item COBWEB -> cM
    net.minecraft.world.item.Item SHORT_GRASS -> cN
    net.minecraft.world.item.Item FERN -> cO
    net.minecraft.world.item.Item AZALEA -> cP
    net.minecraft.world.item.Item FLOWERING_AZALEA -> cQ
    net.minecraft.world.item.Item DEAD_BUSH -> cR
    net.minecraft.world.item.Item SEAGRASS -> cS
    net.minecraft.world.item.Item SEA_PICKLE -> cT
    net.minecraft.world.item.Item WHITE_WOOL -> cU
    net.minecraft.world.item.Item ORANGE_WOOL -> cV
    net.minecraft.world.item.Item MAGENTA_WOOL -> cW
    net.minecraft.world.item.Item LIGHT_BLUE_WOOL -> cX
    net.minecraft.world.item.Item YELLOW_WOOL -> cY
    net.minecraft.world.item.Item LIME_WOOL -> cZ
    net.minecraft.world.item.Item PINK_WOOL -> da
    net.minecraft.world.item.Item GRAY_WOOL -> db
    net.minecraft.world.item.Item LIGHT_GRAY_WOOL -> dc
    net.minecraft.world.item.Item CYAN_WOOL -> dd
    net.minecraft.world.item.Item PURPLE_WOOL -> de
    net.minecraft.world.item.Item BLUE_WOOL -> df
    net.minecraft.world.item.Item BROWN_WOOL -> dg
    net.minecraft.world.item.Item GREEN_WOOL -> dh
    net.minecraft.world.item.Item RED_WOOL -> di
    net.minecraft.world.item.Item BLACK_WOOL -> dj
    net.minecraft.world.item.Item DANDELION -> dk
    net.minecraft.world.item.Item POPPY -> dl
    net.minecraft.world.item.Item BLUE_ORCHID -> dm
    net.minecraft.world.item.Item ALLIUM -> dn
    net.minecraft.world.item.Item AZURE_BLUET -> do
    net.minecraft.world.item.Item RED_TULIP -> dp
    net.minecraft.world.item.Item ORANGE_TULIP -> dq
    net.minecraft.world.item.Item WHITE_TULIP -> dr
    net.minecraft.world.item.Item PINK_TULIP -> ds
    net.minecraft.world.item.Item OXEYE_DAISY -> dt
    net.minecraft.world.item.Item CORNFLOWER -> du
    net.minecraft.world.item.Item LILY_OF_THE_VALLEY -> dv
    net.minecraft.world.item.Item WITHER_ROSE -> dw
    net.minecraft.world.item.Item TORCHFLOWER -> dx
    net.minecraft.world.item.Item PITCHER_PLANT -> dy
    net.minecraft.world.item.Item SPORE_BLOSSOM -> dz
    net.minecraft.world.item.Item BROWN_MUSHROOM -> dA
    net.minecraft.world.item.Item RED_MUSHROOM -> dB
    net.minecraft.world.item.Item CRIMSON_FUNGUS -> dC
    net.minecraft.world.item.Item WARPED_FUNGUS -> dD
    net.minecraft.world.item.Item CRIMSON_ROOTS -> dE
    net.minecraft.world.item.Item WARPED_ROOTS -> dF
    net.minecraft.world.item.Item NETHER_SPROUTS -> dG
    net.minecraft.world.item.Item WEEPING_VINES -> dH
    net.minecraft.world.item.Item TWISTING_VINES -> dI
    net.minecraft.world.item.Item SUGAR_CANE -> dJ
    net.minecraft.world.item.Item KELP -> dK
    net.minecraft.world.item.Item MOSS_CARPET -> dL
    net.minecraft.world.item.Item PINK_PETALS -> dM
    net.minecraft.world.item.Item MOSS_BLOCK -> dN
    net.minecraft.world.item.Item HANGING_ROOTS -> dO
    net.minecraft.world.item.Item BIG_DRIPLEAF -> dP
    net.minecraft.world.item.Item SMALL_DRIPLEAF -> dQ
    net.minecraft.world.item.Item BAMBOO -> dR
    net.minecraft.world.item.Item OAK_SLAB -> dS
    net.minecraft.world.item.Item SPRUCE_SLAB -> dT
    net.minecraft.world.item.Item BIRCH_SLAB -> dU
    net.minecraft.world.item.Item JUNGLE_SLAB -> dV
    net.minecraft.world.item.Item ACACIA_SLAB -> dW
    net.minecraft.world.item.Item CHERRY_SLAB -> dX
    net.minecraft.world.item.Item DARK_OAK_SLAB -> dY
    net.minecraft.world.item.Item MANGROVE_SLAB -> dZ
    net.minecraft.world.item.Item BAMBOO_SLAB -> ea
    net.minecraft.world.item.Item BAMBOO_MOSAIC_SLAB -> eb
    net.minecraft.world.item.Item CRIMSON_SLAB -> ec
    net.minecraft.world.item.Item WARPED_SLAB -> ed
    net.minecraft.world.item.Item STONE_SLAB -> ee
    net.minecraft.world.item.Item SMOOTH_STONE_SLAB -> ef
    net.minecraft.world.item.Item SANDSTONE_SLAB -> eg
    net.minecraft.world.item.Item CUT_STANDSTONE_SLAB -> eh
    net.minecraft.world.item.Item PETRIFIED_OAK_SLAB -> ei
    net.minecraft.world.item.Item COBBLESTONE_SLAB -> ej
    net.minecraft.world.item.Item BRICK_SLAB -> ek
    net.minecraft.world.item.Item STONE_BRICK_SLAB -> el
    net.minecraft.world.item.Item MUD_BRICK_SLAB -> em
    net.minecraft.world.item.Item NETHER_BRICK_SLAB -> en
    net.minecraft.world.item.Item QUARTZ_SLAB -> eo
    net.minecraft.world.item.Item RED_SANDSTONE_SLAB -> ep
    net.minecraft.world.item.Item CUT_RED_SANDSTONE_SLAB -> eq
    net.minecraft.world.item.Item PURPUR_SLAB -> er
    net.minecraft.world.item.Item PRISMARINE_SLAB -> es
    net.minecraft.world.item.Item PRISMARINE_BRICK_SLAB -> et
    net.minecraft.world.item.Item DARK_PRISMARINE_SLAB -> eu
    net.minecraft.world.item.Item SMOOTH_QUARTZ -> ev
    net.minecraft.world.item.Item SMOOTH_RED_SANDSTONE -> ew
    net.minecraft.world.item.Item SMOOTH_SANDSTONE -> ex
    net.minecraft.world.item.Item SMOOTH_STONE -> ey
    net.minecraft.world.item.Item BRICKS -> ez
    net.minecraft.world.item.Item BOOKSHELF -> eA
    net.minecraft.world.item.Item CHISELED_BOOKSHELF -> eB
    net.minecraft.world.item.Item DECORATED_POT -> eC
    net.minecraft.world.item.Item MOSSY_COBBLESTONE -> eD
    net.minecraft.world.item.Item OBSIDIAN -> eE
    net.minecraft.world.item.Item TORCH -> eF
    net.minecraft.world.item.Item END_ROD -> eG
    net.minecraft.world.item.Item CHORUS_PLANT -> eH
    net.minecraft.world.item.Item CHORUS_FLOWER -> eI
    net.minecraft.world.item.Item PURPUR_BLOCK -> eJ
    net.minecraft.world.item.Item PURPUR_PILLAR -> eK
    net.minecraft.world.item.Item PURPUR_STAIRS -> eL
    net.minecraft.world.item.Item SPAWNER -> eM
    net.minecraft.world.item.Item CHEST -> eN
    net.minecraft.world.item.Item CRAFTING_TABLE -> eO
    net.minecraft.world.item.Item FARMLAND -> eP
    net.minecraft.world.item.Item FURNACE -> eQ
    net.minecraft.world.item.Item LADDER -> eR
    net.minecraft.world.item.Item COBBLESTONE_STAIRS -> eS
    net.minecraft.world.item.Item SNOW -> eT
    net.minecraft.world.item.Item ICE -> eU
    net.minecraft.world.item.Item SNOW_BLOCK -> eV
    net.minecraft.world.item.Item CACTUS -> eW
    net.minecraft.world.item.Item CLAY -> eX
    net.minecraft.world.item.Item JUKEBOX -> eY
    net.minecraft.world.item.Item OAK_FENCE -> eZ
    net.minecraft.world.item.Item SPRUCE_FENCE -> fa
    net.minecraft.world.item.Item BIRCH_FENCE -> fb
    net.minecraft.world.item.Item JUNGLE_FENCE -> fc
    net.minecraft.world.item.Item ACACIA_FENCE -> fd
    net.minecraft.world.item.Item CHERRY_FENCE -> fe
    net.minecraft.world.item.Item DARK_OAK_FENCE -> ff
    net.minecraft.world.item.Item MANGROVE_FENCE -> fg
    net.minecraft.world.item.Item BAMBOO_FENCE -> fh
    net.minecraft.world.item.Item CRIMSON_FENCE -> fi
    net.minecraft.world.item.Item WARPED_FENCE -> fj
    net.minecraft.world.item.Item PUMPKIN -> fk
    net.minecraft.world.item.Item CARVED_PUMPKIN -> fl
    net.minecraft.world.item.Item JACK_O_LANTERN -> fm
    net.minecraft.world.item.Item NETHERRACK -> fn
    net.minecraft.world.item.Item SOUL_SAND -> fo
    net.minecraft.world.item.Item SOUL_SOIL -> fp
    net.minecraft.world.item.Item BASALT -> fq
    net.minecraft.world.item.Item POLISHED_BASALT -> fr
    net.minecraft.world.item.Item SMOOTH_BASALT -> fs
    net.minecraft.world.item.Item SOUL_TORCH -> ft
    net.minecraft.world.item.Item GLOWSTONE -> fu
    net.minecraft.world.item.Item INFESTED_STONE -> fv
    net.minecraft.world.item.Item INFESTED_COBBLESTONE -> fw
    net.minecraft.world.item.Item INFESTED_STONE_BRICKS -> fx
    net.minecraft.world.item.Item INFESTED_MOSSY_STONE_BRICKS -> fy
    net.minecraft.world.item.Item INFESTED_CRACKED_STONE_BRICKS -> fz
    net.minecraft.world.item.Item INFESTED_CHISELED_STONE_BRICKS -> fA
    net.minecraft.world.item.Item INFESTED_DEEPSLATE -> fB
    net.minecraft.world.item.Item STONE_BRICKS -> fC
    net.minecraft.world.item.Item MOSSY_STONE_BRICKS -> fD
    net.minecraft.world.item.Item CRACKED_STONE_BRICKS -> fE
    net.minecraft.world.item.Item CHISELED_STONE_BRICKS -> fF
    net.minecraft.world.item.Item PACKED_MUD -> fG
    net.minecraft.world.item.Item MUD_BRICKS -> fH
    net.minecraft.world.item.Item DEEPSLATE_BRICKS -> fI
    net.minecraft.world.item.Item CRACKED_DEEPSLATE_BRICKS -> fJ
    net.minecraft.world.item.Item DEEPSLATE_TILES -> fK
    net.minecraft.world.item.Item CRACKED_DEEPSLATE_TILES -> fL
    net.minecraft.world.item.Item CHISELED_DEEPSLATE -> fM
    net.minecraft.world.item.Item REINFORCED_DEEPSLATE -> fN
    net.minecraft.world.item.Item BROWN_MUSHROOM_BLOCK -> fO
    net.minecraft.world.item.Item RED_MUSHROOM_BLOCK -> fP
    net.minecraft.world.item.Item MUSHROOM_STEM -> fQ
    net.minecraft.world.item.Item IRON_BARS -> fR
    net.minecraft.world.item.Item CHAIN -> fS
    net.minecraft.world.item.Item GLASS_PANE -> fT
    net.minecraft.world.item.Item MELON -> fU
    net.minecraft.world.item.Item VINE -> fV
    net.minecraft.world.item.Item GLOW_LICHEN -> fW
    net.minecraft.world.item.Item BRICK_STAIRS -> fX
    net.minecraft.world.item.Item STONE_BRICK_STAIRS -> fY
    net.minecraft.world.item.Item MUD_BRICK_STAIRS -> fZ
    net.minecraft.world.item.Item MYCELIUM -> ga
    net.minecraft.world.item.Item LILY_PAD -> gb
    net.minecraft.world.item.Item NETHER_BRICKS -> gc
    net.minecraft.world.item.Item CRACKED_NETHER_BRICKS -> gd
    net.minecraft.world.item.Item CHISELED_NETHER_BRICKS -> ge
    net.minecraft.world.item.Item NETHER_BRICK_FENCE -> gf
    net.minecraft.world.item.Item NETHER_BRICK_STAIRS -> gg
    net.minecraft.world.item.Item SCULK -> gh
    net.minecraft.world.item.Item SCULK_VEIN -> gi
    net.minecraft.world.item.Item SCULK_CATALYST -> gj
    net.minecraft.world.item.Item SCULK_SHRIEKER -> gk
    net.minecraft.world.item.Item ENCHANTING_TABLE -> gl
    net.minecraft.world.item.Item END_PORTAL_FRAME -> gm
    net.minecraft.world.item.Item END_STONE -> gn
    net.minecraft.world.item.Item END_STONE_BRICKS -> go
    net.minecraft.world.item.Item DRAGON_EGG -> gp
    net.minecraft.world.item.Item SANDSTONE_STAIRS -> gq
    net.minecraft.world.item.Item ENDER_CHEST -> gr
    net.minecraft.world.item.Item EMERALD_BLOCK -> gs
    net.minecraft.world.item.Item OAK_STAIRS -> gt
    net.minecraft.world.item.Item SPRUCE_STAIRS -> gu
    net.minecraft.world.item.Item BIRCH_STAIRS -> gv
    net.minecraft.world.item.Item JUNGLE_STAIRS -> gw
    net.minecraft.world.item.Item ACACIA_STAIRS -> gx
    net.minecraft.world.item.Item CHERRY_STAIRS -> gy
    net.minecraft.world.item.Item DARK_OAK_STAIRS -> gz
    net.minecraft.world.item.Item MANGROVE_STAIRS -> gA
    net.minecraft.world.item.Item BAMBOO_STAIRS -> gB
    net.minecraft.world.item.Item BAMBOO_MOSAIC_STAIRS -> gC
    net.minecraft.world.item.Item CRIMSON_STAIRS -> gD
    net.minecraft.world.item.Item WARPED_STAIRS -> gE
    net.minecraft.world.item.Item COMMAND_BLOCK -> gF
    net.minecraft.world.item.Item BEACON -> gG
    net.minecraft.world.item.Item COBBLESTONE_WALL -> gH
    net.minecraft.world.item.Item MOSSY_COBBLESTONE_WALL -> gI
    net.minecraft.world.item.Item BRICK_WALL -> gJ
    net.minecraft.world.item.Item PRISMARINE_WALL -> gK
    net.minecraft.world.item.Item RED_SANDSTONE_WALL -> gL
    net.minecraft.world.item.Item MOSSY_STONE_BRICK_WALL -> gM
    net.minecraft.world.item.Item GRANITE_WALL -> gN
    net.minecraft.world.item.Item STONE_BRICK_WALL -> gO
    net.minecraft.world.item.Item MUD_BRICK_WALL -> gP
    net.minecraft.world.item.Item NETHER_BRICK_WALL -> gQ
    net.minecraft.world.item.Item ANDESITE_WALL -> gR
    net.minecraft.world.item.Item RED_NETHER_BRICK_WALL -> gS
    net.minecraft.world.item.Item SANDSTONE_WALL -> gT
    net.minecraft.world.item.Item END_STONE_BRICK_WALL -> gU
    net.minecraft.world.item.Item DIORITE_WALL -> gV
    net.minecraft.world.item.Item BLACKSTONE_WALL -> gW
    net.minecraft.world.item.Item POLISHED_BLACKSTONE_WALL -> gX
    net.minecraft.world.item.Item POLISHED_BLACKSTONE_BRICK_WALL -> gY
    net.minecraft.world.item.Item COBBLED_DEEPSLATE_WALL -> gZ
    net.minecraft.world.item.Item POLISHED_DEEPSLATE_WALL -> ha
    net.minecraft.world.item.Item DEEPSLATE_BRICK_WALL -> hb
    net.minecraft.world.item.Item DEEPSLATE_TILE_WALL -> hc
    net.minecraft.world.item.Item ANVIL -> hd
    net.minecraft.world.item.Item CHIPPED_ANVIL -> he
    net.minecraft.world.item.Item DAMAGED_ANVIL -> hf
    net.minecraft.world.item.Item CHISELED_QUARTZ_BLOCK -> hg
    net.minecraft.world.item.Item QUARTZ_BLOCK -> hh
    net.minecraft.world.item.Item QUARTZ_BRICKS -> hi
    net.minecraft.world.item.Item QUARTZ_PILLAR -> hj
    net.minecraft.world.item.Item QUARTZ_STAIRS -> hk
    net.minecraft.world.item.Item WHITE_TERRACOTTA -> hl
    net.minecraft.world.item.Item ORANGE_TERRACOTTA -> hm
    net.minecraft.world.item.Item MAGENTA_TERRACOTTA -> hn
    net.minecraft.world.item.Item LIGHT_BLUE_TERRACOTTA -> ho
    net.minecraft.world.item.Item YELLOW_TERRACOTTA -> hp
    net.minecraft.world.item.Item LIME_TERRACOTTA -> hq
    net.minecraft.world.item.Item PINK_TERRACOTTA -> hr
    net.minecraft.world.item.Item GRAY_TERRACOTTA -> hs
    net.minecraft.world.item.Item LIGHT_GRAY_TERRACOTTA -> ht
    net.minecraft.world.item.Item CYAN_TERRACOTTA -> hu
    net.minecraft.world.item.Item PURPLE_TERRACOTTA -> hv
    net.minecraft.world.item.Item BLUE_TERRACOTTA -> hw
    net.minecraft.world.item.Item BROWN_TERRACOTTA -> hx
    net.minecraft.world.item.Item GREEN_TERRACOTTA -> hy
    net.minecraft.world.item.Item RED_TERRACOTTA -> hz
    net.minecraft.world.item.Item BLACK_TERRACOTTA -> hA
    net.minecraft.world.item.Item BARRIER -> hB
    net.minecraft.world.item.Item LIGHT -> hC
    net.minecraft.world.item.Item HAY_BLOCK -> hD
    net.minecraft.world.item.Item WHITE_CARPET -> hE
    net.minecraft.world.item.Item ORANGE_CARPET -> hF
    net.minecraft.world.item.Item MAGENTA_CARPET -> hG
    net.minecraft.world.item.Item LIGHT_BLUE_CARPET -> hH
    net.minecraft.world.item.Item YELLOW_CARPET -> hI
    net.minecraft.world.item.Item LIME_CARPET -> hJ
    net.minecraft.world.item.Item PINK_CARPET -> hK
    net.minecraft.world.item.Item GRAY_CARPET -> hL
    net.minecraft.world.item.Item LIGHT_GRAY_CARPET -> hM
    net.minecraft.world.item.Item CYAN_CARPET -> hN
    net.minecraft.world.item.Item PURPLE_CARPET -> hO
    net.minecraft.world.item.Item BLUE_CARPET -> hP
    net.minecraft.world.item.Item BROWN_CARPET -> hQ
    net.minecraft.world.item.Item GREEN_CARPET -> hR
    net.minecraft.world.item.Item RED_CARPET -> hS
    net.minecraft.world.item.Item BLACK_CARPET -> hT
    net.minecraft.world.item.Item TERRACOTTA -> hU
    net.minecraft.world.item.Item PACKED_ICE -> hV
    net.minecraft.world.item.Item DIRT_PATH -> hW
    net.minecraft.world.item.Item SUNFLOWER -> hX
    net.minecraft.world.item.Item LILAC -> hY
    net.minecraft.world.item.Item ROSE_BUSH -> hZ
    net.minecraft.world.item.Item PEONY -> ia
    net.minecraft.world.item.Item TALL_GRASS -> ib
    net.minecraft.world.item.Item LARGE_FERN -> ic
    net.minecraft.world.item.Item WHITE_STAINED_GLASS -> id
    net.minecraft.world.item.Item ORANGE_STAINED_GLASS -> ie
    net.minecraft.world.item.Item MAGENTA_STAINED_GLASS -> if
    net.minecraft.world.item.Item LIGHT_BLUE_STAINED_GLASS -> ig
    net.minecraft.world.item.Item YELLOW_STAINED_GLASS -> ih
    net.minecraft.world.item.Item LIME_STAINED_GLASS -> ii
    net.minecraft.world.item.Item PINK_STAINED_GLASS -> ij
    net.minecraft.world.item.Item GRAY_STAINED_GLASS -> ik
    net.minecraft.world.item.Item LIGHT_GRAY_STAINED_GLASS -> il
    net.minecraft.world.item.Item CYAN_STAINED_GLASS -> im
    net.minecraft.world.item.Item PURPLE_STAINED_GLASS -> in
    net.minecraft.world.item.Item BLUE_STAINED_GLASS -> io
    net.minecraft.world.item.Item BROWN_STAINED_GLASS -> ip
    net.minecraft.world.item.Item GREEN_STAINED_GLASS -> iq
    net.minecraft.world.item.Item RED_STAINED_GLASS -> ir
    net.minecraft.world.item.Item BLACK_STAINED_GLASS -> is
    net.minecraft.world.item.Item WHITE_STAINED_GLASS_PANE -> it
    net.minecraft.world.item.Item ORANGE_STAINED_GLASS_PANE -> iu
    net.minecraft.world.item.Item MAGENTA_STAINED_GLASS_PANE -> iv
    net.minecraft.world.item.Item LIGHT_BLUE_STAINED_GLASS_PANE -> iw
    net.minecraft.world.item.Item YELLOW_STAINED_GLASS_PANE -> ix
    net.minecraft.world.item.Item LIME_STAINED_GLASS_PANE -> iy
    net.minecraft.world.item.Item PINK_STAINED_GLASS_PANE -> iz
    net.minecraft.world.item.Item GRAY_STAINED_GLASS_PANE -> iA
    net.minecraft.world.item.Item LIGHT_GRAY_STAINED_GLASS_PANE -> iB
    net.minecraft.world.item.Item CYAN_STAINED_GLASS_PANE -> iC
    net.minecraft.world.item.Item PURPLE_STAINED_GLASS_PANE -> iD
    net.minecraft.world.item.Item BLUE_STAINED_GLASS_PANE -> iE
    net.minecraft.world.item.Item BROWN_STAINED_GLASS_PANE -> iF
    net.minecraft.world.item.Item GREEN_STAINED_GLASS_PANE -> iG
    net.minecraft.world.item.Item RED_STAINED_GLASS_PANE -> iH
    net.minecraft.world.item.Item BLACK_STAINED_GLASS_PANE -> iI
    net.minecraft.world.item.Item PRISMARINE -> iJ
    net.minecraft.world.item.Item PRISMARINE_BRICKS -> iK
    net.minecraft.world.item.Item DARK_PRISMARINE -> iL
    net.minecraft.world.item.Item PRISMARINE_STAIRS -> iM
    net.minecraft.world.item.Item PRISMARINE_BRICK_STAIRS -> iN
    net.minecraft.world.item.Item DARK_PRISMARINE_STAIRS -> iO
    net.minecraft.world.item.Item SEA_LANTERN -> iP
    net.minecraft.world.item.Item RED_SANDSTONE -> iQ
    net.minecraft.world.item.Item CHISELED_RED_SANDSTONE -> iR
    net.minecraft.world.item.Item CUT_RED_SANDSTONE -> iS
    net.minecraft.world.item.Item RED_SANDSTONE_STAIRS -> iT
    net.minecraft.world.item.Item REPEATING_COMMAND_BLOCK -> iU
    net.minecraft.world.item.Item CHAIN_COMMAND_BLOCK -> iV
    net.minecraft.world.item.Item MAGMA_BLOCK -> iW
    net.minecraft.world.item.Item NETHER_WART_BLOCK -> iX
    net.minecraft.world.item.Item WARPED_WART_BLOCK -> iY
    net.minecraft.world.item.Item RED_NETHER_BRICKS -> iZ
    net.minecraft.world.item.Item BONE_BLOCK -> ja
    net.minecraft.world.item.Item STRUCTURE_VOID -> jb
    net.minecraft.world.item.Item SHULKER_BOX -> jc
    net.minecraft.world.item.Item WHITE_SHULKER_BOX -> jd
    net.minecraft.world.item.Item ORANGE_SHULKER_BOX -> je
    net.minecraft.world.item.Item MAGENTA_SHULKER_BOX -> jf
    net.minecraft.world.item.Item LIGHT_BLUE_SHULKER_BOX -> jg
    net.minecraft.world.item.Item YELLOW_SHULKER_BOX -> jh
    net.minecraft.world.item.Item LIME_SHULKER_BOX -> ji
    net.minecraft.world.item.Item PINK_SHULKER_BOX -> jj
    net.minecraft.world.item.Item GRAY_SHULKER_BOX -> jk
    net.minecraft.world.item.Item LIGHT_GRAY_SHULKER_BOX -> jl
    net.minecraft.world.item.Item CYAN_SHULKER_BOX -> jm
    net.minecraft.world.item.Item PURPLE_SHULKER_BOX -> jn
    net.minecraft.world.item.Item BLUE_SHULKER_BOX -> jo
    net.minecraft.world.item.Item BROWN_SHULKER_BOX -> jp
    net.minecraft.world.item.Item GREEN_SHULKER_BOX -> jq
    net.minecraft.world.item.Item RED_SHULKER_BOX -> jr
    net.minecraft.world.item.Item BLACK_SHULKER_BOX -> js
    net.minecraft.world.item.Item WHITE_GLAZED_TERRACOTTA -> jt
    net.minecraft.world.item.Item ORANGE_GLAZED_TERRACOTTA -> ju
    net.minecraft.world.item.Item MAGENTA_GLAZED_TERRACOTTA -> jv
    net.minecraft.world.item.Item LIGHT_BLUE_GLAZED_TERRACOTTA -> jw
    net.minecraft.world.item.Item YELLOW_GLAZED_TERRACOTTA -> jx
    net.minecraft.world.item.Item LIME_GLAZED_TERRACOTTA -> jy
    net.minecraft.world.item.Item PINK_GLAZED_TERRACOTTA -> jz
    net.minecraft.world.item.Item GRAY_GLAZED_TERRACOTTA -> jA
    net.minecraft.world.item.Item LIGHT_GRAY_GLAZED_TERRACOTTA -> jB
    net.minecraft.world.item.Item CYAN_GLAZED_TERRACOTTA -> jC
    net.minecraft.world.item.Item PURPLE_GLAZED_TERRACOTTA -> jD
    net.minecraft.world.item.Item BLUE_GLAZED_TERRACOTTA -> jE
    net.minecraft.world.item.Item BROWN_GLAZED_TERRACOTTA -> jF
    net.minecraft.world.item.Item GREEN_GLAZED_TERRACOTTA -> jG
    net.minecraft.world.item.Item RED_GLAZED_TERRACOTTA -> jH
    net.minecraft.world.item.Item BLACK_GLAZED_TERRACOTTA -> jI
    net.minecraft.world.item.Item WHITE_CONCRETE -> jJ
    net.minecraft.world.item.Item ORANGE_CONCRETE -> jK
    net.minecraft.world.item.Item MAGENTA_CONCRETE -> jL
    net.minecraft.world.item.Item LIGHT_BLUE_CONCRETE -> jM
    net.minecraft.world.item.Item YELLOW_CONCRETE -> jN
    net.minecraft.world.item.Item LIME_CONCRETE -> jO
    net.minecraft.world.item.Item PINK_CONCRETE -> jP
    net.minecraft.world.item.Item GRAY_CONCRETE -> jQ
    net.minecraft.world.item.Item LIGHT_GRAY_CONCRETE -> jR
    net.minecraft.world.item.Item CYAN_CONCRETE -> jS
    net.minecraft.world.item.Item PURPLE_CONCRETE -> jT
    net.minecraft.world.item.Item BLUE_CONCRETE -> jU
    net.minecraft.world.item.Item BROWN_CONCRETE -> jV
    net.minecraft.world.item.Item GREEN_CONCRETE -> jW
    net.minecraft.world.item.Item RED_CONCRETE -> jX
    net.minecraft.world.item.Item BLACK_CONCRETE -> jY
    net.minecraft.world.item.Item WHITE_CONCRETE_POWDER -> jZ
    net.minecraft.world.item.Item ORANGE_CONCRETE_POWDER -> ka
    net.minecraft.world.item.Item MAGENTA_CONCRETE_POWDER -> kb
    net.minecraft.world.item.Item LIGHT_BLUE_CONCRETE_POWDER -> kc
    net.minecraft.world.item.Item YELLOW_CONCRETE_POWDER -> kd
    net.minecraft.world.item.Item LIME_CONCRETE_POWDER -> ke
    net.minecraft.world.item.Item PINK_CONCRETE_POWDER -> kf
    net.minecraft.world.item.Item GRAY_CONCRETE_POWDER -> kg
    net.minecraft.world.item.Item LIGHT_GRAY_CONCRETE_POWDER -> kh
    net.minecraft.world.item.Item CYAN_CONCRETE_POWDER -> ki
    net.minecraft.world.item.Item PURPLE_CONCRETE_POWDER -> kj
    net.minecraft.world.item.Item BLUE_CONCRETE_POWDER -> kk
    net.minecraft.world.item.Item BROWN_CONCRETE_POWDER -> kl
    net.minecraft.world.item.Item GREEN_CONCRETE_POWDER -> km
    net.minecraft.world.item.Item RED_CONCRETE_POWDER -> kn
    net.minecraft.world.item.Item BLACK_CONCRETE_POWDER -> ko
    net.minecraft.world.item.Item TURTLE_EGG -> kp
    net.minecraft.world.item.Item SNIFFER_EGG -> kq
    net.minecraft.world.item.Item DEAD_TUBE_CORAL_BLOCK -> kr
    net.minecraft.world.item.Item DEAD_BRAIN_CORAL_BLOCK -> ks
    net.minecraft.world.item.Item DEAD_BUBBLE_CORAL_BLOCK -> kt
    net.minecraft.world.item.Item DEAD_FIRE_CORAL_BLOCK -> ku
    net.minecraft.world.item.Item DEAD_HORN_CORAL_BLOCK -> kv
    net.minecraft.world.item.Item TUBE_CORAL_BLOCK -> kw
    net.minecraft.world.item.Item BRAIN_CORAL_BLOCK -> kx
    net.minecraft.world.item.Item BUBBLE_CORAL_BLOCK -> ky
    net.minecraft.world.item.Item FIRE_CORAL_BLOCK -> kz
    net.minecraft.world.item.Item HORN_CORAL_BLOCK -> kA
    net.minecraft.world.item.Item TUBE_CORAL -> kB
    net.minecraft.world.item.Item BRAIN_CORAL -> kC
    net.minecraft.world.item.Item BUBBLE_CORAL -> kD
    net.minecraft.world.item.Item FIRE_CORAL -> kE
    net.minecraft.world.item.Item HORN_CORAL -> kF
    net.minecraft.world.item.Item DEAD_BRAIN_CORAL -> kG
    net.minecraft.world.item.Item DEAD_BUBBLE_CORAL -> kH
    net.minecraft.world.item.Item DEAD_FIRE_CORAL -> kI
    net.minecraft.world.item.Item DEAD_HORN_CORAL -> kJ
    net.minecraft.world.item.Item DEAD_TUBE_CORAL -> kK
    net.minecraft.world.item.Item TUBE_CORAL_FAN -> kL
    net.minecraft.world.item.Item BRAIN_CORAL_FAN -> kM
    net.minecraft.world.item.Item BUBBLE_CORAL_FAN -> kN
    net.minecraft.world.item.Item FIRE_CORAL_FAN -> kO
    net.minecraft.world.item.Item HORN_CORAL_FAN -> kP
    net.minecraft.world.item.Item DEAD_TUBE_CORAL_FAN -> kQ
    net.minecraft.world.item.Item DEAD_BRAIN_CORAL_FAN -> kR
    net.minecraft.world.item.Item DEAD_BUBBLE_CORAL_FAN -> kS
    net.minecraft.world.item.Item DEAD_FIRE_CORAL_FAN -> kT
    net.minecraft.world.item.Item DEAD_HORN_CORAL_FAN -> kU
    net.minecraft.world.item.Item BLUE_ICE -> kV
    net.minecraft.world.item.Item CONDUIT -> kW
    net.minecraft.world.item.Item POLISHED_GRANITE_STAIRS -> kX
    net.minecraft.world.item.Item SMOOTH_RED_SANDSTONE_STAIRS -> kY
    net.minecraft.world.item.Item MOSSY_STONE_BRICK_STAIRS -> kZ
    net.minecraft.world.item.Item POLISHED_DIORITE_STAIRS -> la
    net.minecraft.world.item.Item MOSSY_COBBLESTONE_STAIRS -> lb
    net.minecraft.world.item.Item END_STONE_BRICK_STAIRS -> lc
    net.minecraft.world.item.Item STONE_STAIRS -> ld
    net.minecraft.world.item.Item SMOOTH_SANDSTONE_STAIRS -> le
    net.minecraft.world.item.Item SMOOTH_QUARTZ_STAIRS -> lf
    net.minecraft.world.item.Item GRANITE_STAIRS -> lg
    net.minecraft.world.item.Item ANDESITE_STAIRS -> lh
    net.minecraft.world.item.Item RED_NETHER_BRICK_STAIRS -> li
    net.minecraft.world.item.Item POLISHED_ANDESITE_STAIRS -> lj
    net.minecraft.world.item.Item DIORITE_STAIRS -> lk
    net.minecraft.world.item.Item COBBLED_DEEPSLATE_STAIRS -> ll
    net.minecraft.world.item.Item POLISHED_DEEPSLATE_STAIRS -> lm
    net.minecraft.world.item.Item DEEPSLATE_BRICK_STAIRS -> ln
    net.minecraft.world.item.Item DEEPSLATE_TILE_STAIRS -> lo
    net.minecraft.world.item.Item POLISHED_GRANITE_SLAB -> lp
    net.minecraft.world.item.Item SMOOTH_RED_SANDSTONE_SLAB -> lq
    net.minecraft.world.item.Item MOSSY_STONE_BRICK_SLAB -> lr
    net.minecraft.world.item.Item POLISHED_DIORITE_SLAB -> ls
    net.minecraft.world.item.Item MOSSY_COBBLESTONE_SLAB -> lt
    net.minecraft.world.item.Item END_STONE_BRICK_SLAB -> lu
    net.minecraft.world.item.Item SMOOTH_SANDSTONE_SLAB -> lv
    net.minecraft.world.item.Item SMOOTH_QUARTZ_SLAB -> lw
    net.minecraft.world.item.Item GRANITE_SLAB -> lx
    net.minecraft.world.item.Item ANDESITE_SLAB -> ly
    net.minecraft.world.item.Item RED_NETHER_BRICK_SLAB -> lz
    net.minecraft.world.item.Item POLISHED_ANDESITE_SLAB -> lA
    net.minecraft.world.item.Item DIORITE_SLAB -> lB
    net.minecraft.world.item.Item COBBLED_DEEPSLATE_SLAB -> lC
    net.minecraft.world.item.Item POLISHED_DEEPSLATE_SLAB -> lD
    net.minecraft.world.item.Item DEEPSLATE_BRICK_SLAB -> lE
    net.minecraft.world.item.Item DEEPSLATE_TILE_SLAB -> lF
    net.minecraft.world.item.Item SCAFFOLDING -> lG
    net.minecraft.world.item.Item REDSTONE -> lH
    net.minecraft.world.item.Item REDSTONE_TORCH -> lI
    net.minecraft.world.item.Item REDSTONE_BLOCK -> lJ
    net.minecraft.world.item.Item REPEATER -> lK
    net.minecraft.world.item.Item COMPARATOR -> lL
    net.minecraft.world.item.Item PISTON -> lM
    net.minecraft.world.item.Item STICKY_PISTON -> lN
    net.minecraft.world.item.Item SLIME_BLOCK -> lO
    net.minecraft.world.item.Item HONEY_BLOCK -> lP
    net.minecraft.world.item.Item OBSERVER -> lQ
    net.minecraft.world.item.Item HOPPER -> lR
    net.minecraft.world.item.Item DISPENSER -> lS
    net.minecraft.world.item.Item DROPPER -> lT
    net.minecraft.world.item.Item LECTERN -> lU
    net.minecraft.world.item.Item TARGET -> lV
    net.minecraft.world.item.Item LEVER -> lW
    net.minecraft.world.item.Item LIGHTNING_ROD -> lX
    net.minecraft.world.item.Item DAYLIGHT_DETECTOR -> lY
    net.minecraft.world.item.Item SCULK_SENSOR -> lZ
    net.minecraft.world.item.Item CALIBRATED_SCULK_SENSOR -> ma
    net.minecraft.world.item.Item TRIPWIRE_HOOK -> mb
    net.minecraft.world.item.Item TRAPPED_CHEST -> mc
    net.minecraft.world.item.Item TNT -> md
    net.minecraft.world.item.Item REDSTONE_LAMP -> me
    net.minecraft.world.item.Item NOTE_BLOCK -> mf
    net.minecraft.world.item.Item STONE_BUTTON -> mg
    net.minecraft.world.item.Item POLISHED_BLACKSTONE_BUTTON -> mh
    net.minecraft.world.item.Item OAK_BUTTON -> mi
    net.minecraft.world.item.Item SPRUCE_BUTTON -> mj
    net.minecraft.world.item.Item BIRCH_BUTTON -> mk
    net.minecraft.world.item.Item JUNGLE_BUTTON -> ml
    net.minecraft.world.item.Item ACACIA_BUTTON -> mm
    net.minecraft.world.item.Item CHERRY_BUTTON -> mn
    net.minecraft.world.item.Item DARK_OAK_BUTTON -> mo
    net.minecraft.world.item.Item MANGROVE_BUTTON -> mp
    net.minecraft.world.item.Item BAMBOO_BUTTON -> mq
    net.minecraft.world.item.Item CRIMSON_BUTTON -> mr
    net.minecraft.world.item.Item WARPED_BUTTON -> ms
    net.minecraft.world.item.Item STONE_PRESSURE_PLATE -> mt
    net.minecraft.world.item.Item POLISHED_BLACKSTONE_PRESSURE_PLATE -> mu
    net.minecraft.world.item.Item LIGHT_WEIGHTED_PRESSURE_PLATE -> mv
    net.minecraft.world.item.Item HEAVY_WEIGHTED_PRESSURE_PLATE -> mw
    net.minecraft.world.item.Item OAK_PRESSURE_PLATE -> mx
    net.minecraft.world.item.Item SPRUCE_PRESSURE_PLATE -> my
    net.minecraft.world.item.Item BIRCH_PRESSURE_PLATE -> mz
    net.minecraft.world.item.Item JUNGLE_PRESSURE_PLATE -> mA
    net.minecraft.world.item.Item ACACIA_PRESSURE_PLATE -> mB
    net.minecraft.world.item.Item CHERRY_PRESSURE_PLATE -> mC
    net.minecraft.world.item.Item DARK_OAK_PRESSURE_PLATE -> mD
    net.minecraft.world.item.Item MANGROVE_PRESSURE_PLATE -> mE
    net.minecraft.world.item.Item BAMBOO_PRESSURE_PLATE -> mF
    net.minecraft.world.item.Item CRIMSON_PRESSURE_PLATE -> mG
    net.minecraft.world.item.Item WARPED_PRESSURE_PLATE -> mH
    net.minecraft.world.item.Item IRON_DOOR -> mI
    net.minecraft.world.item.Item OAK_DOOR -> mJ
    net.minecraft.world.item.Item SPRUCE_DOOR -> mK
    net.minecraft.world.item.Item BIRCH_DOOR -> mL
    net.minecraft.world.item.Item JUNGLE_DOOR -> mM
    net.minecraft.world.item.Item ACACIA_DOOR -> mN
    net.minecraft.world.item.Item CHERRY_DOOR -> mO
    net.minecraft.world.item.Item DARK_OAK_DOOR -> mP
    net.minecraft.world.item.Item MANGROVE_DOOR -> mQ
    net.minecraft.world.item.Item BAMBOO_DOOR -> mR
    net.minecraft.world.item.Item CRIMSON_DOOR -> mS
    net.minecraft.world.item.Item WARPED_DOOR -> mT
    net.minecraft.world.item.Item COPPER_DOOR -> mU
    net.minecraft.world.item.Item EXPOSED_COPPER_DOOR -> mV
    net.minecraft.world.item.Item WEATHERED_COPPER_DOOR -> mW
    net.minecraft.world.item.Item OXIDIZED_COPPER_DOOR -> mX
    net.minecraft.world.item.Item WAXED_COPPER_DOOR -> mY
    net.minecraft.world.item.Item WAXED_EXPOSED_COPPER_DOOR -> mZ
    net.minecraft.world.item.Item WAXED_WEATHERED_COPPER_DOOR -> na
    net.minecraft.world.item.Item WAXED_OXIDIZED_COPPER_DOOR -> nb
    net.minecraft.world.item.Item IRON_TRAPDOOR -> nc
    net.minecraft.world.item.Item OAK_TRAPDOOR -> nd
    net.minecraft.world.item.Item SPRUCE_TRAPDOOR -> ne
    net.minecraft.world.item.Item BIRCH_TRAPDOOR -> nf
    net.minecraft.world.item.Item JUNGLE_TRAPDOOR -> ng
    net.minecraft.world.item.Item ACACIA_TRAPDOOR -> nh
    net.minecraft.world.item.Item CHERRY_TRAPDOOR -> ni
    net.minecraft.world.item.Item DARK_OAK_TRAPDOOR -> nj
    net.minecraft.world.item.Item MANGROVE_TRAPDOOR -> nk
    net.minecraft.world.item.Item BAMBOO_TRAPDOOR -> nl
    net.minecraft.world.item.Item CRIMSON_TRAPDOOR -> nm
    net.minecraft.world.item.Item WARPED_TRAPDOOR -> nn
    net.minecraft.world.item.Item COPPER_TRAPDOOR -> no
    net.minecraft.world.item.Item EXPOSED_COPPER_TRAPDOOR -> np
    net.minecraft.world.item.Item WEATHERED_COPPER_TRAPDOOR -> nq
    net.minecraft.world.item.Item OXIDIZED_COPPER_TRAPDOOR -> nr
    net.minecraft.world.item.Item WAXED_COPPER_TRAPDOOR -> ns
    net.minecraft.world.item.Item WAXED_EXPOSED_COPPER_TRAPDOOR -> nt
    net.minecraft.world.item.Item WAXED_WEATHERED_COPPER_TRAPDOOR -> nu
    net.minecraft.world.item.Item WAXED_OXIDIZED_COPPER_TRAPDOOR -> nv
    net.minecraft.world.item.Item OAK_FENCE_GATE -> nw
    net.minecraft.world.item.Item SPRUCE_FENCE_GATE -> nx
    net.minecraft.world.item.Item BIRCH_FENCE_GATE -> ny
    net.minecraft.world.item.Item JUNGLE_FENCE_GATE -> nz
    net.minecraft.world.item.Item ACACIA_FENCE_GATE -> nA
    net.minecraft.world.item.Item CHERRY_FENCE_GATE -> nB
    net.minecraft.world.item.Item DARK_OAK_FENCE_GATE -> nC
    net.minecraft.world.item.Item MANGROVE_FENCE_GATE -> nD
    net.minecraft.world.item.Item BAMBOO_FENCE_GATE -> nE
    net.minecraft.world.item.Item CRIMSON_FENCE_GATE -> nF
    net.minecraft.world.item.Item WARPED_FENCE_GATE -> nG
    net.minecraft.world.item.Item POWERED_RAIL -> nH
    net.minecraft.world.item.Item DETECTOR_RAIL -> nI
    net.minecraft.world.item.Item RAIL -> nJ
    net.minecraft.world.item.Item ACTIVATOR_RAIL -> nK
    net.minecraft.world.item.Item SADDLE -> nL
    net.minecraft.world.item.Item MINECART -> nM
    net.minecraft.world.item.Item CHEST_MINECART -> nN
    net.minecraft.world.item.Item FURNACE_MINECART -> nO
    net.minecraft.world.item.Item TNT_MINECART -> nP
    net.minecraft.world.item.Item HOPPER_MINECART -> nQ
    net.minecraft.world.item.Item CARROT_ON_A_STICK -> nR
    net.minecraft.world.item.Item WARPED_FUNGUS_ON_A_STICK -> nS
    net.minecraft.world.item.Item ELYTRA -> nT
    net.minecraft.world.item.Item OAK_BOAT -> nU
    net.minecraft.world.item.Item OAK_CHEST_BOAT -> nV
    net.minecraft.world.item.Item SPRUCE_BOAT -> nW
    net.minecraft.world.item.Item SPRUCE_CHEST_BOAT -> nX
    net.minecraft.world.item.Item BIRCH_BOAT -> nY
    net.minecraft.world.item.Item BIRCH_CHEST_BOAT -> nZ
    net.minecraft.world.item.Item JUNGLE_BOAT -> oa
    net.minecraft.world.item.Item JUNGLE_CHEST_BOAT -> ob
    net.minecraft.world.item.Item ACACIA_BOAT -> oc
    net.minecraft.world.item.Item ACACIA_CHEST_BOAT -> od
    net.minecraft.world.item.Item CHERRY_BOAT -> oe
    net.minecraft.world.item.Item CHERRY_CHEST_BOAT -> of
    net.minecraft.world.item.Item DARK_OAK_BOAT -> og
    net.minecraft.world.item.Item DARK_OAK_CHEST_BOAT -> oh
    net.minecraft.world.item.Item MANGROVE_BOAT -> oi
    net.minecraft.world.item.Item MANGROVE_CHEST_BOAT -> oj
    net.minecraft.world.item.Item BAMBOO_RAFT -> ok
    net.minecraft.world.item.Item BAMBOO_CHEST_RAFT -> ol
    net.minecraft.world.item.Item STRUCTURE_BLOCK -> om
    net.minecraft.world.item.Item JIGSAW -> on
    net.minecraft.world.item.Item TURTLE_HELMET -> oo
    net.minecraft.world.item.Item TURTLE_SCUTE -> op
    net.minecraft.world.item.Item ARMADILLO_SCUTE -> oq
    net.minecraft.world.item.Item WOLF_ARMOR -> or
    net.minecraft.world.item.Item FLINT_AND_STEEL -> os
    net.minecraft.world.item.Item BOWL -> ot
    net.minecraft.world.item.Item APPLE -> ou
    net.minecraft.world.item.Item BOW -> ov
    net.minecraft.world.item.Item ARROW -> ow
    net.minecraft.world.item.Item COAL -> ox
    net.minecraft.world.item.Item CHARCOAL -> oy
    net.minecraft.world.item.Item DIAMOND -> oz
    net.minecraft.world.item.Item EMERALD -> oA
    net.minecraft.world.item.Item LAPIS_LAZULI -> oB
    net.minecraft.world.item.Item QUARTZ -> oC
    net.minecraft.world.item.Item AMETHYST_SHARD -> oD
    net.minecraft.world.item.Item RAW_IRON -> oE
    net.minecraft.world.item.Item IRON_INGOT -> oF
    net.minecraft.world.item.Item RAW_COPPER -> oG
    net.minecraft.world.item.Item COPPER_INGOT -> oH
    net.minecraft.world.item.Item RAW_GOLD -> oI
    net.minecraft.world.item.Item GOLD_INGOT -> oJ
    net.minecraft.world.item.Item NETHERITE_INGOT -> oK
    net.minecraft.world.item.Item NETHERITE_SCRAP -> oL
    net.minecraft.world.item.Item WOODEN_SWORD -> oM
    net.minecraft.world.item.Item WOODEN_SHOVEL -> oN
    net.minecraft.world.item.Item WOODEN_PICKAXE -> oO
    net.minecraft.world.item.Item WOODEN_AXE -> oP
    net.minecraft.world.item.Item WOODEN_HOE -> oQ
    net.minecraft.world.item.Item STONE_SWORD -> oR
    net.minecraft.world.item.Item STONE_SHOVEL -> oS
    net.minecraft.world.item.Item STONE_PICKAXE -> oT
    net.minecraft.world.item.Item STONE_AXE -> oU
    net.minecraft.world.item.Item STONE_HOE -> oV
    net.minecraft.world.item.Item GOLDEN_SWORD -> oW
    net.minecraft.world.item.Item GOLDEN_SHOVEL -> oX
    net.minecraft.world.item.Item GOLDEN_PICKAXE -> oY
    net.minecraft.world.item.Item GOLDEN_AXE -> oZ
    net.minecraft.world.item.Item GOLDEN_HOE -> pa
    net.minecraft.world.item.Item IRON_SWORD -> pb
    net.minecraft.world.item.Item IRON_SHOVEL -> pc
    net.minecraft.world.item.Item IRON_PICKAXE -> pd
    net.minecraft.world.item.Item IRON_AXE -> pe
    net.minecraft.world.item.Item IRON_HOE -> pf
    net.minecraft.world.item.Item DIAMOND_SWORD -> pg
    net.minecraft.world.item.Item DIAMOND_SHOVEL -> ph
    net.minecraft.world.item.Item DIAMOND_PICKAXE -> pi
    net.minecraft.world.item.Item DIAMOND_AXE -> pj
    net.minecraft.world.item.Item DIAMOND_HOE -> pk
    net.minecraft.world.item.Item NETHERITE_SWORD -> pl
    net.minecraft.world.item.Item NETHERITE_SHOVEL -> pm
    net.minecraft.world.item.Item NETHERITE_PICKAXE -> pn
    net.minecraft.world.item.Item NETHERITE_AXE -> po
    net.minecraft.world.item.Item NETHERITE_HOE -> pp
    net.minecraft.world.item.Item STICK -> pq
    net.minecraft.world.item.Item MUSHROOM_STEW -> pr
    net.minecraft.world.item.Item STRING -> ps
    net.minecraft.world.item.Item FEATHER -> pt
    net.minecraft.world.item.Item GUNPOWDER -> pu
    net.minecraft.world.item.Item WHEAT_SEEDS -> pv
    net.minecraft.world.item.Item WHEAT -> pw
    net.minecraft.world.item.Item BREAD -> px
    net.minecraft.world.item.Item LEATHER_HELMET -> py
    net.minecraft.world.item.Item LEATHER_CHESTPLATE -> pz
    net.minecraft.world.item.Item LEATHER_LEGGINGS -> pA
    net.minecraft.world.item.Item LEATHER_BOOTS -> pB
    net.minecraft.world.item.Item CHAINMAIL_HELMET -> pC
    net.minecraft.world.item.Item CHAINMAIL_CHESTPLATE -> pD
    net.minecraft.world.item.Item CHAINMAIL_LEGGINGS -> pE
    net.minecraft.world.item.Item CHAINMAIL_BOOTS -> pF
    net.minecraft.world.item.Item IRON_HELMET -> pG
    net.minecraft.world.item.Item IRON_CHESTPLATE -> pH
    net.minecraft.world.item.Item IRON_LEGGINGS -> pI
    net.minecraft.world.item.Item IRON_BOOTS -> pJ
    net.minecraft.world.item.Item DIAMOND_HELMET -> pK
    net.minecraft.world.item.Item DIAMOND_CHESTPLATE -> pL
    net.minecraft.world.item.Item DIAMOND_LEGGINGS -> pM
    net.minecraft.world.item.Item DIAMOND_BOOTS -> pN
    net.minecraft.world.item.Item GOLDEN_HELMET -> pO
    net.minecraft.world.item.Item GOLDEN_CHESTPLATE -> pP
    net.minecraft.world.item.Item GOLDEN_LEGGINGS -> pQ
    net.minecraft.world.item.Item GOLDEN_BOOTS -> pR
    net.minecraft.world.item.Item NETHERITE_HELMET -> pS
    net.minecraft.world.item.Item NETHERITE_CHESTPLATE -> pT
    net.minecraft.world.item.Item NETHERITE_LEGGINGS -> pU
    net.minecraft.world.item.Item NETHERITE_BOOTS -> pV
    net.minecraft.world.item.Item FLINT -> pW
    net.minecraft.world.item.Item PORKCHOP -> pX
    net.minecraft.world.item.Item COOKED_PORKCHOP -> pY
    net.minecraft.world.item.Item PAINTING -> pZ
    net.minecraft.world.item.Item GOLDEN_APPLE -> qa
    net.minecraft.world.item.Item ENCHANTED_GOLDEN_APPLE -> qb
    net.minecraft.world.item.Item OAK_SIGN -> qc
    net.minecraft.world.item.Item SPRUCE_SIGN -> qd
    net.minecraft.world.item.Item BIRCH_SIGN -> qe
    net.minecraft.world.item.Item JUNGLE_SIGN -> qf
    net.minecraft.world.item.Item ACACIA_SIGN -> qg
    net.minecraft.world.item.Item CHERRY_SIGN -> qh
    net.minecraft.world.item.Item DARK_OAK_SIGN -> qi
    net.minecraft.world.item.Item MANGROVE_SIGN -> qj
    net.minecraft.world.item.Item BAMBOO_SIGN -> qk
    net.minecraft.world.item.Item CRIMSON_SIGN -> ql
    net.minecraft.world.item.Item WARPED_SIGN -> qm
    net.minecraft.world.item.Item OAK_HANGING_SIGN -> qn
    net.minecraft.world.item.Item SPRUCE_HANGING_SIGN -> qo
    net.minecraft.world.item.Item BIRCH_HANGING_SIGN -> qp
    net.minecraft.world.item.Item JUNGLE_HANGING_SIGN -> qq
    net.minecraft.world.item.Item ACACIA_HANGING_SIGN -> qr
    net.minecraft.world.item.Item CHERRY_HANGING_SIGN -> qs
    net.minecraft.world.item.Item DARK_OAK_HANGING_SIGN -> qt
    net.minecraft.world.item.Item MANGROVE_HANGING_SIGN -> qu
    net.minecraft.world.item.Item BAMBOO_HANGING_SIGN -> qv
    net.minecraft.world.item.Item CRIMSON_HANGING_SIGN -> qw
    net.minecraft.world.item.Item WARPED_HANGING_SIGN -> qx
    net.minecraft.world.item.Item BUCKET -> qy
    net.minecraft.world.item.Item WATER_BUCKET -> qz
    net.minecraft.world.item.Item LAVA_BUCKET -> qA
    net.minecraft.world.item.Item POWDER_SNOW_BUCKET -> qB
    net.minecraft.world.item.Item SNOWBALL -> qC
    net.minecraft.world.item.Item LEATHER -> qD
    net.minecraft.world.item.Item MILK_BUCKET -> qE
    net.minecraft.world.item.Item PUFFERFISH_BUCKET -> qF
    net.minecraft.world.item.Item SALMON_BUCKET -> qG
    net.minecraft.world.item.Item COD_BUCKET -> qH
    net.minecraft.world.item.Item TROPICAL_FISH_BUCKET -> qI
    net.minecraft.world.item.Item AXOLOTL_BUCKET -> qJ
    net.minecraft.world.item.Item TADPOLE_BUCKET -> qK
    net.minecraft.world.item.Item BRICK -> qL
    net.minecraft.world.item.Item CLAY_BALL -> qM
    net.minecraft.world.item.Item DRIED_KELP_BLOCK -> qN
    net.minecraft.world.item.Item PAPER -> qO
    net.minecraft.world.item.Item BOOK -> qP
    net.minecraft.world.item.Item SLIME_BALL -> qQ
    net.minecraft.world.item.Item EGG -> qR
    net.minecraft.world.item.Item COMPASS -> qS
    net.minecraft.world.item.Item RECOVERY_COMPASS -> qT
    net.minecraft.world.item.Item BUNDLE -> qU
    net.minecraft.world.item.Item FISHING_ROD -> qV
    net.minecraft.world.item.Item CLOCK -> qW
    net.minecraft.world.item.Item SPYGLASS -> qX
    net.minecraft.world.item.Item GLOWSTONE_DUST -> qY
    net.minecraft.world.item.Item COD -> qZ
    net.minecraft.world.item.Item SALMON -> ra
    net.minecraft.world.item.Item TROPICAL_FISH -> rb
    net.minecraft.world.item.Item PUFFERFISH -> rc
    net.minecraft.world.item.Item COOKED_COD -> rd
    net.minecraft.world.item.Item COOKED_SALMON -> re
    net.minecraft.world.item.Item INK_SAC -> rf
    net.minecraft.world.item.Item GLOW_INK_SAC -> rg
    net.minecraft.world.item.Item COCOA_BEANS -> rh
    net.minecraft.world.item.Item WHITE_DYE -> ri
    net.minecraft.world.item.Item ORANGE_DYE -> rj
    net.minecraft.world.item.Item MAGENTA_DYE -> rk
    net.minecraft.world.item.Item LIGHT_BLUE_DYE -> rl
    net.minecraft.world.item.Item YELLOW_DYE -> rm
    net.minecraft.world.item.Item LIME_DYE -> rn
    net.minecraft.world.item.Item PINK_DYE -> ro
    net.minecraft.world.item.Item GRAY_DYE -> rp
    net.minecraft.world.item.Item LIGHT_GRAY_DYE -> rq
    net.minecraft.world.item.Item CYAN_DYE -> rr
    net.minecraft.world.item.Item PURPLE_DYE -> rs
    net.minecraft.world.item.Item BLUE_DYE -> rt
    net.minecraft.world.item.Item BROWN_DYE -> ru
    net.minecraft.world.item.Item GREEN_DYE -> rv
    net.minecraft.world.item.Item RED_DYE -> rw
    net.minecraft.world.item.Item BLACK_DYE -> rx
    net.minecraft.world.item.Item BONE_MEAL -> ry
    net.minecraft.world.item.Item BONE -> rz
    net.minecraft.world.item.Item SUGAR -> rA
    net.minecraft.world.item.Item CAKE -> rB
    net.minecraft.world.item.Item WHITE_BED -> rC
    net.minecraft.world.item.Item ORANGE_BED -> rD
    net.minecraft.world.item.Item MAGENTA_BED -> rE
    net.minecraft.world.item.Item LIGHT_BLUE_BED -> rF
    net.minecraft.world.item.Item YELLOW_BED -> rG
    net.minecraft.world.item.Item LIME_BED -> rH
    net.minecraft.world.item.Item PINK_BED -> rI
    net.minecraft.world.item.Item GRAY_BED -> rJ
    net.minecraft.world.item.Item LIGHT_GRAY_BED -> rK
    net.minecraft.world.item.Item CYAN_BED -> rL
    net.minecraft.world.item.Item PURPLE_BED -> rM
    net.minecraft.world.item.Item BLUE_BED -> rN
    net.minecraft.world.item.Item BROWN_BED -> rO
    net.minecraft.world.item.Item GREEN_BED -> rP
    net.minecraft.world.item.Item RED_BED -> rQ
    net.minecraft.world.item.Item BLACK_BED -> rR
    net.minecraft.world.item.Item COOKIE -> rS
    net.minecraft.world.item.Item CRAFTER -> rT
    net.minecraft.world.item.Item FILLED_MAP -> rU
    net.minecraft.world.item.Item SHEARS -> rV
    net.minecraft.world.item.Item MELON_SLICE -> rW
    net.minecraft.world.item.Item DRIED_KELP -> rX
    net.minecraft.world.item.Item PUMPKIN_SEEDS -> rY
    net.minecraft.world.item.Item MELON_SEEDS -> rZ
    net.minecraft.world.item.Item BEEF -> sa
    net.minecraft.world.item.Item COOKED_BEEF -> sb
    net.minecraft.world.item.Item CHICKEN -> sc
    net.minecraft.world.item.Item COOKED_CHICKEN -> sd
    net.minecraft.world.item.Item ROTTEN_FLESH -> se
    net.minecraft.world.item.Item ENDER_PEARL -> sf
    net.minecraft.world.item.Item BLAZE_ROD -> sg
    net.minecraft.world.item.Item GHAST_TEAR -> sh
    net.minecraft.world.item.Item GOLD_NUGGET -> si
    net.minecraft.world.item.Item NETHER_WART -> sj
    net.minecraft.world.item.Item POTION -> sk
    net.minecraft.world.item.Item GLASS_BOTTLE -> sl
    net.minecraft.world.item.Item SPIDER_EYE -> sm
    net.minecraft.world.item.Item FERMENTED_SPIDER_EYE -> sn
    net.minecraft.world.item.Item BLAZE_POWDER -> so
    net.minecraft.world.item.Item MAGMA_CREAM -> sp
    net.minecraft.world.item.Item BREWING_STAND -> sq
    net.minecraft.world.item.Item CAULDRON -> sr
    net.minecraft.world.item.Item ENDER_EYE -> ss
    net.minecraft.world.item.Item GLISTERING_MELON_SLICE -> st
    net.minecraft.world.item.Item ARMADILLO_SPAWN_EGG -> su
    net.minecraft.world.item.Item ALLAY_SPAWN_EGG -> sv
    net.minecraft.world.item.Item AXOLOTL_SPAWN_EGG -> sw
    net.minecraft.world.item.Item BAT_SPAWN_EGG -> sx
    net.minecraft.world.item.Item BEE_SPAWN_EGG -> sy
    net.minecraft.world.item.Item BLAZE_SPAWN_EGG -> sz
    net.minecraft.world.item.Item BOGGED_SPAWN_EGG -> sA
    net.minecraft.world.item.Item BREEZE_SPAWN_EGG -> sB
    net.minecraft.world.item.Item CAT_SPAWN_EGG -> sC
    net.minecraft.world.item.Item CAMEL_SPAWN_EGG -> sD
    net.minecraft.world.item.Item CAVE_SPIDER_SPAWN_EGG -> sE
    net.minecraft.world.item.Item CHICKEN_SPAWN_EGG -> sF
    net.minecraft.world.item.Item COD_SPAWN_EGG -> sG
    net.minecraft.world.item.Item COW_SPAWN_EGG -> sH
    net.minecraft.world.item.Item CREEPER_SPAWN_EGG -> sI
    net.minecraft.world.item.Item DOLPHIN_SPAWN_EGG -> sJ
    net.minecraft.world.item.Item DONKEY_SPAWN_EGG -> sK
    net.minecraft.world.item.Item DROWNED_SPAWN_EGG -> sL
    net.minecraft.world.item.Item ELDER_GUARDIAN_SPAWN_EGG -> sM
    net.minecraft.world.item.Item ENDER_DRAGON_SPAWN_EGG -> sN
    net.minecraft.world.item.Item ENDERMAN_SPAWN_EGG -> sO
    net.minecraft.world.item.Item ENDERMITE_SPAWN_EGG -> sP
    net.minecraft.world.item.Item EVOKER_SPAWN_EGG -> sQ
    net.minecraft.world.item.Item FOX_SPAWN_EGG -> sR
    net.minecraft.world.item.Item FROG_SPAWN_EGG -> sS
    net.minecraft.world.item.Item GHAST_SPAWN_EGG -> sT
    net.minecraft.world.item.Item GLOW_SQUID_SPAWN_EGG -> sU
    net.minecraft.world.item.Item GOAT_SPAWN_EGG -> sV
    net.minecraft.world.item.Item GUARDIAN_SPAWN_EGG -> sW
    net.minecraft.world.item.Item HOGLIN_SPAWN_EGG -> sX
    net.minecraft.world.item.Item HORSE_SPAWN_EGG -> sY
    net.minecraft.world.item.Item HUSK_SPAWN_EGG -> sZ
    net.minecraft.world.item.Item IRON_GOLEM_SPAWN_EGG -> ta
    net.minecraft.world.item.Item LLAMA_SPAWN_EGG -> tb
    net.minecraft.world.item.Item MAGMA_CUBE_SPAWN_EGG -> tc
    net.minecraft.world.item.Item MOOSHROOM_SPAWN_EGG -> td
    net.minecraft.world.item.Item MULE_SPAWN_EGG -> te
    net.minecraft.world.item.Item OCELOT_SPAWN_EGG -> tf
    net.minecraft.world.item.Item PANDA_SPAWN_EGG -> tg
    net.minecraft.world.item.Item PARROT_SPAWN_EGG -> th
    net.minecraft.world.item.Item PHANTOM_SPAWN_EGG -> ti
    net.minecraft.world.item.Item PIG_SPAWN_EGG -> tj
    net.minecraft.world.item.Item PIGLIN_SPAWN_EGG -> tk
    net.minecraft.world.item.Item PIGLIN_BRUTE_SPAWN_EGG -> tl
    net.minecraft.world.item.Item PILLAGER_SPAWN_EGG -> tm
    net.minecraft.world.item.Item POLAR_BEAR_SPAWN_EGG -> tn
    net.minecraft.world.item.Item PUFFERFISH_SPAWN_EGG -> to
    net.minecraft.world.item.Item RABBIT_SPAWN_EGG -> tp
    net.minecraft.world.item.Item RAVAGER_SPAWN_EGG -> tq
    net.minecraft.world.item.Item SALMON_SPAWN_EGG -> tr
    net.minecraft.world.item.Item SHEEP_SPAWN_EGG -> ts
    net.minecraft.world.item.Item SHULKER_SPAWN_EGG -> tt
    net.minecraft.world.item.Item SILVERFISH_SPAWN_EGG -> tu
    net.minecraft.world.item.Item SKELETON_SPAWN_EGG -> tv
    net.minecraft.world.item.Item SKELETON_HORSE_SPAWN_EGG -> tw
    net.minecraft.world.item.Item SLIME_SPAWN_EGG -> tx
    net.minecraft.world.item.Item SNIFFER_SPAWN_EGG -> ty
    net.minecraft.world.item.Item SNOW_GOLEM_SPAWN_EGG -> tz
    net.minecraft.world.item.Item SPIDER_SPAWN_EGG -> tA
    net.minecraft.world.item.Item SQUID_SPAWN_EGG -> tB
    net.minecraft.world.item.Item STRAY_SPAWN_EGG -> tC
    net.minecraft.world.item.Item STRIDER_SPAWN_EGG -> tD
    net.minecraft.world.item.Item TADPOLE_SPAWN_EGG -> tE
    net.minecraft.world.item.Item TRADER_LLAMA_SPAWN_EGG -> tF
    net.minecraft.world.item.Item TROPICAL_FISH_SPAWN_EGG -> tG
    net.minecraft.world.item.Item TURTLE_SPAWN_EGG -> tH
    net.minecraft.world.item.Item VEX_SPAWN_EGG -> tI
    net.minecraft.world.item.Item VILLAGER_SPAWN_EGG -> tJ
    net.minecraft.world.item.Item VINDICATOR_SPAWN_EGG -> tK
    net.minecraft.world.item.Item WANDERING_TRADER_SPAWN_EGG -> tL
    net.minecraft.world.item.Item WARDEN_SPAWN_EGG -> tM
    net.minecraft.world.item.Item WITCH_SPAWN_EGG -> tN
    net.minecraft.world.item.Item WITHER_SPAWN_EGG -> tO
    net.minecraft.world.item.Item WITHER_SKELETON_SPAWN_EGG -> tP
    net.minecraft.world.item.Item WOLF_SPAWN_EGG -> tQ
    net.minecraft.world.item.Item ZOGLIN_SPAWN_EGG -> tR
    net.minecraft.world.item.Item ZOMBIE_SPAWN_EGG -> tS
    net.minecraft.world.item.Item ZOMBIE_HORSE_SPAWN_EGG -> tT
    net.minecraft.world.item.Item ZOMBIE_VILLAGER_SPAWN_EGG -> tU
    net.minecraft.world.item.Item ZOMBIFIED_PIGLIN_SPAWN_EGG -> tV
    net.minecraft.world.item.Item EXPERIENCE_BOTTLE -> tW
    net.minecraft.world.item.Item FIRE_CHARGE -> tX
    net.minecraft.world.item.Item WIND_CHARGE -> tY
    net.minecraft.world.item.Item WRITABLE_BOOK -> tZ
    net.minecraft.world.item.Item WRITTEN_BOOK -> ua
    net.minecraft.world.item.Item MACE -> ub
    net.minecraft.world.item.Item ITEM_FRAME -> uc
    net.minecraft.world.item.Item GLOW_ITEM_FRAME -> ud
    net.minecraft.world.item.Item FLOWER_POT -> ue
    net.minecraft.world.item.Item CARROT -> uf
    net.minecraft.world.item.Item POTATO -> ug
    net.minecraft.world.item.Item BAKED_POTATO -> uh
    net.minecraft.world.item.Item POISONOUS_POTATO -> ui
    net.minecraft.world.item.Item MAP -> uj
    net.minecraft.world.item.Item GOLDEN_CARROT -> uk
    net.minecraft.world.item.Item SKELETON_SKULL -> ul
    net.minecraft.world.item.Item WITHER_SKELETON_SKULL -> um
    net.minecraft.world.item.Item PLAYER_HEAD -> un
    net.minecraft.world.item.Item ZOMBIE_HEAD -> uo
    net.minecraft.world.item.Item CREEPER_HEAD -> up
    net.minecraft.world.item.Item DRAGON_HEAD -> uq
    net.minecraft.world.item.Item PIGLIN_HEAD -> ur
    net.minecraft.world.item.Item NETHER_STAR -> us
    net.minecraft.world.item.Item PUMPKIN_PIE -> ut
    net.minecraft.world.item.Item FIREWORK_ROCKET -> uu
    net.minecraft.world.item.Item FIREWORK_STAR -> uv
    net.minecraft.world.item.Item ENCHANTED_BOOK -> uw
    net.minecraft.world.item.Item NETHER_BRICK -> ux
    net.minecraft.world.item.Item PRISMARINE_SHARD -> uy
    net.minecraft.world.item.Item PRISMARINE_CRYSTALS -> uz
    net.minecraft.world.item.Item RABBIT -> uA
    net.minecraft.world.item.Item COOKED_RABBIT -> uB
    net.minecraft.world.item.Item RABBIT_STEW -> uC
    net.minecraft.world.item.Item RABBIT_FOOT -> uD
    net.minecraft.world.item.Item RABBIT_HIDE -> uE
    net.minecraft.world.item.Item ARMOR_STAND -> uF
    net.minecraft.world.item.Item IRON_HORSE_ARMOR -> uG
    net.minecraft.world.item.Item GOLDEN_HORSE_ARMOR -> uH
    net.minecraft.world.item.Item DIAMOND_HORSE_ARMOR -> uI
    net.minecraft.world.item.Item LEATHER_HORSE_ARMOR -> uJ
    net.minecraft.world.item.Item LEAD -> uK
    net.minecraft.world.item.Item NAME_TAG -> uL
    net.minecraft.world.item.Item COMMAND_BLOCK_MINECART -> uM
    net.minecraft.world.item.Item MUTTON -> uN
    net.minecraft.world.item.Item COOKED_MUTTON -> uO
    net.minecraft.world.item.Item WHITE_BANNER -> uP
    net.minecraft.world.item.Item ORANGE_BANNER -> uQ
    net.minecraft.world.item.Item MAGENTA_BANNER -> uR
    net.minecraft.world.item.Item LIGHT_BLUE_BANNER -> uS
    net.minecraft.world.item.Item YELLOW_BANNER -> uT
    net.minecraft.world.item.Item LIME_BANNER -> uU
    net.minecraft.world.item.Item PINK_BANNER -> uV
    net.minecraft.world.item.Item GRAY_BANNER -> uW
    net.minecraft.world.item.Item LIGHT_GRAY_BANNER -> uX
    net.minecraft.world.item.Item CYAN_BANNER -> uY
    net.minecraft.world.item.Item PURPLE_BANNER -> uZ
    net.minecraft.world.item.Item BLUE_BANNER -> va
    net.minecraft.world.item.Item BROWN_BANNER -> vb
    net.minecraft.world.item.Item GREEN_BANNER -> vc
    net.minecraft.world.item.Item RED_BANNER -> vd
    net.minecraft.world.item.Item BLACK_BANNER -> ve
    net.minecraft.world.item.Item END_CRYSTAL -> vf
    net.minecraft.world.item.Item CHORUS_FRUIT -> vg
    net.minecraft.world.item.Item POPPED_CHORUS_FRUIT -> vh
    net.minecraft.world.item.Item TORCHFLOWER_SEEDS -> vi
    net.minecraft.world.item.Item PITCHER_POD -> vj
    net.minecraft.world.item.Item BEETROOT -> vk
    net.minecraft.world.item.Item BEETROOT_SEEDS -> vl
    net.minecraft.world.item.Item BEETROOT_SOUP -> vm
    net.minecraft.world.item.Item DRAGON_BREATH -> vn
    net.minecraft.world.item.Item SPLASH_POTION -> vo
    net.minecraft.world.item.Item SPECTRAL_ARROW -> vp
    net.minecraft.world.item.Item TIPPED_ARROW -> vq
    net.minecraft.world.item.Item LINGERING_POTION -> vr
    net.minecraft.world.item.Item SHIELD -> vs
    net.minecraft.world.item.Item TOTEM_OF_UNDYING -> vt
    net.minecraft.world.item.Item SHULKER_SHELL -> vu
    net.minecraft.world.item.Item IRON_NUGGET -> vv
    net.minecraft.world.item.Item KNOWLEDGE_BOOK -> vw
    net.minecraft.world.item.Item DEBUG_STICK -> vx
    net.minecraft.world.item.Item MUSIC_DISC_13 -> vy
    net.minecraft.world.item.Item MUSIC_DISC_CAT -> vz
    net.minecraft.world.item.Item MUSIC_DISC_BLOCKS -> vA
    net.minecraft.world.item.Item MUSIC_DISC_CHIRP -> vB
    net.minecraft.world.item.Item MUSIC_DISC_CREATOR -> vC
    net.minecraft.world.item.Item MUSIC_DISC_CREATOR_MUSIC_BOX -> vD
    net.minecraft.world.item.Item MUSIC_DISC_FAR -> vE
    net.minecraft.world.item.Item MUSIC_DISC_MALL -> vF
    net.minecraft.world.item.Item MUSIC_DISC_MELLOHI -> vG
    net.minecraft.world.item.Item MUSIC_DISC_STAL -> vH
    net.minecraft.world.item.Item MUSIC_DISC_STRAD -> vI
    net.minecraft.world.item.Item MUSIC_DISC_WARD -> vJ
    net.minecraft.world.item.Item MUSIC_DISC_11 -> vK
    net.minecraft.world.item.Item MUSIC_DISC_WAIT -> vL
    net.minecraft.world.item.Item MUSIC_DISC_OTHERSIDE -> vM
    net.minecraft.world.item.Item MUSIC_DISC_RELIC -> vN
    net.minecraft.world.item.Item MUSIC_DISC_5 -> vO
    net.minecraft.world.item.Item MUSIC_DISC_PIGSTEP -> vP
    net.minecraft.world.item.Item MUSIC_DISC_PRECIPICE -> vQ
    net.minecraft.world.item.Item DISC_FRAGMENT_5 -> vR
    net.minecraft.world.item.Item TRIDENT -> vS
    net.minecraft.world.item.Item PHANTOM_MEMBRANE -> vT
    net.minecraft.world.item.Item NAUTILUS_SHELL -> vU
    net.minecraft.world.item.Item HEART_OF_THE_SEA -> vV
    net.minecraft.world.item.Item CROSSBOW -> vW
    net.minecraft.world.item.Item SUSPICIOUS_STEW -> vX
    net.minecraft.world.item.Item LOOM -> vY
    net.minecraft.world.item.Item FLOWER_BANNER_PATTERN -> vZ
    net.minecraft.world.item.Item CREEPER_BANNER_PATTERN -> wa
    net.minecraft.world.item.Item SKULL_BANNER_PATTERN -> wb
    net.minecraft.world.item.Item MOJANG_BANNER_PATTERN -> wc
    net.minecraft.world.item.Item GLOBE_BANNER_PATTERN -> wd
    net.minecraft.world.item.Item PIGLIN_BANNER_PATTERN -> we
    net.minecraft.world.item.Item FLOW_BANNER_PATTERN -> wf
    net.minecraft.world.item.Item GUSTER_BANNER_PATTERN -> wg
    net.minecraft.world.item.Item GOAT_HORN -> wh
    net.minecraft.world.item.Item COMPOSTER -> wi
    net.minecraft.world.item.Item BARREL -> wj
    net.minecraft.world.item.Item SMOKER -> wk
    net.minecraft.world.item.Item BLAST_FURNACE -> wl
    net.minecraft.world.item.Item CARTOGRAPHY_TABLE -> wm
    net.minecraft.world.item.Item FLETCHING_TABLE -> wn
    net.minecraft.world.item.Item GRINDSTONE -> wo
    net.minecraft.world.item.Item SMITHING_TABLE -> wp
    net.minecraft.world.item.Item STONECUTTER -> wq
    net.minecraft.world.item.Item BELL -> wr
    net.minecraft.world.item.Item LANTERN -> ws
    net.minecraft.world.item.Item SOUL_LANTERN -> wt
    net.minecraft.world.item.Item SWEET_BERRIES -> wu
    net.minecraft.world.item.Item GLOW_BERRIES -> wv
    net.minecraft.world.item.Item CAMPFIRE -> ww
    net.minecraft.world.item.Item SOUL_CAMPFIRE -> wx
    net.minecraft.world.item.Item SHROOMLIGHT -> wy
    net.minecraft.world.item.Item HONEYCOMB -> wz
    net.minecraft.world.item.Item BEE_NEST -> wA
    net.minecraft.world.item.Item BEEHIVE -> wB
    net.minecraft.world.item.Item HONEY_BOTTLE -> wC
    net.minecraft.world.item.Item HONEYCOMB_BLOCK -> wD
    net.minecraft.world.item.Item LODESTONE -> wE
    net.minecraft.world.item.Item CRYING_OBSIDIAN -> wF
    net.minecraft.world.item.Item BLACKSTONE -> wG
    net.minecraft.world.item.Item BLACKSTONE_SLAB -> wH
    net.minecraft.world.item.Item BLACKSTONE_STAIRS -> wI
    net.minecraft.world.item.Item GILDED_BLACKSTONE -> wJ
    net.minecraft.world.item.Item POLISHED_BLACKSTONE -> wK
    net.minecraft.world.item.Item POLISHED_BLACKSTONE_SLAB -> wL
    net.minecraft.world.item.Item POLISHED_BLACKSTONE_STAIRS -> wM
    net.minecraft.world.item.Item CHISELED_POLISHED_BLACKSTONE -> wN
    net.minecraft.world.item.Item POLISHED_BLACKSTONE_BRICKS -> wO
    net.minecraft.world.item.Item POLISHED_BLACKSTONE_BRICK_SLAB -> wP
    net.minecraft.world.item.Item POLISHED_BLACKSTONE_BRICK_STAIRS -> wQ
    net.minecraft.world.item.Item CRACKED_POLISHED_BLACKSTONE_BRICKS -> wR
    net.minecraft.world.item.Item RESPAWN_ANCHOR -> wS
    net.minecraft.world.item.Item CANDLE -> wT
    net.minecraft.world.item.Item WHITE_CANDLE -> wU
    net.minecraft.world.item.Item ORANGE_CANDLE -> wV
    net.minecraft.world.item.Item MAGENTA_CANDLE -> wW
    net.minecraft.world.item.Item LIGHT_BLUE_CANDLE -> wX
    net.minecraft.world.item.Item YELLOW_CANDLE -> wY
    net.minecraft.world.item.Item LIME_CANDLE -> wZ
    net.minecraft.world.item.Item PINK_CANDLE -> xa
    net.minecraft.world.item.Item GRAY_CANDLE -> xb
    net.minecraft.world.item.Item LIGHT_GRAY_CANDLE -> xc
    net.minecraft.world.item.Item CYAN_CANDLE -> xd
    net.minecraft.world.item.Item PURPLE_CANDLE -> xe
    net.minecraft.world.item.Item BLUE_CANDLE -> xf
    net.minecraft.world.item.Item BROWN_CANDLE -> xg
    net.minecraft.world.item.Item GREEN_CANDLE -> xh
    net.minecraft.world.item.Item RED_CANDLE -> xi
    net.minecraft.world.item.Item BLACK_CANDLE -> xj
    net.minecraft.world.item.Item SMALL_AMETHYST_BUD -> xk
    net.minecraft.world.item.Item MEDIUM_AMETHYST_BUD -> xl
    net.minecraft.world.item.Item LARGE_AMETHYST_BUD -> xm
    net.minecraft.world.item.Item AMETHYST_CLUSTER -> xn
    net.minecraft.world.item.Item POINTED_DRIPSTONE -> xo
    net.minecraft.world.item.Item OCHRE_FROGLIGHT -> xp
    net.minecraft.world.item.Item VERDANT_FROGLIGHT -> xq
    net.minecraft.world.item.Item PEARLESCENT_FROGLIGHT -> xr
    net.minecraft.world.item.Item FROGSPAWN -> xs
    net.minecraft.world.item.Item ECHO_SHARD -> xt
    net.minecraft.world.item.Item BRUSH -> xu
    net.minecraft.world.item.Item NETHERITE_UPGRADE_SMITHING_TEMPLATE -> xv
    net.minecraft.world.item.Item SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE -> xw
    net.minecraft.world.item.Item DUNE_ARMOR_TRIM_SMITHING_TEMPLATE -> xx
    net.minecraft.world.item.Item COAST_ARMOR_TRIM_SMITHING_TEMPLATE -> xy
    net.minecraft.world.item.Item WILD_ARMOR_TRIM_SMITHING_TEMPLATE -> xz
    net.minecraft.world.item.Item WARD_ARMOR_TRIM_SMITHING_TEMPLATE -> xA
    net.minecraft.world.item.Item EYE_ARMOR_TRIM_SMITHING_TEMPLATE -> xB
    net.minecraft.world.item.Item VEX_ARMOR_TRIM_SMITHING_TEMPLATE -> xC
    net.minecraft.world.item.Item TIDE_ARMOR_TRIM_SMITHING_TEMPLATE -> xD
    net.minecraft.world.item.Item SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE -> xE
    net.minecraft.world.item.Item RIB_ARMOR_TRIM_SMITHING_TEMPLATE -> xF
    net.minecraft.world.item.Item SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE -> xG
    net.minecraft.world.item.Item WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE -> xH
    net.minecraft.world.item.Item SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE -> xI
    net.minecraft.world.item.Item SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE -> xJ
    net.minecraft.world.item.Item RAISER_ARMOR_TRIM_SMITHING_TEMPLATE -> xK
    net.minecraft.world.item.Item HOST_ARMOR_TRIM_SMITHING_TEMPLATE -> xL
    net.minecraft.world.item.Item FLOW_ARMOR_TRIM_SMITHING_TEMPLATE -> xM
    net.minecraft.world.item.Item BOLT_ARMOR_TRIM_SMITHING_TEMPLATE -> xN
    net.minecraft.world.item.Item ANGLER_POTTERY_SHERD -> xO
    net.minecraft.world.item.Item ARCHER_POTTERY_SHERD -> xP
    net.minecraft.world.item.Item ARMS_UP_POTTERY_SHERD -> xQ
    net.minecraft.world.item.Item BLADE_POTTERY_SHERD -> xR
    net.minecraft.world.item.Item BREWER_POTTERY_SHERD -> xS
    net.minecraft.world.item.Item BURN_POTTERY_SHERD -> xT
    net.minecraft.world.item.Item DANGER_POTTERY_SHERD -> xU
    net.minecraft.world.item.Item EXPLORER_POTTERY_SHERD -> xV
    net.minecraft.world.item.Item FLOW_POTTERY_SHERD -> xW
    net.minecraft.world.item.Item FRIEND_POTTERY_SHERD -> xX
    net.minecraft.world.item.Item GUSTER_POTTERY_SHERD -> xY
    net.minecraft.world.item.Item HEART_POTTERY_SHERD -> xZ
    net.minecraft.world.item.Item HEARTBREAK_POTTERY_SHERD -> ya
    net.minecraft.world.item.Item HOWL_POTTERY_SHERD -> yb
    net.minecraft.world.item.Item MINER_POTTERY_SHERD -> yc
    net.minecraft.world.item.Item MOURNER_POTTERY_SHERD -> yd
    net.minecraft.world.item.Item PLENTY_POTTERY_SHERD -> ye
    net.minecraft.world.item.Item PRIZE_POTTERY_SHERD -> yf
    net.minecraft.world.item.Item SCRAPE_POTTERY_SHERD -> yg
    net.minecraft.world.item.Item SHEAF_POTTERY_SHERD -> yh
    net.minecraft.world.item.Item SHELTER_POTTERY_SHERD -> yi
    net.minecraft.world.item.Item SKULL_POTTERY_SHERD -> yj
    net.minecraft.world.item.Item SNORT_POTTERY_SHERD -> yk
    net.minecraft.world.item.Item COPPER_GRATE -> yl
    net.minecraft.world.item.Item EXPOSED_COPPER_GRATE -> ym
    net.minecraft.world.item.Item WEATHERED_COPPER_GRATE -> yn
    net.minecraft.world.item.Item OXIDIZED_COPPER_GRATE -> yo
    net.minecraft.world.item.Item WAXED_COPPER_GRATE -> yp
    net.minecraft.world.item.Item WAXED_EXPOSED_COPPER_GRATE -> yq
    net.minecraft.world.item.Item WAXED_WEATHERED_COPPER_GRATE -> yr
    net.minecraft.world.item.Item WAXED_OXIDIZED_COPPER_GRATE -> ys
    net.minecraft.world.item.Item COPPER_BULB -> yt
    net.minecraft.world.item.Item EXPOSED_COPPER_BULB -> yu
    net.minecraft.world.item.Item WEATHERED_COPPER_BULB -> yv
    net.minecraft.world.item.Item OXIDIZED_COPPER_BULB -> yw
    net.minecraft.world.item.Item WAXED_COPPER_BULB -> yx
    net.minecraft.world.item.Item WAXED_EXPOSED_COPPER_BULB -> yy
    net.minecraft.world.item.Item WAXED_WEATHERED_COPPER_BULB -> yz
    net.minecraft.world.item.Item WAXED_OXIDIZED_COPPER_BULB -> yA
    net.minecraft.world.item.Item TRIAL_SPAWNER -> yB
    net.minecraft.world.item.Item TRIAL_KEY -> yC
    net.minecraft.world.item.Item OMINOUS_TRIAL_KEY -> yD
    net.minecraft.world.item.Item VAULT -> yE
    net.minecraft.world.item.Item OMINOUS_BOTTLE -> yF
    net.minecraft.world.item.Item BREEZE_ROD -> yG
    41:41:void <init>() -> <init>
    1436:1436:net.minecraft.world.item.Item registerBlock(net.minecraft.world.level.block.Block) -> a
    1440:1440:net.minecraft.world.item.Item registerBlock(net.minecraft.world.level.block.Block,java.util.function.UnaryOperator) -> a
    1445:1450:net.minecraft.world.item.Item registerBlock(net.minecraft.world.level.block.Block,net.minecraft.world.level.block.Block[]) -> a
    1458:1458:net.minecraft.world.item.Item registerBlock(net.minecraft.world.level.block.Block,net.minecraft.world.item.Item) -> a
    1470:1473:net.minecraft.world.item.Item registerItem(net.minecraft.resources.ResourceKey,net.minecraft.world.item.Item) -> a
    1306:1306:net.minecraft.world.item.Item$Properties lambda$static$14(net.minecraft.world.item.Item$Properties) -> a
    1305:1305:net.minecraft.world.item.Item$Properties lambda$static$13(net.minecraft.world.item.Item$Properties) -> b
    1294:1294:net.minecraft.world.item.Item$Properties lambda$static$12(net.minecraft.world.item.Item$Properties) -> c
    1293:1293:net.minecraft.world.item.Item$Properties lambda$static$11(net.minecraft.world.item.Item$Properties) -> d
    1292:1292:net.minecraft.world.item.Item$Properties lambda$static$10(net.minecraft.world.item.Item$Properties) -> e
    1088:1088:net.minecraft.world.item.Item$Properties lambda$static$9(net.minecraft.world.item.Item$Properties) -> f
    1065:1065:net.minecraft.world.item.Item$Properties lambda$static$8(net.minecraft.world.item.Item$Properties) -> g
    742:742:net.minecraft.world.item.Item$Properties lambda$static$7(net.minecraft.world.item.Item$Properties) -> h
    731:731:net.minecraft.world.item.Item$Properties lambda$static$6(net.minecraft.world.item.Item$Properties) -> i
    730:730:net.minecraft.world.item.Item$Properties lambda$static$5(net.minecraft.world.item.Item$Properties) -> j
    729:729:net.minecraft.world.item.Item$Properties lambda$static$4(net.minecraft.world.item.Item$Properties) -> k
    433:433:net.minecraft.world.item.Item$Properties lambda$static$3(net.minecraft.world.item.Item$Properties) -> l
    352:352:net.minecraft.world.item.Item$Properties lambda$static$2(net.minecraft.world.item.Item$Properties) -> m
    349:349:net.minecraft.world.item.Item$Properties lambda$static$1(net.minecraft.world.item.Item$Properties) -> n
    337:337:net.minecraft.world.item.Item$Properties lambda$static$0(net.minecraft.world.item.Item$Properties) -> o
    43:1428:void <clinit>() -> <clinit>

 */
class Items(around: Any) : MimickedClass(around) {
	companion object {
		val clazz: Class<*> = loadClass(
			net_minecraft_world_item_Items
		)

		fun registerBlock(blockItem: BlockItem): Item = Item(
			clazz.getMethod("a", BlockItem.clazz).invoke(null, blockItem.around)
		)

		fun registerItem(name: String, item: Item): Item = Item(
			clazz.getMethod("a", String::class.java, Item.clazz)
				.invoke(null, name, item.around)
		)

		fun registerItem(id: ResourceLocation, item: Item): Item = Item(
			clazz.getMethod("a", ResourceLocation.clazz, Item.clazz)
				.invoke(null, id.around, item.around)
		)

		val AIR: Item
			get() = Item(clazz.getField("a").get(null))
		val GRASS_BLOCK: Item
			get() = Item(clazz.getField("B").get(null))
	}
}