package org.bread_experts_group.eam.minecraft.feature.v1x21x1

const val net_minecraft_resources_ResourceLocation: String = "akr"
const val net_minecraft_core_registries_Registry: String = "jz"
const val net_minecraft_core_DefaultedRegistry: String = "jh"
const val net_minecraft_core_registries_BuiltInRegistries: String = "lt"
const val net_minecraft_core_registries_BuiltInRegistries_createContents: String = "b"
const val net_minecraft_world_level_block_Block: String = "dfy"
const val net_minecraft_world_level_block_state_BlockBehaviour: String = "dtb"
const val net_minecraft_world_level_block_state_BlockBehaviour_Properties: String = $$"dtb$d"
const val net_minecraft_world_level_block_Blocks: String = "dga"
const val net_minecraft_world_level_Level: String = "dcw"
const val net_minecraft_world_entity_Entity: String = "bsr"
const val net_minecraft_core_IdMapper: String = "js"
const val net_minecraft_world_level_block_state_BlockState: String = "dtc"
const val net_minecraft_world_level_block_state_StateDefinition: String = "dtd"
const val net_minecraft_world_item_Item_Properties: String = $$"cul$a"
const val net_minecraft_world_item_Item: String = "cul"
const val net_minecraft_world_item_Item_inventoryTick: String = "a"
const val net_minecraft_world_item_BlockItem: String = "cso"
const val net_minecraft_world_item_Items: String = "cut"
const val net_minecraft_world_item_ItemStack: String = "cuq"
const val net_minecraft_world_food_FoodProperties: String = "cpr"
const val net_minecraft_world_food_FoodProperties_Builder: String = $$"cpr$a"
const val net_minecraft_client_gui_screens_TitleScreen: String = "fof"
const val net_minecraft_client_gui_screens_TitleScreen_render: String = "a"
const val net_minecraft_client_gui_GuiGraphics: String = "fhz"

//const val net_minecraft_client_gui_GuiGraphics_ScissorStack: String = $$"fhz$a"
const val net_minecraft_client_gui_Font: String = "fhx"
const val net_minecraft_client_Minecraft: String = "fgo"
const val net_minecraft_client_Minecraft_updateTitle: String = "d"
const val com_mojang_blaze3d_vertex_PoseStack: String = "fbi"
const val com_mojang_blaze3d_vertex_PoseStack_Pose: String = $$"fbi$a"
const val com_mojang_blaze3d_platform_Window: String = "fam"
const val com_mojang_math_Axis: String = "a"