package org.bread_experts_group.eam.minecraft.version_impl.v1x21x1.net.minecraft.world.entity

import org.bread_experts_group.eam.classDesc
import org.bread_experts_group.eam.loadClass
import org.bread_experts_group.eam.minecraft.ClassInfo
import org.bread_experts_group.eam.minecraft.version_impl.v1x21x1.net.minecraft.world.item.Item
import org.bread_experts_group.eam.minecraft.version_impl.v1x21x1.net_minecraft_world_entity_LivingEntity
import java.lang.constant.ClassDesc

/*

net.minecraft.world.entity.LivingEntity -> btn:
# {"fileName":"LivingEntity.java","id":"sourceFile"}
    org.slf4j.Logger LOGGER -> b
    java.lang.String TAG_ACTIVE_EFFECTS -> c
    net.minecraft.resources.ResourceLocation SPEED_MODIFIER_POWDER_SNOW_ID -> d
    net.minecraft.resources.ResourceLocation SPRINTING_MODIFIER_ID -> e
    net.minecraft.world.entity.ai.attributes.AttributeModifier SPEED_MODIFIER_SPRINTING -> bH
    int HAND_SLOTS -> i
    int ARMOR_SLOTS -> j
    int EQUIPMENT_SLOT_OFFSET -> k
    int ARMOR_SLOT_OFFSET -> l
    int BODY_ARMOR_OFFSET -> m
    int SWING_DURATION -> n
    int PLAYER_HURT_EXPERIENCE_TIME -> o
    int DAMAGE_SOURCE_TIMEOUT -> bI
    double MIN_MOVEMENT_DISTANCE -> p
    double DEFAULT_BASE_GRAVITY -> q
    int DEATH_DURATION -> r
    int TICKS_PER_ELYTRA_FREE_FALL_EVENT -> bJ
    int FREE_FALL_EVENTS_PER_ELYTRA_BREAK -> bK
    int USE_ITEM_INTERVAL -> s
    float BASE_JUMP_POWER -> t
    double MAX_LINE_OF_SIGHT_TEST_RANGE -> bL
    int LIVING_ENTITY_FLAG_IS_USING -> u
    int LIVING_ENTITY_FLAG_OFF_HAND -> v
    int LIVING_ENTITY_FLAG_SPIN_ATTACK -> aD
    net.minecraft.network.syncher.EntityDataAccessor DATA_LIVING_ENTITY_FLAGS -> aE
    net.minecraft.network.syncher.EntityDataAccessor DATA_HEALTH_ID -> bM
    net.minecraft.network.syncher.EntityDataAccessor DATA_EFFECT_PARTICLES -> bN
    net.minecraft.network.syncher.EntityDataAccessor DATA_EFFECT_AMBIENCE_ID -> bO
    net.minecraft.network.syncher.EntityDataAccessor DATA_ARROW_COUNT_ID -> bP
    net.minecraft.network.syncher.EntityDataAccessor DATA_STINGER_COUNT_ID -> bQ
    net.minecraft.network.syncher.EntityDataAccessor SLEEPING_POS_ID -> bR
    int PARTICLE_FREQUENCY_WHEN_INVISIBLE -> bS
    net.minecraft.world.entity.EntityDimensions SLEEPING_DIMENSIONS -> aF
    float EXTRA_RENDER_CULLING_SIZE_WITH_BIG_HAT -> aG
    float DEFAULT_BABY_SCALE -> aH
    float ITEM_USE_EFFECT_START_FRACTION -> bT
    java.lang.String ATTRIBUTES_FIELD -> aI
    net.minecraft.world.entity.ai.attributes.AttributeMap attributes -> bU
    net.minecraft.world.damagesource.CombatTracker combatTracker -> bV
    java.util.Map activeEffects -> bW
    net.minecraft.core.NonNullList lastHandItemStacks -> bX
    net.minecraft.core.NonNullList lastArmorItemStacks -> bY
    net.minecraft.world.item.ItemStack lastBodyItemStack -> bZ
    boolean swinging -> aJ
    boolean discardFriction -> ca
    net.minecraft.world.InteractionHand swingingArm -> aK
    int swingTime -> aL
    int removeArrowTime -> aM
    int removeStingerTime -> aN
    int hurtTime -> aO
    int hurtDuration -> aP
    int deathTime -> aQ
    float oAttackAnim -> aR
    float attackAnim -> aS
    int attackStrengthTicker -> aT
    net.minecraft.world.entity.WalkAnimationState walkAnimation -> aU
    int invulnerableDuration -> aV
    float timeOffs -> aW
    float rotA -> aX
    float yBodyRot -> aY
    float yBodyRotO -> aZ
    float yHeadRot -> ba
    float yHeadRotO -> bb
    net.minecraft.world.entity.player.Player lastHurtByPlayer -> bc
    int lastHurtByPlayerTime -> bd
    boolean dead -> be
    int noActionTime -> bf
    float oRun -> bg
    float run -> bh
    float animStep -> bi
    float animStepO -> bj
    float rotOffs -> bk
    int deathScore -> bl
    float lastHurt -> bm
    boolean jumping -> bn
    float xxa -> bo
    float yya -> bp
    float zza -> bq
    int lerpSteps -> br
    double lerpX -> bs
    double lerpY -> bt
    double lerpZ -> bu
    double lerpYRot -> bv
    double lerpXRot -> bw
    double lerpYHeadRot -> bx
    int lerpHeadSteps -> by
    boolean effectsDirty -> cb
    net.minecraft.world.entity.LivingEntity lastHurtByMob -> cc
    int lastHurtByMobTimestamp -> cd
    net.minecraft.world.entity.LivingEntity lastHurtMob -> ce
    int lastHurtMobTimestamp -> cf
    float speed -> cg
    int noJumpDelay -> ch
    float absorptionAmount -> ci
    net.minecraft.world.item.ItemStack useItem -> bz
    int useItemRemaining -> bA
    int fallFlyTicks -> bB
    net.minecraft.core.BlockPos lastPos -> cj
    java.util.Optional lastClimbablePos -> ck
    net.minecraft.world.damagesource.DamageSource lastDamageSource -> cl
    long lastDamageStamp -> cm
    int autoSpinAttackTicks -> bC
    float autoSpinAttackDmg -> bD
    net.minecraft.world.item.ItemStack autoSpinAttackItemStack -> bE
    float swimAmount -> cn
    float swimAmountO -> co
    net.minecraft.world.entity.ai.Brain brain -> bF
    boolean skipDropExperience -> cp
    it.unimi.dsi.fastutil.objects.Reference2ObjectMap activeLocationDependentEnchantments -> cq
    float appliedScale -> bG
    187:284:void <init>(net.minecraft.world.entity.EntityType,net.minecraft.world.level.Level) -> <init>
    287:287:net.minecraft.world.entity.ai.Brain getBrain() -> dT
    291:291:net.minecraft.world.entity.ai.Brain$Provider brainProvider() -> dU
    295:295:net.minecraft.world.entity.ai.Brain makeBrain(com.mojang.serialization.Dynamic) -> a
    300:301:void kill() -> ap
    304:304:boolean canAttackType(net.minecraft.world.entity.EntityType) -> a
    309:316:void defineSynchedData(net.minecraft.network.syncher.SynchedEntityData$Builder) -> a
    319:337:net.minecraft.world.entity.ai.attributes.AttributeSupplier$Builder createLivingAttributes() -> dV
    342:379:void checkFallDamage(double,boolean,net.minecraft.world.level.block.state.BlockState,net.minecraft.core.BlockPos) -> a
    382:382:boolean canBreatheUnderwater() -> dW
    386:386:float getSwimAmount(float) -> a
    390:390:boolean hasLandedInLiquid() -> dX
    395:506:void baseTick() -> aw
    510:510:float getBlockSpeedFactor() -> aO
    514:523:void removeFrost() -> dY
    526:539:void tryAddFrost() -> dZ
    542:543:void onChangedBlock(net.minecraft.server.level.ServerLevel,net.minecraft.core.BlockPos) -> b
    546:546:boolean isBaby() -> o_
    550:550:float getAgeScale() -> ea
    554:559:float getScale() -> eb
    563:563:float sanitizeScale(float) -> b
    567:567:boolean isAffectedByFluids() -> ec
    571:576:void tickDeath() -> ed
    579:579:boolean shouldDropExperience() -> ee
    583:583:boolean shouldDropLoot() -> ef
    587:600:int decreaseAirSupply(int) -> m
    604:604:int increaseAirSupply(int) -> n
    608:608:int getExperienceReward(net.minecraft.server.level.ServerLevel,net.minecraft.world.entity.Entity) -> a
    612:612:int getBaseExperienceReward() -> eg
    616:616:boolean isAlwaysExperienceDropper() -> eh
    621:621:net.minecraft.world.entity.LivingEntity getLastHurtByMob() -> ei
    626:626:net.minecraft.world.entity.LivingEntity getLastAttacker() -> Y_
    630:630:int getLastHurtByMobTimestamp() -> ej
    634:636:void setLastHurtByPlayer(net.minecraft.world.entity.player.Player) -> c
    639:641:void setLastHurtByMob(net.minecraft.world.entity.LivingEntity) -> a
    645:645:net.minecraft.world.entity.LivingEntity getLastHurtMob() -> ek
    649:649:int getLastHurtMobTimestamp() -> el
    653:659:void setLastHurtMob(net.minecraft.world.entity.Entity) -> A
    662:662:int getNoActionTime() -> em
    666:667:void setNoActionTime(int) -> o
    670:670:boolean shouldDiscardFriction() -> en
    674:675:void setDiscardFriction(boolean) -> r
    678:678:boolean doesEmitEquipEvent(net.minecraft.world.entity.EquipmentSlot) -> b
    682:696:void onEquipItem(net.minecraft.world.entity.EquipmentSlot,net.minecraft.world.item.ItemStack,net.minecraft.world.item.ItemStack) -> a
    700:706:void remove(net.minecraft.world.entity.Entity$RemovalReason) -> a
    709:713:void triggerOnDeathMobEffects(net.minecraft.world.entity.Entity$RemovalReason) -> c
    717:744:void addAdditionalSaveData(net.minecraft.nbt.CompoundTag) -> b
    748:805:void readAdditionalSaveData(net.minecraft.nbt.CompoundTag) -> a
    808:848:void tickEffects() -> eo
    851:860:void updateInvisibilityStatus() -> K
    863:870:void updateSynchronizedMobEffectParticles() -> s
    873:877:void updateGlowingStatus() -> v
    880:906:double getVisibilityPercent(net.minecraft.world.entity.Entity) -> B
    910:913:boolean canAttack(net.minecraft.world.entity.LivingEntity) -> c
    917:917:boolean canAttack(net.minecraft.world.entity.LivingEntity,net.minecraft.world.entity.ai.targeting.TargetingConditions) -> a
    922:922:boolean canBeSeenAsEnemy() -> ep
    926:926:boolean canBeSeenByAnyone() -> eq
    930:936:boolean areAllEffectsAmbient(java.util.Collection) -> c
    940:941:void removeEffectParticles() -> er
    944:955:boolean removeAllEffects() -> es
    959:959:java.util.Collection getActiveEffects() -> et
    963:963:java.util.Map getActiveEffectsMap() -> eu
    967:967:boolean hasEffect(net.minecraft.core.Holder) -> b
    972:972:net.minecraft.world.effect.MobEffectInstance getEffect(net.minecraft.core.Holder) -> c
    976:976:boolean addEffect(net.minecraft.world.effect.MobEffectInstance) -> b
    980:1000:boolean addEffect(net.minecraft.world.effect.MobEffectInstance,net.minecraft.world.entity.Entity) -> b
    1004:1013:boolean canBeAffected(net.minecraft.world.effect.MobEffectInstance) -> c
    1017:1028:void forceAddEffect(net.minecraft.world.effect.MobEffectInstance,net.minecraft.world.entity.Entity) -> c
    1031:1031:boolean isInvertedHealAndHarm() -> ev
    1036:1036:net.minecraft.world.effect.MobEffectInstance removeEffectNoUpdate(net.minecraft.core.Holder) -> d
    1040:1045:boolean removeEffect(net.minecraft.core.Holder) -> e
    1049:1054:void onEffectAdded(net.minecraft.world.effect.MobEffectInstance,net.minecraft.world.entity.Entity) -> a
    1057:1062:void sendEffectToPassengers(net.minecraft.world.effect.MobEffectInstance) -> d
    1065:1075:void onEffectUpdated(net.minecraft.world.effect.MobEffectInstance,boolean,net.minecraft.world.entity.Entity) -> a
    1078:1088:void onEffectRemoved(net.minecraft.world.effect.MobEffectInstance) -> a
    1091:1096:void refreshDirtyAttributes() -> B
    1099:1110:void onAttributeUpdated(net.minecraft.core.Holder) -> i
    1113:1117:void heal(float) -> c
    1120:1120:float getHealth() -> ew
    1124:1125:void setHealth(float) -> v
    1128:1128:boolean isDeadOrDying() -> ex
    1133:1278:boolean hurt(net.minecraft.world.damagesource.DamageSource,float) -> a
    1282:1283:void blockUsingShield(net.minecraft.world.entity.LivingEntity) -> d
    1286:1287:void blockedByShield(net.minecraft.world.entity.LivingEntity) -> e
    1290:1319:boolean checkTotemDeathProtection(net.minecraft.world.damagesource.DamageSource) -> g
    1327:1330:net.minecraft.world.damagesource.DamageSource getLastDamageSource() -> ey
    1334:1335:void playHurtSound(net.minecraft.world.damagesource.DamageSource) -> e
    1338:1341:void makeSound(net.minecraft.sounds.SoundEvent) -> b
    1344:1364:boolean isDamageSourceBlocked(net.minecraft.world.damagesource.DamageSource) -> f
    1368:1374:void breakItem(net.minecraft.world.item.ItemStack) -> i
    1377:1405:void die(net.minecraft.world.damagesource.DamageSource) -> a
    1408:1428:void createWitherRose(net.minecraft.world.entity.LivingEntity) -> f
    1431:1439:void dropAllDeathLoot(net.minecraft.server.level.ServerLevel,net.minecraft.world.damagesource.DamageSource) -> a
    1442:1442:void dropEquipment() -> ez
    1445:1448:void dropExperience(net.minecraft.world.entity.Entity) -> C
    1451:1451:void dropCustomDeathLoot(net.minecraft.server.level.ServerLevel,net.minecraft.world.damagesource.DamageSource,boolean) -> a
    1454:1454:net.minecraft.resources.ResourceKey getLootTable() -> eA
    1458:1458:long getLootTableSeed() -> eB
    1462:1466:float getKnockback(net.minecraft.world.entity.Entity,net.minecraft.world.damagesource.DamageSource) -> a
    1470:1486:void dropFromLootTable(net.minecraft.world.damagesource.DamageSource,boolean) -> a
    1489:1509:void knockback(double,double,double) -> p
    1512:1512:void indicateDamage(double,double) -> a
    1516:1516:net.minecraft.sounds.SoundEvent getHurtSound(net.minecraft.world.damagesource.DamageSource) -> d
    1521:1521:net.minecraft.sounds.SoundEvent getDeathSound() -> n_
    1525:1525:net.minecraft.sounds.SoundEvent getFallDamageSound(int) -> r
    1529:1530:void skipDropExperience() -> eC
    1533:1533:boolean wasExperienceConsumed() -> eD
    1540:1540:float getHurtDir() -> eE
    1544:1550:net.minecraft.world.phys.AABB getHitbox() -> eF
    1554:1554:java.util.Map activeLocationDependentEnchantments() -> eG
    1561:1561:net.minecraft.world.entity.LivingEntity$Fallsounds getFallSounds() -> eH
    1565:1565:net.minecraft.sounds.SoundEvent getDrinkingSound(net.minecraft.world.item.ItemStack) -> c
    1569:1569:net.minecraft.sounds.SoundEvent getEatingSound(net.minecraft.world.item.ItemStack) -> d
    1573:1573:java.util.Optional getLastClimbablePos() -> eI
    1577:1593:boolean onClimbable() -> p_
    1597:1601:boolean trapdoorUsableAsLadder(net.minecraft.core.BlockPos,net.minecraft.world.level.block.state.BlockState) -> c
    1609:1609:boolean isAlive() -> bE
    1614:1614:int getMaxFallDistance() -> cx
    1619:1619:int getComfortableFallDistance(float) -> w
    1624:1633:boolean causeFallDamage(float,float,net.minecraft.world.damagesource.DamageSource) -> a
    1637:1642:int calculateFallDamage(float,float) -> e
    1646:1658:void playBlockFallSound() -> eJ
    1662:1664:void animateHurt(float) -> n
    1672:1672:int getArmorValue() -> eK
    1676:1676:void hurtArmor(net.minecraft.world.damagesource.DamageSource,float) -> b
    1679:1679:void hurtHelmet(net.minecraft.world.damagesource.DamageSource,float) -> c
    1682:1682:void hurtCurrentlyUsedShield(float) -> x
    1685:1696:void doHurtEquipment(net.minecraft.world.damagesource.DamageSource,float,net.minecraft.world.entity.EquipmentSlot[]) -> a
    1699:1703:float getDamageAfterArmorAbsorb(net.minecraft.world.damagesource.DamageSource,float) -> d
    1707:1746:float getDamageAfterMagicAbsorb(net.minecraft.world.damagesource.DamageSource,float) -> e
    1750:1773:void actuallyHurt(net.minecraft.world.damagesource.DamageSource,float) -> f
    1776:1776:net.minecraft.world.damagesource.CombatTracker getCombatTracker() -> eL
    1781:1787:net.minecraft.world.entity.LivingEntity getKillCredit() -> eM
    1791:1791:float getMaxHealth() -> eN
    1795:1795:float getMaxAbsorption() -> eO
    1799:1799:int getArrowCount() -> eP
    1803:1804:void setArrowCount(int) -> p
    1807:1807:int getStingerCount() -> eQ
    1811:1812:void setStingerCount(int) -> q
    1815:1821:int getCurrentSwingDuration() -> C
    1825:1826:void swing(net.minecraft.world.InteractionHand) -> a
    1829:1845:void swing(net.minecraft.world.InteractionHand,boolean) -> a
    1849:1862:void handleDamageEvent(net.minecraft.world.damagesource.DamageSource) -> c
    1866:1934:void handleEntityEvent(byte) -> b
    1937:1943:void makePoofParticles() -> D
    1946:1949:void swapHandItems() -> E
    1953:1954:void onBelowWorld() -> aE
    1957:1969:void updateSwingTime() -> eR
    1973:1973:net.minecraft.world.entity.ai.attributes.AttributeInstance getAttribute(net.minecraft.core.Holder) -> f
    1977:1977:double getAttributeValue(net.minecraft.core.Holder) -> g
    1981:1981:double getAttributeBaseValue(net.minecraft.core.Holder) -> h
    1985:1985:net.minecraft.world.entity.ai.attributes.AttributeMap getAttributes() -> eS
    1989:1989:net.minecraft.world.item.ItemStack getMainHandItem() -> eT
    1993:1993:net.minecraft.world.item.ItemStack getOffhandItem() -> eU
    1999:1999:net.minecraft.world.item.ItemStack getWeaponItem() -> dS
    2003:2003:boolean isHolding(net.minecraft.world.item.Item) -> b
    2007:2007:boolean isHolding(java.util.function.Predicate) -> b
    2011:2016:net.minecraft.world.item.ItemStack getItemInHand(net.minecraft.world.InteractionHand) -> b
    2021:2028:void setItemInHand(net.minecraft.world.InteractionHand,net.minecraft.world.item.ItemStack) -> a
    2031:2031:boolean hasItemInSlot(net.minecraft.world.entity.EquipmentSlot) -> c
    2035:2035:boolean canUseSlot(net.minecraft.world.entity.EquipmentSlot) -> d
    java.lang.Iterable getArmorSlots() -> eV
    net.minecraft.world.item.ItemStack getItemBySlot(net.minecraft.world.entity.EquipmentSlot) -> a
    void setItemSlot(net.minecraft.world.entity.EquipmentSlot,net.minecraft.world.item.ItemStack) -> a
    2045:2045:java.lang.Iterable getHandSlots() -> eW
    2049:2049:java.lang.Iterable getArmorAndBodyArmorSlots() -> eX
    2053:2053:java.lang.Iterable getAllSlots() -> eY
    2057:2058:void verifyEquippedItem(net.minecraft.world.item.ItemStack) -> e
    2061:2071:float getArmorCoverPercentage() -> eZ
    2076:2083:void setSprinting(boolean) -> h
    2086:2086:float getSoundVolume() -> fa
    2090:2093:float getVoicePitch() -> fb
    2097:2097:boolean isImmobile() -> fc
    2102:2105:void push(net.minecraft.world.entity.Entity) -> h
    2109:2121:void dismountVehicle(net.minecraft.world.entity.Entity) -> d
    2125:2125:boolean shouldShowName() -> cF
    2129:2129:float getJumpPower() -> fd
    2134:2134:float getJumpPower(float) -> y
    2138:2138:float getJumpBoostPower() -> fe
    2143:2160:void jumpFromGround() -> ff
    2163:2164:void goDownInWater() -> fg
    2167:2168:void jumpInLiquid(net.minecraft.tags.TagKey) -> c
    2171:2171:float getWaterSlowDown() -> fh
    2175:2175:boolean canStandOnFluid(net.minecraft.world.level.material.FluidState) -> a
    2180:2180:double getDefaultGravity() -> aZ
    2184:2353:void travel(net.minecraft.world.phys.Vec3) -> a
    2356:2369:void travelRidden(net.minecraft.world.entity.player.Player,net.minecraft.world.phys.Vec3) -> c
    2372:2372:void tickRidden(net.minecraft.world.entity.player.Player,net.minecraft.world.phys.Vec3) -> a
    2375:2375:net.minecraft.world.phys.Vec3 getRiddenInput(net.minecraft.world.entity.player.Player,net.minecraft.world.phys.Vec3) -> b
    2379:2379:float getRiddenSpeed(net.minecraft.world.entity.player.Player) -> e
    2383:2389:void calculateEntityAnimation(boolean) -> s
    2392:2394:void updateWalkAnimation(float) -> z
    2397:2406:net.minecraft.world.phys.Vec3 handleRelativeFrictionAndCalculateMovement(net.minecraft.world.phys.Vec3,float) -> a
    2410:2420:net.minecraft.world.phys.Vec3 getFluidFallingAdjustedMovement(double,boolean,net.minecraft.world.phys.Vec3) -> a
    2424:2438:net.minecraft.world.phys.Vec3 handleOnClimbable(net.minecraft.world.phys.Vec3) -> b
    2442:2445:float getFrictionInfluencedSpeed(float) -> E
    2450:2450:float getFlyingSpeed() -> fi
    2454:2454:float getSpeed() -> fj
    2458:2459:void setSpeed(float) -> A
    2462:2463:boolean doHurtTarget(net.minecraft.world.entity.Entity) -> D
    2468:2595:void tick() -> l
    2598:2607:void detectEquipmentUpdates() -> F
    2611:2657:java.util.Map collectEquipmentChanges() -> H
    2661:2661:boolean equipmentHasChanged(net.minecraft.world.item.ItemStack,net.minecraft.world.item.ItemStack) -> a
    2666:2679:void handleHandSwap(java.util.Map) -> a
    2682:2694:void handleEquipmentChanges(java.util.Map) -> b
    2697:2697:net.minecraft.world.item.ItemStack getLastArmorItem(net.minecraft.world.entity.EquipmentSlot) -> e
    2701:2702:void setLastArmorItem(net.minecraft.world.entity.EquipmentSlot,net.minecraft.world.item.ItemStack) -> b
    2705:2705:net.minecraft.world.item.ItemStack getLastHandItem(net.minecraft.world.entity.EquipmentSlot) -> f
    2709:2710:void setLastHandItem(net.minecraft.world.entity.EquipmentSlot,net.minecraft.world.item.ItemStack) -> c
    2713:2728:float tickHeadTurn(float,float) -> f
    2732:2732:float getMaxHeadRotationRelativeToBody() -> fk
    2736:2859:void aiStep() -> m_
    2865:2865:boolean isSensitiveToWater() -> fl
    2869:2894:void updateFallFlying() -> I
    2897:2897:void serverAiStep() -> fm
    2900:2925:void pushEntities() -> r
    2928:2947:void checkAutoSpinAttack(net.minecraft.world.phys.AABB,net.minecraft.world.phys.AABB) -> a
    2950:2951:void doPush(net.minecraft.world.entity.Entity) -> E
    2954:2954:void doAutoAttackOnTouch(net.minecraft.world.entity.LivingEntity) -> g
    2957:2957:boolean isAutoSpinAttack() -> fn
    2962:2967:void stopRiding() -> ad
    2971:2975:void rideTick() -> u
    2979:2986:void lerpTo(double,double,double,float,float,int) -> a
    2990:2990:double lerpTargetX() -> c_
    2995:2995:double lerpTargetY() -> d_
    3000:3000:double lerpTargetZ() -> P_
    3005:3005:float lerpTargetXRot() -> Q_
    3010:3010:float lerpTargetYRot() -> e_
    3015:3018:void lerpHeadTo(float,int) -> a
    3021:3022:void setJumping(boolean) -> t
    3025:3029:void onItemPickup(net.minecraft.world.entity.item.ItemEntity) -> a
    3032:3037:void take(net.minecraft.world.entity.Entity,int) -> a
    3041:3050:boolean hasLineOfSight(net.minecraft.world.entity.Entity) -> F
    3055:3058:float getViewYRot(float) -> i
    3062:3066:float getAttackAnim(float) -> B
    3071:3071:boolean isPickable() -> bA
    3076:3076:boolean isPushable() -> bB
    3081:3081:float getYHeadRot() -> ct
    3086:3087:void setYHeadRot(float) -> o
    3091:3092:void setYBodyRot(float) -> p
    3096:3096:net.minecraft.world.phys.Vec3 getRelativePortalPosition(net.minecraft.core.Direction$Axis,net.minecraft.BlockUtil$FoundRectangle) -> a
    3101:3101:net.minecraft.world.phys.Vec3 resetForwardDirectionOfRelativePortalPosition(net.minecraft.world.phys.Vec3) -> k
    3105:3105:float getAbsorptionAmount() -> fo
    3109:3110:void setAbsorptionAmount(float) -> C
    3113:3114:void internalSetAbsorptionAmount(float) -> D
    3117:3117:void onEnterCombat() -> f_
    3120:3120:void onLeaveCombat() -> g_
    3123:3124:void updateEffectVisibility() -> fp
    net.minecraft.world.entity.HumanoidArm getMainArm() -> fq
    3129:3129:boolean isUsingItem() -> fr
    3133:3133:net.minecraft.world.InteractionHand getUsedItemHand() -> fs
    3137:3146:void updatingUsingItem() -> J
    3149:3156:void updateUsingItem(net.minecraft.world.item.ItemStack) -> a
    3159:3162:boolean shouldTriggerItemUseEffects() -> L
    3166:3172:void updateSwimAmount() -> N
    3175:3182:void setLivingEntityFlag(int,boolean) -> c
    3185:3198:void startUsingItem(net.minecraft.world.InteractionHand) -> c
    3202:3220:void onSyncedDataUpdated(net.minecraft.network.syncher.EntityDataAccessor) -> a
    3224:3228:void lookAt(net.minecraft.commands.arguments.EntityAnchorArgument$Anchor,net.minecraft.world.phys.Vec3) -> a
    3232:3232:float getPreciseBodyRotation(float) -> r
    3236:3248:void triggerItemUseEffects(net.minecraft.world.item.ItemStack,int) -> b
    3251:3263:void spawnItemParticles(net.minecraft.world.item.ItemStack,int) -> a
    3266:3284:void completeUsingItem() -> L_
    3287:3287:net.minecraft.world.item.ItemStack getUseItem() -> ft
    3291:3291:int getUseItemRemainingTicks() -> fu
    3295:3298:int getTicksUsingItem() -> fv
    3302:3309:void releaseUsingItem() -> fw
    3312:3321:void stopUsingItem() -> fx
    3324:3331:boolean isBlocking() -> fy
    3335:3335:boolean isSuppressingSlidingDownLadder() -> fz
    3339:3339:boolean isFallFlying() -> fA
    3346:3346:boolean isVisuallySwimming() -> ce
    3350:3350:int getFallFlyingTicks() -> fB
    3354:3397:boolean randomTeleport(double,double,double,boolean) -> b
    3401:3401:boolean isAffectedByPotions() -> fC
    3405:3405:boolean attackable() -> fD
    3409:3409:void setRecordPlayingNearby(net.minecraft.core.BlockPos,boolean) -> a
    3412:3412:boolean canTakeItem(net.minecraft.world.item.ItemStack) -> f
    3417:3417:net.minecraft.world.entity.EntityDimensions getDimensions(net.minecraft.world.entity.Pose) -> a
    3421:3421:net.minecraft.world.entity.EntityDimensions getDefaultDimensions(net.minecraft.world.entity.Pose) -> e
    3425:3425:com.google.common.collect.ImmutableList getDismountPoses() -> fE
    3429:3432:net.minecraft.world.phys.AABB getLocalBoundsForPose(net.minecraft.world.entity.Pose) -> f
    3437:3438:boolean wouldNotSuffocateAtTargetPose(net.minecraft.world.entity.Pose) -> g
    3443:3443:boolean canUsePortal(boolean) -> o
    3447:3447:java.util.Optional getSleepingPos() -> fF
    3451:3452:void setSleepingPos(net.minecraft.core.BlockPos) -> g
    3455:3456:void clearSleepingPos() -> fG
    3459:3459:boolean isSleeping() -> fH
    3463:3477:void startSleeping(net.minecraft.core.BlockPos) -> b
    3480:3481:void setPosToBed(net.minecraft.core.BlockPos) -> a
    3484:3484:boolean checkBedExists() -> O
    3488:3512:void stopSleeping() -> fI
    3516:3517:net.minecraft.core.Direction getBedOrientation() -> fJ
    3522:3522:boolean isInWall() -> bF
    3526:3526:net.minecraft.world.item.ItemStack getProjectile(net.minecraft.world.item.ItemStack) -> g
    3530:3534:net.minecraft.world.item.ItemStack eat(net.minecraft.world.level.Level,net.minecraft.world.item.ItemStack) -> a
    3538:3543:net.minecraft.world.item.ItemStack eat(net.minecraft.world.level.Level,net.minecraft.world.item.ItemStack,net.minecraft.world.food.FoodProperties) -> a
    3547:3556:void addEatEffect(net.minecraft.world.food.FoodProperties) -> a
    3559:3566:byte entityEventForEquipmentBreak(net.minecraft.world.entity.EquipmentSlot) -> g
    3571:3572:void onEquippedItemBroken(net.minecraft.world.item.Item,net.minecraft.world.entity.EquipmentSlot) -> a
    3575:3575:net.minecraft.world.entity.EquipmentSlot getSlotForHand(net.minecraft.world.InteractionHand) -> d
    3580:3584:net.minecraft.world.phys.AABB getBoundingBoxForCulling() -> h_
    3588:3597:net.minecraft.world.entity.EquipmentSlot getEquipmentSlotForItem(net.minecraft.world.item.ItemStack) -> h
    3601:3604:net.minecraft.world.entity.SlotAccess createEquipmentSlotAccess(net.minecraft.world.entity.LivingEntity,net.minecraft.world.entity.EquipmentSlot) -> a
    3610:3631:net.minecraft.world.entity.EquipmentSlot getEquipmentSlot(int) -> s
    3636:3642:net.minecraft.world.entity.SlotAccess getSlot(int) -> a_
    3647:3655:boolean canFreeze() -> dC
    3660:3660:boolean isCurrentlyGlowing() -> ch
    3665:3665:float getVisualRotationYInDegrees() -> dF
    3670:3689:void recreateFromPacket(net.minecraft.network.protocol.game.ClientboundAddEntityPacket) -> a
    3692:3692:boolean canDisableShield() -> fK
    3697:3698:float maxUpStep() -> dI
    3703:3703:net.minecraft.world.phys.Vec3 getPassengerRidingPosition(net.minecraft.world.entity.Entity) -> m
    3707:3708:void lerpHeadRotationStep(int,double) -> a
    3712:3713:void igniteForTicks(int) -> g
    3716:3716:boolean hasInfiniteMaterials() -> fL
    3721:3722:boolean isInvulnerableTo(net.minecraft.world.damagesource.DamageSource) -> b
    3604:3604:boolean lambda$createEquipmentSlotAccess$10(net.minecraft.world.entity.LivingEntity,net.minecraft.world.entity.EquipmentSlot,net.minecraft.world.item.ItemStack) -> a
    3489:3506:void lambda$stopSleeping$9(net.minecraft.core.BlockPos) -> c
    3495:3496:net.minecraft.world.phys.Vec3 lambda$stopSleeping$8(net.minecraft.core.BlockPos) -> h
    3484:3484:java.lang.Boolean lambda$checkBedExists$7(net.minecraft.core.BlockPos) -> i
    2685:2692:void lambda$handleEquipmentChanges$6(java.util.List,net.minecraft.world.entity.EquipmentSlot,net.minecraft.world.item.ItemStack) -> a
    2645:2653:void lambda$collectEquipmentChanges$5(net.minecraft.world.item.ItemStack,net.minecraft.world.entity.EquipmentSlot,net.minecraft.core.Holder,net.minecraft.world.entity.ai.attributes.AttributeModifier) -> a
    2629:2634:void lambda$collectEquipmentChanges$4(net.minecraft.world.entity.ai.attributes.AttributeMap,net.minecraft.world.item.ItemStack,net.minecraft.world.entity.EquipmentSlot,net.minecraft.core.Holder,net.minecraft.world.entity.ai.attributes.AttributeModifier) -> a
    2003:2003:boolean lambda$isHolding$3(net.minecraft.world.item.Item,net.minecraft.world.item.ItemStack) -> a
    814:814:void lambda$tickEffects$2(net.minecraft.world.effect.MobEffectInstance) -> e
    743:743:void lambda$addAdditionalSaveData$1(net.minecraft.nbt.CompoundTag,net.minecraft.nbt.Tag) -> a
    737:740:void lambda$addAdditionalSaveData$0(net.minecraft.nbt.CompoundTag,net.minecraft.core.BlockPos) -> a
    139:179:void <clinit>() -> <clinit>
 */
open class LivingEntity(around: Any) : Entity(around) {
	companion object : ClassInfo {
		override val clazz: Class<*> = loadClass(net_minecraft_world_entity_LivingEntity)
		override val classDesc: ClassDesc =clazz.classDesc
		override val mimicClassDesc: ClassDesc = LivingEntity::class.classDesc
	}

	fun isHolding(item: Item): Boolean =
		clazz.getMethod("b", Item.clazz).invoke(around, item.around) as Boolean
}