package org.bread_experts_group.eam.minecraft.version_impl.v1x21x1.net.minecraft.client.sounds

import org.bread_experts_group.eam.classDesc
import org.bread_experts_group.eam.loadClass
import org.bread_experts_group.eam.minecraft.mimic.ClassInfo
import org.bread_experts_group.eam.minecraft.mimic.MimickedClass
import org.bread_experts_group.eam.minecraft.version_impl.v1x21x1.net.minecraft.core.Holder
import org.bread_experts_group.eam.minecraft.version_impl.v1x21x1.net_minecraft_sounds_SoundEvents
import java.lang.constant.ClassDesc

/*
net.minecraft.sounds.SoundEvents -> avp:
# {"fileName":"SoundEvents.java","id":"sourceFile"}
    net.minecraft.sounds.SoundEvent ALLAY_AMBIENT_WITH_ITEM -> a
    net.minecraft.sounds.SoundEvent ALLAY_AMBIENT_WITHOUT_ITEM -> b
    net.minecraft.sounds.SoundEvent ALLAY_DEATH -> c
    net.minecraft.sounds.SoundEvent ALLAY_HURT -> d
    net.minecraft.sounds.SoundEvent ALLAY_ITEM_GIVEN -> e
    net.minecraft.sounds.SoundEvent ALLAY_ITEM_TAKEN -> f
    net.minecraft.sounds.SoundEvent ALLAY_THROW -> g
    net.minecraft.core.Holder$Reference AMBIENT_CAVE -> h
    net.minecraft.core.Holder$Reference AMBIENT_BASALT_DELTAS_ADDITIONS -> i
    net.minecraft.core.Holder$Reference AMBIENT_BASALT_DELTAS_LOOP -> j
    net.minecraft.core.Holder$Reference AMBIENT_BASALT_DELTAS_MOOD -> k
    net.minecraft.core.Holder$Reference AMBIENT_CRIMSON_FOREST_ADDITIONS -> l
    net.minecraft.core.Holder$Reference AMBIENT_CRIMSON_FOREST_LOOP -> m
    net.minecraft.core.Holder$Reference AMBIENT_CRIMSON_FOREST_MOOD -> n
    net.minecraft.core.Holder$Reference AMBIENT_NETHER_WASTES_ADDITIONS -> o
    net.minecraft.core.Holder$Reference AMBIENT_NETHER_WASTES_LOOP -> p
    net.minecraft.core.Holder$Reference AMBIENT_NETHER_WASTES_MOOD -> q
    net.minecraft.core.Holder$Reference AMBIENT_SOUL_SAND_VALLEY_ADDITIONS -> r
    net.minecraft.core.Holder$Reference AMBIENT_SOUL_SAND_VALLEY_LOOP -> s
    net.minecraft.core.Holder$Reference AMBIENT_SOUL_SAND_VALLEY_MOOD -> t
    net.minecraft.core.Holder$Reference AMBIENT_WARPED_FOREST_ADDITIONS -> u
    net.minecraft.core.Holder$Reference AMBIENT_WARPED_FOREST_LOOP -> v
    net.minecraft.core.Holder$Reference AMBIENT_WARPED_FOREST_MOOD -> w
    net.minecraft.sounds.SoundEvent AMBIENT_UNDERWATER_ENTER -> x
    net.minecraft.sounds.SoundEvent AMBIENT_UNDERWATER_EXIT -> y
    net.minecraft.sounds.SoundEvent AMBIENT_UNDERWATER_LOOP -> z
    net.minecraft.sounds.SoundEvent AMBIENT_UNDERWATER_LOOP_ADDITIONS -> A
    net.minecraft.sounds.SoundEvent AMBIENT_UNDERWATER_LOOP_ADDITIONS_RARE -> B
    net.minecraft.sounds.SoundEvent AMBIENT_UNDERWATER_LOOP_ADDITIONS_ULTRA_RARE -> C
    net.minecraft.sounds.SoundEvent AMETHYST_BLOCK_BREAK -> D
    net.minecraft.sounds.SoundEvent AMETHYST_BLOCK_CHIME -> E
    net.minecraft.sounds.SoundEvent AMETHYST_BLOCK_FALL -> F
    net.minecraft.sounds.SoundEvent AMETHYST_BLOCK_HIT -> G
    net.minecraft.sounds.SoundEvent AMETHYST_BLOCK_PLACE -> H
    net.minecraft.sounds.SoundEvent AMETHYST_BLOCK_RESONATE -> I
    net.minecraft.sounds.SoundEvent AMETHYST_BLOCK_STEP -> J
    net.minecraft.sounds.SoundEvent AMETHYST_CLUSTER_BREAK -> K
    net.minecraft.sounds.SoundEvent AMETHYST_CLUSTER_FALL -> L
    net.minecraft.sounds.SoundEvent AMETHYST_CLUSTER_HIT -> M
    net.minecraft.sounds.SoundEvent AMETHYST_CLUSTER_PLACE -> N
    net.minecraft.sounds.SoundEvent AMETHYST_CLUSTER_STEP -> O
    net.minecraft.sounds.SoundEvent ANCIENT_DEBRIS_BREAK -> P
    net.minecraft.sounds.SoundEvent ANCIENT_DEBRIS_STEP -> Q
    net.minecraft.sounds.SoundEvent ANCIENT_DEBRIS_PLACE -> R
    net.minecraft.sounds.SoundEvent ANCIENT_DEBRIS_HIT -> S
    net.minecraft.sounds.SoundEvent ANCIENT_DEBRIS_FALL -> T
    net.minecraft.sounds.SoundEvent ANVIL_BREAK -> U
    net.minecraft.sounds.SoundEvent ANVIL_DESTROY -> V
    net.minecraft.sounds.SoundEvent ANVIL_FALL -> W
    net.minecraft.sounds.SoundEvent ANVIL_HIT -> X
    net.minecraft.sounds.SoundEvent ANVIL_LAND -> Y
    net.minecraft.sounds.SoundEvent ANVIL_PLACE -> Z
    net.minecraft.sounds.SoundEvent ANVIL_STEP -> aa
    net.minecraft.sounds.SoundEvent ANVIL_USE -> ab
    net.minecraft.sounds.SoundEvent ARMADILLO_EAT -> ac
    net.minecraft.sounds.SoundEvent ARMADILLO_HURT -> ad
    net.minecraft.sounds.SoundEvent ARMADILLO_HURT_REDUCED -> ae
    net.minecraft.sounds.SoundEvent ARMADILLO_AMBIENT -> af
    net.minecraft.sounds.SoundEvent ARMADILLO_STEP -> ag
    net.minecraft.sounds.SoundEvent ARMADILLO_DEATH -> ah
    net.minecraft.sounds.SoundEvent ARMADILLO_ROLL -> ai
    net.minecraft.sounds.SoundEvent ARMADILLO_LAND -> aj
    net.minecraft.sounds.SoundEvent ARMADILLO_SCUTE_DROP -> ak
    net.minecraft.sounds.SoundEvent ARMADILLO_UNROLL_FINISH -> al
    net.minecraft.sounds.SoundEvent ARMADILLO_PEEK -> am
    net.minecraft.sounds.SoundEvent ARMADILLO_UNROLL_START -> an
    net.minecraft.sounds.SoundEvent ARMADILLO_BRUSH -> ao
    net.minecraft.core.Holder ARMOR_EQUIP_CHAIN -> ap
    net.minecraft.core.Holder ARMOR_EQUIP_DIAMOND -> aq
    net.minecraft.core.Holder ARMOR_EQUIP_ELYTRA -> ar
    net.minecraft.core.Holder ARMOR_EQUIP_GENERIC -> as
    net.minecraft.core.Holder ARMOR_EQUIP_GOLD -> at
    net.minecraft.core.Holder ARMOR_EQUIP_IRON -> au
    net.minecraft.core.Holder ARMOR_EQUIP_LEATHER -> av
    net.minecraft.core.Holder ARMOR_EQUIP_NETHERITE -> aw
    net.minecraft.core.Holder ARMOR_EQUIP_TURTLE -> ax
    net.minecraft.core.Holder ARMOR_EQUIP_WOLF -> ay
    net.minecraft.sounds.SoundEvent ARMOR_UNEQUIP_WOLF -> az
    net.minecraft.sounds.SoundEvent ARMOR_STAND_BREAK -> aA
    net.minecraft.sounds.SoundEvent ARMOR_STAND_FALL -> aB
    net.minecraft.sounds.SoundEvent ARMOR_STAND_HIT -> aC
    net.minecraft.sounds.SoundEvent ARMOR_STAND_PLACE -> aD
    net.minecraft.sounds.SoundEvent ARROW_HIT -> aE
    net.minecraft.sounds.SoundEvent ARROW_HIT_PLAYER -> aF
    net.minecraft.sounds.SoundEvent ARROW_SHOOT -> aG
    net.minecraft.sounds.SoundEvent AXE_STRIP -> aH
    net.minecraft.sounds.SoundEvent AXE_SCRAPE -> aI
    net.minecraft.sounds.SoundEvent AXE_WAX_OFF -> aJ
    net.minecraft.sounds.SoundEvent AXOLOTL_ATTACK -> aK
    net.minecraft.sounds.SoundEvent AXOLOTL_DEATH -> aL
    net.minecraft.sounds.SoundEvent AXOLOTL_HURT -> aM
    net.minecraft.sounds.SoundEvent AXOLOTL_IDLE_AIR -> aN
    net.minecraft.sounds.SoundEvent AXOLOTL_IDLE_WATER -> aO
    net.minecraft.sounds.SoundEvent AXOLOTL_SPLASH -> aP
    net.minecraft.sounds.SoundEvent AXOLOTL_SWIM -> aQ
    net.minecraft.sounds.SoundEvent AZALEA_BREAK -> aR
    net.minecraft.sounds.SoundEvent AZALEA_FALL -> aS
    net.minecraft.sounds.SoundEvent AZALEA_HIT -> aT
    net.minecraft.sounds.SoundEvent AZALEA_PLACE -> aU
    net.minecraft.sounds.SoundEvent AZALEA_STEP -> aV
    net.minecraft.sounds.SoundEvent AZALEA_LEAVES_BREAK -> aW
    net.minecraft.sounds.SoundEvent AZALEA_LEAVES_FALL -> aX
    net.minecraft.sounds.SoundEvent AZALEA_LEAVES_HIT -> aY
    net.minecraft.sounds.SoundEvent AZALEA_LEAVES_PLACE -> aZ
    net.minecraft.sounds.SoundEvent AZALEA_LEAVES_STEP -> ba
    net.minecraft.sounds.SoundEvent BAMBOO_BREAK -> bb
    net.minecraft.sounds.SoundEvent BAMBOO_FALL -> bc
    net.minecraft.sounds.SoundEvent BAMBOO_HIT -> bd
    net.minecraft.sounds.SoundEvent BAMBOO_PLACE -> be
    net.minecraft.sounds.SoundEvent BAMBOO_STEP -> bf
    net.minecraft.sounds.SoundEvent BAMBOO_SAPLING_BREAK -> bg
    net.minecraft.sounds.SoundEvent BAMBOO_SAPLING_HIT -> bh
    net.minecraft.sounds.SoundEvent BAMBOO_SAPLING_PLACE -> bi
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_BREAK -> bj
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_FALL -> bk
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_HIT -> bl
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_PLACE -> bm
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_STEP -> bn
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_DOOR_CLOSE -> bo
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_DOOR_OPEN -> bp
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_TRAPDOOR_CLOSE -> bq
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_TRAPDOOR_OPEN -> br
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_BUTTON_CLICK_OFF -> bs
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_BUTTON_CLICK_ON -> bt
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_PRESSURE_PLATE_CLICK_OFF -> bu
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_PRESSURE_PLATE_CLICK_ON -> bv
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_FENCE_GATE_CLOSE -> bw
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_FENCE_GATE_OPEN -> bx
    net.minecraft.sounds.SoundEvent BARREL_CLOSE -> by
    net.minecraft.sounds.SoundEvent BARREL_OPEN -> bz
    net.minecraft.sounds.SoundEvent BASALT_BREAK -> bA
    net.minecraft.sounds.SoundEvent BASALT_STEP -> bB
    net.minecraft.sounds.SoundEvent BASALT_PLACE -> bC
    net.minecraft.sounds.SoundEvent BASALT_HIT -> bD
    net.minecraft.sounds.SoundEvent BASALT_FALL -> bE
    net.minecraft.sounds.SoundEvent BAT_AMBIENT -> bF
    net.minecraft.sounds.SoundEvent BAT_DEATH -> bG
    net.minecraft.sounds.SoundEvent BAT_HURT -> bH
    net.minecraft.sounds.SoundEvent BAT_LOOP -> bI
    net.minecraft.sounds.SoundEvent BAT_TAKEOFF -> bJ
    net.minecraft.sounds.SoundEvent BEACON_ACTIVATE -> bK
    net.minecraft.sounds.SoundEvent BEACON_AMBIENT -> bL
    net.minecraft.sounds.SoundEvent BEACON_DEACTIVATE -> bM
    net.minecraft.sounds.SoundEvent BEACON_POWER_SELECT -> bN
    net.minecraft.sounds.SoundEvent BEE_DEATH -> bO
    net.minecraft.sounds.SoundEvent BEE_HURT -> bP
    net.minecraft.sounds.SoundEvent BEE_LOOP_AGGRESSIVE -> bQ
    net.minecraft.sounds.SoundEvent BEE_LOOP -> bR
    net.minecraft.sounds.SoundEvent BEE_STING -> bS
    net.minecraft.sounds.SoundEvent BEE_POLLINATE -> bT
    net.minecraft.sounds.SoundEvent BEEHIVE_DRIP -> bU
    net.minecraft.sounds.SoundEvent BEEHIVE_ENTER -> bV
    net.minecraft.sounds.SoundEvent BEEHIVE_EXIT -> bW
    net.minecraft.sounds.SoundEvent BEEHIVE_SHEAR -> bX
    net.minecraft.sounds.SoundEvent BEEHIVE_WORK -> bY
    net.minecraft.sounds.SoundEvent BELL_BLOCK -> bZ
    net.minecraft.sounds.SoundEvent BELL_RESONATE -> ca
    net.minecraft.sounds.SoundEvent BIG_DRIPLEAF_BREAK -> cb
    net.minecraft.sounds.SoundEvent BIG_DRIPLEAF_FALL -> cc
    net.minecraft.sounds.SoundEvent BIG_DRIPLEAF_HIT -> cd
    net.minecraft.sounds.SoundEvent BIG_DRIPLEAF_PLACE -> ce
    net.minecraft.sounds.SoundEvent BIG_DRIPLEAF_STEP -> cf
    net.minecraft.sounds.SoundEvent BLAZE_AMBIENT -> cg
    net.minecraft.sounds.SoundEvent BLAZE_BURN -> ch
    net.minecraft.sounds.SoundEvent BLAZE_DEATH -> ci
    net.minecraft.sounds.SoundEvent BLAZE_HURT -> cj
    net.minecraft.sounds.SoundEvent BLAZE_SHOOT -> ck
    net.minecraft.sounds.SoundEvent BOAT_PADDLE_LAND -> cl
    net.minecraft.sounds.SoundEvent BOAT_PADDLE_WATER -> cm
    net.minecraft.sounds.SoundEvent BOGGED_AMBIENT -> cn
    net.minecraft.sounds.SoundEvent BOGGED_DEATH -> co
    net.minecraft.sounds.SoundEvent BOGGED_HURT -> cp
    net.minecraft.sounds.SoundEvent BOGGED_SHEAR -> cq
    net.minecraft.sounds.SoundEvent BOGGED_STEP -> cr
    net.minecraft.sounds.SoundEvent BONE_BLOCK_BREAK -> cs
    net.minecraft.sounds.SoundEvent BONE_BLOCK_FALL -> ct
    net.minecraft.sounds.SoundEvent BONE_BLOCK_HIT -> cu
    net.minecraft.sounds.SoundEvent BONE_BLOCK_PLACE -> cv
    net.minecraft.sounds.SoundEvent BONE_BLOCK_STEP -> cw
    net.minecraft.sounds.SoundEvent BONE_MEAL_USE -> cx
    net.minecraft.sounds.SoundEvent BOOK_PAGE_TURN -> cy
    net.minecraft.sounds.SoundEvent BOOK_PUT -> cz
    net.minecraft.sounds.SoundEvent BLASTFURNACE_FIRE_CRACKLE -> cA
    net.minecraft.sounds.SoundEvent BOTTLE_EMPTY -> cB
    net.minecraft.sounds.SoundEvent BOTTLE_FILL -> cC
    net.minecraft.sounds.SoundEvent BOTTLE_FILL_DRAGONBREATH -> cD
    net.minecraft.sounds.SoundEvent BREEZE_CHARGE -> cE
    net.minecraft.sounds.SoundEvent BREEZE_DEFLECT -> cF
    net.minecraft.sounds.SoundEvent BREEZE_INHALE -> cG
    net.minecraft.sounds.SoundEvent BREEZE_IDLE_GROUND -> cH
    net.minecraft.sounds.SoundEvent BREEZE_IDLE_AIR -> cI
    net.minecraft.sounds.SoundEvent BREEZE_SHOOT -> cJ
    net.minecraft.sounds.SoundEvent BREEZE_JUMP -> cK
    net.minecraft.sounds.SoundEvent BREEZE_LAND -> cL
    net.minecraft.sounds.SoundEvent BREEZE_SLIDE -> cM
    net.minecraft.sounds.SoundEvent BREEZE_DEATH -> cN
    net.minecraft.sounds.SoundEvent BREEZE_HURT -> cO
    net.minecraft.sounds.SoundEvent BREEZE_WHIRL -> cP
    net.minecraft.core.Holder$Reference BREEZE_WIND_CHARGE_BURST -> cQ
    net.minecraft.sounds.SoundEvent BREWING_STAND_BREW -> cR
    net.minecraft.sounds.SoundEvent BRUSH_GENERIC -> cS
    net.minecraft.sounds.SoundEvent BRUSH_SAND -> cT
    net.minecraft.sounds.SoundEvent BRUSH_GRAVEL -> cU
    net.minecraft.sounds.SoundEvent BRUSH_SAND_COMPLETED -> cV
    net.minecraft.sounds.SoundEvent BRUSH_GRAVEL_COMPLETED -> cW
    net.minecraft.sounds.SoundEvent BUBBLE_COLUMN_BUBBLE_POP -> cX
    net.minecraft.sounds.SoundEvent BUBBLE_COLUMN_UPWARDS_AMBIENT -> cY
    net.minecraft.sounds.SoundEvent BUBBLE_COLUMN_UPWARDS_INSIDE -> cZ
    net.minecraft.sounds.SoundEvent BUBBLE_COLUMN_WHIRLPOOL_AMBIENT -> da
    net.minecraft.sounds.SoundEvent BUBBLE_COLUMN_WHIRLPOOL_INSIDE -> db
    net.minecraft.sounds.SoundEvent BUCKET_EMPTY -> dc
    net.minecraft.sounds.SoundEvent BUCKET_EMPTY_AXOLOTL -> dd
    net.minecraft.sounds.SoundEvent BUCKET_EMPTY_FISH -> de
    net.minecraft.sounds.SoundEvent BUCKET_EMPTY_LAVA -> df
    net.minecraft.sounds.SoundEvent BUCKET_EMPTY_POWDER_SNOW -> dg
    net.minecraft.sounds.SoundEvent BUCKET_EMPTY_TADPOLE -> dh
    net.minecraft.sounds.SoundEvent BUCKET_FILL -> di
    net.minecraft.sounds.SoundEvent BUCKET_FILL_AXOLOTL -> dj
    net.minecraft.sounds.SoundEvent BUCKET_FILL_FISH -> dk
    net.minecraft.sounds.SoundEvent BUCKET_FILL_LAVA -> dl
    net.minecraft.sounds.SoundEvent BUCKET_FILL_POWDER_SNOW -> dm
    net.minecraft.sounds.SoundEvent BUCKET_FILL_TADPOLE -> dn
    net.minecraft.sounds.SoundEvent BUNDLE_DROP_CONTENTS -> do
    net.minecraft.sounds.SoundEvent BUNDLE_INSERT -> dp
    net.minecraft.sounds.SoundEvent BUNDLE_REMOVE_ONE -> dq
    net.minecraft.sounds.SoundEvent CAKE_ADD_CANDLE -> dr
    net.minecraft.sounds.SoundEvent CALCITE_BREAK -> ds
    net.minecraft.sounds.SoundEvent CALCITE_STEP -> dt
    net.minecraft.sounds.SoundEvent CALCITE_PLACE -> du
    net.minecraft.sounds.SoundEvent CALCITE_HIT -> dv
    net.minecraft.sounds.SoundEvent CALCITE_FALL -> dw
    net.minecraft.sounds.SoundEvent CAMEL_AMBIENT -> dx
    net.minecraft.sounds.SoundEvent CAMEL_DASH -> dy
    net.minecraft.sounds.SoundEvent CAMEL_DASH_READY -> dz
    net.minecraft.sounds.SoundEvent CAMEL_DEATH -> dA
    net.minecraft.sounds.SoundEvent CAMEL_EAT -> dB
    net.minecraft.sounds.SoundEvent CAMEL_HURT -> dC
    net.minecraft.sounds.SoundEvent CAMEL_SADDLE -> dD
    net.minecraft.sounds.SoundEvent CAMEL_SIT -> dE
    net.minecraft.sounds.SoundEvent CAMEL_STAND -> dF
    net.minecraft.sounds.SoundEvent CAMEL_STEP -> dG
    net.minecraft.sounds.SoundEvent CAMEL_STEP_SAND -> dH
    net.minecraft.sounds.SoundEvent CAMPFIRE_CRACKLE -> dI
    net.minecraft.sounds.SoundEvent CANDLE_AMBIENT -> dJ
    net.minecraft.sounds.SoundEvent CANDLE_BREAK -> dK
    net.minecraft.sounds.SoundEvent CANDLE_EXTINGUISH -> dL
    net.minecraft.sounds.SoundEvent CANDLE_FALL -> dM
    net.minecraft.sounds.SoundEvent CANDLE_HIT -> dN
    net.minecraft.sounds.SoundEvent CANDLE_PLACE -> dO
    net.minecraft.sounds.SoundEvent CANDLE_STEP -> dP
    net.minecraft.sounds.SoundEvent CAT_AMBIENT -> dQ
    net.minecraft.sounds.SoundEvent CAT_STRAY_AMBIENT -> dR
    net.minecraft.sounds.SoundEvent CAT_DEATH -> dS
    net.minecraft.sounds.SoundEvent CAT_EAT -> dT
    net.minecraft.sounds.SoundEvent CAT_HISS -> dU
    net.minecraft.sounds.SoundEvent CAT_BEG_FOR_FOOD -> dV
    net.minecraft.sounds.SoundEvent CAT_HURT -> dW
    net.minecraft.sounds.SoundEvent CAT_PURR -> dX
    net.minecraft.sounds.SoundEvent CAT_PURREOW -> dY
    net.minecraft.sounds.SoundEvent CAVE_VINES_BREAK -> dZ
    net.minecraft.sounds.SoundEvent CAVE_VINES_FALL -> ea
    net.minecraft.sounds.SoundEvent CAVE_VINES_HIT -> eb
    net.minecraft.sounds.SoundEvent CAVE_VINES_PLACE -> ec
    net.minecraft.sounds.SoundEvent CAVE_VINES_STEP -> ed
    net.minecraft.sounds.SoundEvent CAVE_VINES_PICK_BERRIES -> ee
    net.minecraft.sounds.SoundEvent CHAIN_BREAK -> ef
    net.minecraft.sounds.SoundEvent CHAIN_FALL -> eg
    net.minecraft.sounds.SoundEvent CHAIN_HIT -> eh
    net.minecraft.sounds.SoundEvent CHAIN_PLACE -> ei
    net.minecraft.sounds.SoundEvent CHAIN_STEP -> ej
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_BREAK -> ek
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_FALL -> el
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_HIT -> em
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_PLACE -> en
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_STEP -> eo
    net.minecraft.sounds.SoundEvent CHERRY_SAPLING_BREAK -> ep
    net.minecraft.sounds.SoundEvent CHERRY_SAPLING_FALL -> eq
    net.minecraft.sounds.SoundEvent CHERRY_SAPLING_HIT -> er
    net.minecraft.sounds.SoundEvent CHERRY_SAPLING_PLACE -> es
    net.minecraft.sounds.SoundEvent CHERRY_SAPLING_STEP -> et
    net.minecraft.sounds.SoundEvent CHERRY_LEAVES_BREAK -> eu
    net.minecraft.sounds.SoundEvent CHERRY_LEAVES_FALL -> ev
    net.minecraft.sounds.SoundEvent CHERRY_LEAVES_HIT -> ew
    net.minecraft.sounds.SoundEvent CHERRY_LEAVES_PLACE -> ex
    net.minecraft.sounds.SoundEvent CHERRY_LEAVES_STEP -> ey
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_HANGING_SIGN_STEP -> ez
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_HANGING_SIGN_BREAK -> eA
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_HANGING_SIGN_FALL -> eB
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_HANGING_SIGN_HIT -> eC
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_HANGING_SIGN_PLACE -> eD
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_DOOR_CLOSE -> eE
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_DOOR_OPEN -> eF
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_TRAPDOOR_CLOSE -> eG
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_TRAPDOOR_OPEN -> eH
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_BUTTON_CLICK_OFF -> eI
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_BUTTON_CLICK_ON -> eJ
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_PRESSURE_PLATE_CLICK_OFF -> eK
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_PRESSURE_PLATE_CLICK_ON -> eL
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_FENCE_GATE_CLOSE -> eM
    net.minecraft.sounds.SoundEvent CHERRY_WOOD_FENCE_GATE_OPEN -> eN
    net.minecraft.sounds.SoundEvent CHEST_CLOSE -> eO
    net.minecraft.sounds.SoundEvent CHEST_LOCKED -> eP
    net.minecraft.sounds.SoundEvent CHEST_OPEN -> eQ
    net.minecraft.sounds.SoundEvent CHICKEN_AMBIENT -> eR
    net.minecraft.sounds.SoundEvent CHICKEN_DEATH -> eS
    net.minecraft.sounds.SoundEvent CHICKEN_EGG -> eT
    net.minecraft.sounds.SoundEvent CHICKEN_HURT -> eU
    net.minecraft.sounds.SoundEvent CHICKEN_STEP -> eV
    net.minecraft.sounds.SoundEvent CHISELED_BOOKSHELF_BREAK -> eW
    net.minecraft.sounds.SoundEvent CHISELED_BOOKSHELF_FALL -> eX
    net.minecraft.sounds.SoundEvent CHISELED_BOOKSHELF_HIT -> eY
    net.minecraft.sounds.SoundEvent CHISELED_BOOKSHELF_INSERT -> eZ
    net.minecraft.sounds.SoundEvent CHISELED_BOOKSHELF_INSERT_ENCHANTED -> fa
    net.minecraft.sounds.SoundEvent CHISELED_BOOKSHELF_STEP -> fb
    net.minecraft.sounds.SoundEvent CHISELED_BOOKSHELF_PICKUP -> fc
    net.minecraft.sounds.SoundEvent CHISELED_BOOKSHELF_PICKUP_ENCHANTED -> fd
    net.minecraft.sounds.SoundEvent CHISELED_BOOKSHELF_PLACE -> fe
    net.minecraft.sounds.SoundEvent CHORUS_FLOWER_DEATH -> ff
    net.minecraft.sounds.SoundEvent CHORUS_FLOWER_GROW -> fg
    net.minecraft.sounds.SoundEvent CHORUS_FRUIT_TELEPORT -> fh
    net.minecraft.sounds.SoundEvent COBWEB_BREAK -> fi
    net.minecraft.sounds.SoundEvent COBWEB_STEP -> fj
    net.minecraft.sounds.SoundEvent COBWEB_PLACE -> fk
    net.minecraft.sounds.SoundEvent COBWEB_HIT -> fl
    net.minecraft.sounds.SoundEvent COBWEB_FALL -> fm
    net.minecraft.sounds.SoundEvent COD_AMBIENT -> fn
    net.minecraft.sounds.SoundEvent COD_DEATH -> fo
    net.minecraft.sounds.SoundEvent COD_FLOP -> fp
    net.minecraft.sounds.SoundEvent COD_HURT -> fq
    net.minecraft.sounds.SoundEvent COMPARATOR_CLICK -> fr
    net.minecraft.sounds.SoundEvent COMPOSTER_EMPTY -> fs
    net.minecraft.sounds.SoundEvent COMPOSTER_FILL -> ft
    net.minecraft.sounds.SoundEvent COMPOSTER_FILL_SUCCESS -> fu
    net.minecraft.sounds.SoundEvent COMPOSTER_READY -> fv
    net.minecraft.sounds.SoundEvent CONDUIT_ACTIVATE -> fw
    net.minecraft.sounds.SoundEvent CONDUIT_AMBIENT -> fx
    net.minecraft.sounds.SoundEvent CONDUIT_AMBIENT_SHORT -> fy
    net.minecraft.sounds.SoundEvent CONDUIT_ATTACK_TARGET -> fz
    net.minecraft.sounds.SoundEvent CONDUIT_DEACTIVATE -> fA
    net.minecraft.sounds.SoundEvent COPPER_BULB_BREAK -> fB
    net.minecraft.sounds.SoundEvent COPPER_BULB_STEP -> fC
    net.minecraft.sounds.SoundEvent COPPER_BULB_PLACE -> fD
    net.minecraft.sounds.SoundEvent COPPER_BULB_HIT -> fE
    net.minecraft.sounds.SoundEvent COPPER_BULB_FALL -> fF
    net.minecraft.sounds.SoundEvent COPPER_BULB_TURN_ON -> fG
    net.minecraft.sounds.SoundEvent COPPER_BULB_TURN_OFF -> fH
    net.minecraft.sounds.SoundEvent COPPER_BREAK -> fI
    net.minecraft.sounds.SoundEvent COPPER_STEP -> fJ
    net.minecraft.sounds.SoundEvent COPPER_PLACE -> fK
    net.minecraft.sounds.SoundEvent COPPER_HIT -> fL
    net.minecraft.sounds.SoundEvent COPPER_FALL -> fM
    net.minecraft.sounds.SoundEvent COPPER_DOOR_CLOSE -> fN
    net.minecraft.sounds.SoundEvent COPPER_DOOR_OPEN -> fO
    net.minecraft.sounds.SoundEvent COPPER_GRATE_BREAK -> fP
    net.minecraft.sounds.SoundEvent COPPER_GRATE_STEP -> fQ
    net.minecraft.sounds.SoundEvent COPPER_GRATE_PLACE -> fR
    net.minecraft.sounds.SoundEvent COPPER_GRATE_HIT -> fS
    net.minecraft.sounds.SoundEvent COPPER_GRATE_FALL -> fT
    net.minecraft.sounds.SoundEvent COPPER_TRAPDOOR_CLOSE -> fU
    net.minecraft.sounds.SoundEvent COPPER_TRAPDOOR_OPEN -> fV
    net.minecraft.sounds.SoundEvent CORAL_BLOCK_BREAK -> fW
    net.minecraft.sounds.SoundEvent CORAL_BLOCK_FALL -> fX
    net.minecraft.sounds.SoundEvent CORAL_BLOCK_HIT -> fY
    net.minecraft.sounds.SoundEvent CORAL_BLOCK_PLACE -> fZ
    net.minecraft.sounds.SoundEvent CORAL_BLOCK_STEP -> ga
    net.minecraft.sounds.SoundEvent COW_AMBIENT -> gb
    net.minecraft.sounds.SoundEvent COW_DEATH -> gc
    net.minecraft.sounds.SoundEvent COW_HURT -> gd
    net.minecraft.sounds.SoundEvent COW_MILK -> ge
    net.minecraft.sounds.SoundEvent COW_STEP -> gf
    net.minecraft.sounds.SoundEvent CRAFTER_CRAFT -> gg
    net.minecraft.sounds.SoundEvent CRAFTER_FAIL -> gh
    net.minecraft.sounds.SoundEvent CREEPER_DEATH -> gi
    net.minecraft.sounds.SoundEvent CREEPER_HURT -> gj
    net.minecraft.sounds.SoundEvent CREEPER_PRIMED -> gk
    net.minecraft.sounds.SoundEvent CROP_BREAK -> gl
    net.minecraft.sounds.SoundEvent CROP_PLANTED -> gm
    net.minecraft.sounds.SoundEvent CROSSBOW_HIT -> gn
    net.minecraft.core.Holder CROSSBOW_LOADING_END -> go
    net.minecraft.core.Holder CROSSBOW_LOADING_MIDDLE -> gp
    net.minecraft.core.Holder CROSSBOW_LOADING_START -> gq
    net.minecraft.core.Holder CROSSBOW_QUICK_CHARGE_1 -> gr
    net.minecraft.core.Holder CROSSBOW_QUICK_CHARGE_2 -> gs
    net.minecraft.core.Holder CROSSBOW_QUICK_CHARGE_3 -> gt
    net.minecraft.sounds.SoundEvent CROSSBOW_SHOOT -> gu
    net.minecraft.sounds.SoundEvent DECORATED_POT_BREAK -> gv
    net.minecraft.sounds.SoundEvent DECORATED_POT_FALL -> gw
    net.minecraft.sounds.SoundEvent DECORATED_POT_HIT -> gx
    net.minecraft.sounds.SoundEvent DECORATED_POT_INSERT -> gy
    net.minecraft.sounds.SoundEvent DECORATED_POT_INSERT_FAIL -> gz
    net.minecraft.sounds.SoundEvent DECORATED_POT_STEP -> gA
    net.minecraft.sounds.SoundEvent DECORATED_POT_PLACE -> gB
    net.minecraft.sounds.SoundEvent DECORATED_POT_SHATTER -> gC
    net.minecraft.sounds.SoundEvent DEEPSLATE_BRICKS_BREAK -> gD
    net.minecraft.sounds.SoundEvent DEEPSLATE_BRICKS_FALL -> gE
    net.minecraft.sounds.SoundEvent DEEPSLATE_BRICKS_HIT -> gF
    net.minecraft.sounds.SoundEvent DEEPSLATE_BRICKS_PLACE -> gG
    net.minecraft.sounds.SoundEvent DEEPSLATE_BRICKS_STEP -> gH
    net.minecraft.sounds.SoundEvent DEEPSLATE_BREAK -> gI
    net.minecraft.sounds.SoundEvent DEEPSLATE_FALL -> gJ
    net.minecraft.sounds.SoundEvent DEEPSLATE_HIT -> gK
    net.minecraft.sounds.SoundEvent DEEPSLATE_PLACE -> gL
    net.minecraft.sounds.SoundEvent DEEPSLATE_STEP -> gM
    net.minecraft.sounds.SoundEvent DEEPSLATE_TILES_BREAK -> gN
    net.minecraft.sounds.SoundEvent DEEPSLATE_TILES_FALL -> gO
    net.minecraft.sounds.SoundEvent DEEPSLATE_TILES_HIT -> gP
    net.minecraft.sounds.SoundEvent DEEPSLATE_TILES_PLACE -> gQ
    net.minecraft.sounds.SoundEvent DEEPSLATE_TILES_STEP -> gR
    net.minecraft.sounds.SoundEvent DISPENSER_DISPENSE -> gS
    net.minecraft.sounds.SoundEvent DISPENSER_FAIL -> gT
    net.minecraft.sounds.SoundEvent DISPENSER_LAUNCH -> gU
    net.minecraft.sounds.SoundEvent DOLPHIN_AMBIENT -> gV
    net.minecraft.sounds.SoundEvent DOLPHIN_AMBIENT_WATER -> gW
    net.minecraft.sounds.SoundEvent DOLPHIN_ATTACK -> gX
    net.minecraft.sounds.SoundEvent DOLPHIN_DEATH -> gY
    net.minecraft.sounds.SoundEvent DOLPHIN_EAT -> gZ
    net.minecraft.sounds.SoundEvent DOLPHIN_HURT -> ha
    net.minecraft.sounds.SoundEvent DOLPHIN_JUMP -> hb
    net.minecraft.sounds.SoundEvent DOLPHIN_PLAY -> hc
    net.minecraft.sounds.SoundEvent DOLPHIN_SPLASH -> hd
    net.minecraft.sounds.SoundEvent DOLPHIN_SWIM -> he
    net.minecraft.sounds.SoundEvent DONKEY_AMBIENT -> hf
    net.minecraft.sounds.SoundEvent DONKEY_ANGRY -> hg
    net.minecraft.sounds.SoundEvent DONKEY_CHEST -> hh
    net.minecraft.sounds.SoundEvent DONKEY_DEATH -> hi
    net.minecraft.sounds.SoundEvent DONKEY_EAT -> hj
    net.minecraft.sounds.SoundEvent DONKEY_HURT -> hk
    net.minecraft.sounds.SoundEvent DONKEY_JUMP -> hl
    net.minecraft.sounds.SoundEvent DRIPSTONE_BLOCK_BREAK -> hm
    net.minecraft.sounds.SoundEvent DRIPSTONE_BLOCK_STEP -> hn
    net.minecraft.sounds.SoundEvent DRIPSTONE_BLOCK_PLACE -> ho
    net.minecraft.sounds.SoundEvent DRIPSTONE_BLOCK_HIT -> hp
    net.minecraft.sounds.SoundEvent DRIPSTONE_BLOCK_FALL -> hq
    net.minecraft.sounds.SoundEvent POINTED_DRIPSTONE_BREAK -> hr
    net.minecraft.sounds.SoundEvent POINTED_DRIPSTONE_STEP -> hs
    net.minecraft.sounds.SoundEvent POINTED_DRIPSTONE_PLACE -> ht
    net.minecraft.sounds.SoundEvent POINTED_DRIPSTONE_HIT -> hu
    net.minecraft.sounds.SoundEvent POINTED_DRIPSTONE_FALL -> hv
    net.minecraft.sounds.SoundEvent POINTED_DRIPSTONE_LAND -> hw
    net.minecraft.sounds.SoundEvent POINTED_DRIPSTONE_DRIP_LAVA -> hx
    net.minecraft.sounds.SoundEvent POINTED_DRIPSTONE_DRIP_WATER -> hy
    net.minecraft.sounds.SoundEvent POINTED_DRIPSTONE_DRIP_LAVA_INTO_CAULDRON -> hz
    net.minecraft.sounds.SoundEvent POINTED_DRIPSTONE_DRIP_WATER_INTO_CAULDRON -> hA
    net.minecraft.sounds.SoundEvent BIG_DRIPLEAF_TILT_DOWN -> hB
    net.minecraft.sounds.SoundEvent BIG_DRIPLEAF_TILT_UP -> hC
    net.minecraft.sounds.SoundEvent DROWNED_AMBIENT -> hD
    net.minecraft.sounds.SoundEvent DROWNED_AMBIENT_WATER -> hE
    net.minecraft.sounds.SoundEvent DROWNED_DEATH -> hF
    net.minecraft.sounds.SoundEvent DROWNED_DEATH_WATER -> hG
    net.minecraft.sounds.SoundEvent DROWNED_HURT -> hH
    net.minecraft.sounds.SoundEvent DROWNED_HURT_WATER -> hI
    net.minecraft.sounds.SoundEvent DROWNED_SHOOT -> hJ
    net.minecraft.sounds.SoundEvent DROWNED_STEP -> hK
    net.minecraft.sounds.SoundEvent DROWNED_SWIM -> hL
    net.minecraft.sounds.SoundEvent DYE_USE -> hM
    net.minecraft.sounds.SoundEvent EGG_THROW -> hN
    net.minecraft.sounds.SoundEvent ELDER_GUARDIAN_AMBIENT -> hO
    net.minecraft.sounds.SoundEvent ELDER_GUARDIAN_AMBIENT_LAND -> hP
    net.minecraft.sounds.SoundEvent ELDER_GUARDIAN_CURSE -> hQ
    net.minecraft.sounds.SoundEvent ELDER_GUARDIAN_DEATH -> hR
    net.minecraft.sounds.SoundEvent ELDER_GUARDIAN_DEATH_LAND -> hS
    net.minecraft.sounds.SoundEvent ELDER_GUARDIAN_FLOP -> hT
    net.minecraft.sounds.SoundEvent ELDER_GUARDIAN_HURT -> hU
    net.minecraft.sounds.SoundEvent ELDER_GUARDIAN_HURT_LAND -> hV
    net.minecraft.sounds.SoundEvent ELYTRA_FLYING -> hW
    net.minecraft.sounds.SoundEvent ENCHANTMENT_TABLE_USE -> hX
    net.minecraft.sounds.SoundEvent ENDER_CHEST_CLOSE -> hY
    net.minecraft.sounds.SoundEvent ENDER_CHEST_OPEN -> hZ
    net.minecraft.sounds.SoundEvent ENDER_DRAGON_AMBIENT -> ia
    net.minecraft.sounds.SoundEvent ENDER_DRAGON_DEATH -> ib
    net.minecraft.sounds.SoundEvent DRAGON_FIREBALL_EXPLODE -> ic
    net.minecraft.sounds.SoundEvent ENDER_DRAGON_FLAP -> id
    net.minecraft.sounds.SoundEvent ENDER_DRAGON_GROWL -> ie
    net.minecraft.sounds.SoundEvent ENDER_DRAGON_HURT -> if
    net.minecraft.sounds.SoundEvent ENDER_DRAGON_SHOOT -> ig
    net.minecraft.sounds.SoundEvent ENDER_EYE_DEATH -> ih
    net.minecraft.sounds.SoundEvent ENDER_EYE_LAUNCH -> ii
    net.minecraft.sounds.SoundEvent ENDERMAN_AMBIENT -> ij
    net.minecraft.sounds.SoundEvent ENDERMAN_DEATH -> ik
    net.minecraft.sounds.SoundEvent ENDERMAN_HURT -> il
    net.minecraft.sounds.SoundEvent ENDERMAN_SCREAM -> im
    net.minecraft.sounds.SoundEvent ENDERMAN_STARE -> in
    net.minecraft.sounds.SoundEvent ENDERMAN_TELEPORT -> io
    net.minecraft.sounds.SoundEvent ENDERMITE_AMBIENT -> ip
    net.minecraft.sounds.SoundEvent ENDERMITE_DEATH -> iq
    net.minecraft.sounds.SoundEvent ENDERMITE_HURT -> ir
    net.minecraft.sounds.SoundEvent ENDERMITE_STEP -> is
    net.minecraft.sounds.SoundEvent ENDER_PEARL_THROW -> it
    net.minecraft.sounds.SoundEvent END_GATEWAY_SPAWN -> iu
    net.minecraft.sounds.SoundEvent END_PORTAL_FRAME_FILL -> iv
    net.minecraft.sounds.SoundEvent END_PORTAL_SPAWN -> iw
    net.minecraft.sounds.SoundEvent EVOKER_AMBIENT -> ix
    net.minecraft.sounds.SoundEvent EVOKER_CAST_SPELL -> iy
    net.minecraft.sounds.SoundEvent EVOKER_CELEBRATE -> iz
    net.minecraft.sounds.SoundEvent EVOKER_DEATH -> iA
    net.minecraft.sounds.SoundEvent EVOKER_FANGS_ATTACK -> iB
    net.minecraft.sounds.SoundEvent EVOKER_HURT -> iC
    net.minecraft.sounds.SoundEvent EVOKER_PREPARE_ATTACK -> iD
    net.minecraft.sounds.SoundEvent EVOKER_PREPARE_SUMMON -> iE
    net.minecraft.sounds.SoundEvent EVOKER_PREPARE_WOLOLO -> iF
    net.minecraft.sounds.SoundEvent EXPERIENCE_BOTTLE_THROW -> iG
    net.minecraft.sounds.SoundEvent EXPERIENCE_ORB_PICKUP -> iH
    net.minecraft.sounds.SoundEvent FENCE_GATE_CLOSE -> iI
    net.minecraft.sounds.SoundEvent FENCE_GATE_OPEN -> iJ
    net.minecraft.sounds.SoundEvent FIRECHARGE_USE -> iK
    net.minecraft.sounds.SoundEvent FIREWORK_ROCKET_BLAST -> iL
    net.minecraft.sounds.SoundEvent FIREWORK_ROCKET_BLAST_FAR -> iM
    net.minecraft.sounds.SoundEvent FIREWORK_ROCKET_LARGE_BLAST -> iN
    net.minecraft.sounds.SoundEvent FIREWORK_ROCKET_LARGE_BLAST_FAR -> iO
    net.minecraft.sounds.SoundEvent FIREWORK_ROCKET_LAUNCH -> iP
    net.minecraft.sounds.SoundEvent FIREWORK_ROCKET_SHOOT -> iQ
    net.minecraft.sounds.SoundEvent FIREWORK_ROCKET_TWINKLE -> iR
    net.minecraft.sounds.SoundEvent FIREWORK_ROCKET_TWINKLE_FAR -> iS
    net.minecraft.sounds.SoundEvent FIRE_AMBIENT -> iT
    net.minecraft.sounds.SoundEvent FIRE_EXTINGUISH -> iU
    net.minecraft.sounds.SoundEvent FISH_SWIM -> iV
    net.minecraft.sounds.SoundEvent FISHING_BOBBER_RETRIEVE -> iW
    net.minecraft.sounds.SoundEvent FISHING_BOBBER_SPLASH -> iX
    net.minecraft.sounds.SoundEvent FISHING_BOBBER_THROW -> iY
    net.minecraft.sounds.SoundEvent FLINTANDSTEEL_USE -> iZ
    net.minecraft.sounds.SoundEvent FLOWERING_AZALEA_BREAK -> ja
    net.minecraft.sounds.SoundEvent FLOWERING_AZALEA_FALL -> jb
    net.minecraft.sounds.SoundEvent FLOWERING_AZALEA_HIT -> jc
    net.minecraft.sounds.SoundEvent FLOWERING_AZALEA_PLACE -> jd
    net.minecraft.sounds.SoundEvent FLOWERING_AZALEA_STEP -> je
    net.minecraft.sounds.SoundEvent FOX_AGGRO -> jf
    net.minecraft.sounds.SoundEvent FOX_AMBIENT -> jg
    net.minecraft.sounds.SoundEvent FOX_BITE -> jh
    net.minecraft.sounds.SoundEvent FOX_DEATH -> ji
    net.minecraft.sounds.SoundEvent FOX_EAT -> jj
    net.minecraft.sounds.SoundEvent FOX_HURT -> jk
    net.minecraft.sounds.SoundEvent FOX_SCREECH -> jl
    net.minecraft.sounds.SoundEvent FOX_SLEEP -> jm
    net.minecraft.sounds.SoundEvent FOX_SNIFF -> jn
    net.minecraft.sounds.SoundEvent FOX_SPIT -> jo
    net.minecraft.sounds.SoundEvent FOX_TELEPORT -> jp
    net.minecraft.sounds.SoundEvent SUSPICIOUS_SAND_BREAK -> jq
    net.minecraft.sounds.SoundEvent SUSPICIOUS_SAND_STEP -> jr
    net.minecraft.sounds.SoundEvent SUSPICIOUS_SAND_PLACE -> js
    net.minecraft.sounds.SoundEvent SUSPICIOUS_SAND_HIT -> jt
    net.minecraft.sounds.SoundEvent SUSPICIOUS_SAND_FALL -> ju
    net.minecraft.sounds.SoundEvent SUSPICIOUS_GRAVEL_BREAK -> jv
    net.minecraft.sounds.SoundEvent SUSPICIOUS_GRAVEL_STEP -> jw
    net.minecraft.sounds.SoundEvent SUSPICIOUS_GRAVEL_PLACE -> jx
    net.minecraft.sounds.SoundEvent SUSPICIOUS_GRAVEL_HIT -> jy
    net.minecraft.sounds.SoundEvent SUSPICIOUS_GRAVEL_FALL -> jz
    net.minecraft.sounds.SoundEvent FROGLIGHT_BREAK -> jA
    net.minecraft.sounds.SoundEvent FROGLIGHT_FALL -> jB
    net.minecraft.sounds.SoundEvent FROGLIGHT_HIT -> jC
    net.minecraft.sounds.SoundEvent FROGLIGHT_PLACE -> jD
    net.minecraft.sounds.SoundEvent FROGLIGHT_STEP -> jE
    net.minecraft.sounds.SoundEvent FROGSPAWNSTEP -> jF
    net.minecraft.sounds.SoundEvent FROGSPAWN_BREAK -> jG
    net.minecraft.sounds.SoundEvent FROGSPAWN_FALL -> jH
    net.minecraft.sounds.SoundEvent FROGSPAWN_HATCH -> jI
    net.minecraft.sounds.SoundEvent FROGSPAWN_HIT -> jJ
    net.minecraft.sounds.SoundEvent FROGSPAWN_PLACE -> jK
    net.minecraft.sounds.SoundEvent FROG_AMBIENT -> jL
    net.minecraft.sounds.SoundEvent FROG_DEATH -> jM
    net.minecraft.sounds.SoundEvent FROG_EAT -> jN
    net.minecraft.sounds.SoundEvent FROG_HURT -> jO
    net.minecraft.sounds.SoundEvent FROG_LAY_SPAWN -> jP
    net.minecraft.sounds.SoundEvent FROG_LONG_JUMP -> jQ
    net.minecraft.sounds.SoundEvent FROG_STEP -> jR
    net.minecraft.sounds.SoundEvent FROG_TONGUE -> jS
    net.minecraft.sounds.SoundEvent ROOTS_BREAK -> jT
    net.minecraft.sounds.SoundEvent ROOTS_STEP -> jU
    net.minecraft.sounds.SoundEvent ROOTS_PLACE -> jV
    net.minecraft.sounds.SoundEvent ROOTS_HIT -> jW
    net.minecraft.sounds.SoundEvent ROOTS_FALL -> jX
    net.minecraft.sounds.SoundEvent FURNACE_FIRE_CRACKLE -> jY
    net.minecraft.sounds.SoundEvent GENERIC_BIG_FALL -> jZ
    net.minecraft.sounds.SoundEvent GENERIC_BURN -> ka
    net.minecraft.sounds.SoundEvent GENERIC_DEATH -> kb
    net.minecraft.sounds.SoundEvent GENERIC_DRINK -> kc
    net.minecraft.sounds.SoundEvent GENERIC_EAT -> kd
    net.minecraft.core.Holder$Reference GENERIC_EXPLODE -> ke
    net.minecraft.sounds.SoundEvent GENERIC_EXTINGUISH_FIRE -> kf
    net.minecraft.sounds.SoundEvent GENERIC_HURT -> kg
    net.minecraft.sounds.SoundEvent GENERIC_SMALL_FALL -> kh
    net.minecraft.sounds.SoundEvent GENERIC_SPLASH -> ki
    net.minecraft.sounds.SoundEvent GENERIC_SWIM -> kj
    net.minecraft.sounds.SoundEvent GHAST_AMBIENT -> kk
    net.minecraft.sounds.SoundEvent GHAST_DEATH -> kl
    net.minecraft.sounds.SoundEvent GHAST_HURT -> km
    net.minecraft.sounds.SoundEvent GHAST_SCREAM -> kn
    net.minecraft.sounds.SoundEvent GHAST_SHOOT -> ko
    net.minecraft.sounds.SoundEvent GHAST_WARN -> kp
    net.minecraft.sounds.SoundEvent GILDED_BLACKSTONE_BREAK -> kq
    net.minecraft.sounds.SoundEvent GILDED_BLACKSTONE_FALL -> kr
    net.minecraft.sounds.SoundEvent GILDED_BLACKSTONE_HIT -> ks
    net.minecraft.sounds.SoundEvent GILDED_BLACKSTONE_PLACE -> kt
    net.minecraft.sounds.SoundEvent GILDED_BLACKSTONE_STEP -> ku
    net.minecraft.sounds.SoundEvent GLASS_BREAK -> kv
    net.minecraft.sounds.SoundEvent GLASS_FALL -> kw
    net.minecraft.sounds.SoundEvent GLASS_HIT -> kx
    net.minecraft.sounds.SoundEvent GLASS_PLACE -> ky
    net.minecraft.sounds.SoundEvent GLASS_STEP -> kz
    net.minecraft.sounds.SoundEvent GLOW_INK_SAC_USE -> kA
    net.minecraft.sounds.SoundEvent GLOW_ITEM_FRAME_ADD_ITEM -> kB
    net.minecraft.sounds.SoundEvent GLOW_ITEM_FRAME_BREAK -> kC
    net.minecraft.sounds.SoundEvent GLOW_ITEM_FRAME_PLACE -> kD
    net.minecraft.sounds.SoundEvent GLOW_ITEM_FRAME_REMOVE_ITEM -> kE
    net.minecraft.sounds.SoundEvent GLOW_ITEM_FRAME_ROTATE_ITEM -> kF
    net.minecraft.sounds.SoundEvent GLOW_SQUID_AMBIENT -> kG
    net.minecraft.sounds.SoundEvent GLOW_SQUID_DEATH -> kH
    net.minecraft.sounds.SoundEvent GLOW_SQUID_HURT -> kI
    net.minecraft.sounds.SoundEvent GLOW_SQUID_SQUIRT -> kJ
    net.minecraft.sounds.SoundEvent GOAT_AMBIENT -> kK
    net.minecraft.sounds.SoundEvent GOAT_DEATH -> kL
    net.minecraft.sounds.SoundEvent GOAT_EAT -> kM
    net.minecraft.sounds.SoundEvent GOAT_HURT -> kN
    net.minecraft.sounds.SoundEvent GOAT_LONG_JUMP -> kO
    net.minecraft.sounds.SoundEvent GOAT_MILK -> kP
    net.minecraft.sounds.SoundEvent GOAT_PREPARE_RAM -> kQ
    net.minecraft.sounds.SoundEvent GOAT_RAM_IMPACT -> kR
    net.minecraft.sounds.SoundEvent GOAT_HORN_BREAK -> kS
    net.minecraft.sounds.SoundEvent GOAT_HORN_PLAY -> kT
    net.minecraft.sounds.SoundEvent GOAT_SCREAMING_AMBIENT -> kU
    net.minecraft.sounds.SoundEvent GOAT_SCREAMING_DEATH -> kV
    net.minecraft.sounds.SoundEvent GOAT_SCREAMING_EAT -> kW
    net.minecraft.sounds.SoundEvent GOAT_SCREAMING_HURT -> kX
    net.minecraft.sounds.SoundEvent GOAT_SCREAMING_LONG_JUMP -> kY
    net.minecraft.sounds.SoundEvent GOAT_SCREAMING_MILK -> kZ
    net.minecraft.sounds.SoundEvent GOAT_SCREAMING_PREPARE_RAM -> la
    net.minecraft.sounds.SoundEvent GOAT_SCREAMING_RAM_IMPACT -> lb
    net.minecraft.sounds.SoundEvent GOAT_SCREAMING_HORN_BREAK -> lc
    net.minecraft.sounds.SoundEvent GOAT_STEP -> ld
    net.minecraft.sounds.SoundEvent GRASS_BREAK -> le
    net.minecraft.sounds.SoundEvent GRASS_FALL -> lf
    net.minecraft.sounds.SoundEvent GRASS_HIT -> lg
    net.minecraft.sounds.SoundEvent GRASS_PLACE -> lh
    net.minecraft.sounds.SoundEvent GRASS_STEP -> li
    net.minecraft.sounds.SoundEvent GRAVEL_BREAK -> lj
    net.minecraft.sounds.SoundEvent GRAVEL_FALL -> lk
    net.minecraft.sounds.SoundEvent GRAVEL_HIT -> ll
    net.minecraft.sounds.SoundEvent GRAVEL_PLACE -> lm
    net.minecraft.sounds.SoundEvent GRAVEL_STEP -> ln
    net.minecraft.sounds.SoundEvent GRINDSTONE_USE -> lo
    net.minecraft.sounds.SoundEvent GROWING_PLANT_CROP -> lp
    net.minecraft.sounds.SoundEvent GUARDIAN_AMBIENT -> lq
    net.minecraft.sounds.SoundEvent GUARDIAN_AMBIENT_LAND -> lr
    net.minecraft.sounds.SoundEvent GUARDIAN_ATTACK -> ls
    net.minecraft.sounds.SoundEvent GUARDIAN_DEATH -> lt
    net.minecraft.sounds.SoundEvent GUARDIAN_DEATH_LAND -> lu
    net.minecraft.sounds.SoundEvent GUARDIAN_FLOP -> lv
    net.minecraft.sounds.SoundEvent GUARDIAN_HURT -> lw
    net.minecraft.sounds.SoundEvent GUARDIAN_HURT_LAND -> lx
    net.minecraft.sounds.SoundEvent HANGING_ROOTS_BREAK -> ly
    net.minecraft.sounds.SoundEvent HANGING_ROOTS_FALL -> lz
    net.minecraft.sounds.SoundEvent HANGING_ROOTS_HIT -> lA
    net.minecraft.sounds.SoundEvent HANGING_ROOTS_PLACE -> lB
    net.minecraft.sounds.SoundEvent HANGING_ROOTS_STEP -> lC
    net.minecraft.sounds.SoundEvent HANGING_SIGN_STEP -> lD
    net.minecraft.sounds.SoundEvent HANGING_SIGN_BREAK -> lE
    net.minecraft.sounds.SoundEvent HANGING_SIGN_FALL -> lF
    net.minecraft.sounds.SoundEvent HANGING_SIGN_HIT -> lG
    net.minecraft.sounds.SoundEvent HANGING_SIGN_PLACE -> lH
    net.minecraft.sounds.SoundEvent HEAVY_CORE_BREAK -> lI
    net.minecraft.sounds.SoundEvent HEAVY_CORE_FALL -> lJ
    net.minecraft.sounds.SoundEvent HEAVY_CORE_HIT -> lK
    net.minecraft.sounds.SoundEvent HEAVY_CORE_PLACE -> lL
    net.minecraft.sounds.SoundEvent HEAVY_CORE_STEP -> lM
    net.minecraft.sounds.SoundEvent NETHER_WOOD_HANGING_SIGN_STEP -> lN
    net.minecraft.sounds.SoundEvent NETHER_WOOD_HANGING_SIGN_BREAK -> lO
    net.minecraft.sounds.SoundEvent NETHER_WOOD_HANGING_SIGN_FALL -> lP
    net.minecraft.sounds.SoundEvent NETHER_WOOD_HANGING_SIGN_HIT -> lQ
    net.minecraft.sounds.SoundEvent NETHER_WOOD_HANGING_SIGN_PLACE -> lR
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_HANGING_SIGN_STEP -> lS
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_HANGING_SIGN_BREAK -> lT
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_HANGING_SIGN_FALL -> lU
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_HANGING_SIGN_HIT -> lV
    net.minecraft.sounds.SoundEvent BAMBOO_WOOD_HANGING_SIGN_PLACE -> lW
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_BREAK -> lX
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_STEP -> lY
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_PLACE -> lZ
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_HIT -> ma
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_FALL -> mb
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_SPAWN_MOB -> mc
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_ABOUT_TO_SPAWN_ITEM -> md
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_SPAWN_ITEM -> me
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_SPAWN_ITEM_BEGIN -> mf
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_DETECT_PLAYER -> mg
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_OMINOUS_ACTIVATE -> mh
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_AMBIENT -> mi
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_AMBIENT_OMINOUS -> mj
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_OPEN_SHUTTER -> mk
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_CLOSE_SHUTTER -> ml
    net.minecraft.sounds.SoundEvent TRIAL_SPAWNER_EJECT_ITEM -> mm
    net.minecraft.sounds.SoundEvent HOE_TILL -> mn
    net.minecraft.sounds.SoundEvent HOGLIN_AMBIENT -> mo
    net.minecraft.sounds.SoundEvent HOGLIN_ANGRY -> mp
    net.minecraft.sounds.SoundEvent HOGLIN_ATTACK -> mq
    net.minecraft.sounds.SoundEvent HOGLIN_CONVERTED_TO_ZOMBIFIED -> mr
    net.minecraft.sounds.SoundEvent HOGLIN_DEATH -> ms
    net.minecraft.sounds.SoundEvent HOGLIN_HURT -> mt
    net.minecraft.sounds.SoundEvent HOGLIN_RETREAT -> mu
    net.minecraft.sounds.SoundEvent HOGLIN_STEP -> mv
    net.minecraft.sounds.SoundEvent HONEY_BLOCK_BREAK -> mw
    net.minecraft.sounds.SoundEvent HONEY_BLOCK_FALL -> mx
    net.minecraft.sounds.SoundEvent HONEY_BLOCK_HIT -> my
    net.minecraft.sounds.SoundEvent HONEY_BLOCK_PLACE -> mz
    net.minecraft.sounds.SoundEvent HONEY_BLOCK_SLIDE -> mA
    net.minecraft.sounds.SoundEvent HONEY_BLOCK_STEP -> mB
    net.minecraft.sounds.SoundEvent HONEYCOMB_WAX_ON -> mC
    net.minecraft.sounds.SoundEvent HONEY_DRINK -> mD
    int GOAT_HORN_VARIANT_COUNT -> mE
    com.google.common.collect.ImmutableList GOAT_HORN_SOUND_VARIANTS -> mF
    net.minecraft.sounds.SoundEvent HORSE_AMBIENT -> mG
    net.minecraft.sounds.SoundEvent HORSE_ANGRY -> mH
    net.minecraft.sounds.SoundEvent HORSE_ARMOR -> mI
    net.minecraft.sounds.SoundEvent HORSE_BREATHE -> mJ
    net.minecraft.sounds.SoundEvent HORSE_DEATH -> mK
    net.minecraft.sounds.SoundEvent HORSE_EAT -> mL
    net.minecraft.sounds.SoundEvent HORSE_GALLOP -> mM
    net.minecraft.sounds.SoundEvent HORSE_HURT -> mN
    net.minecraft.sounds.SoundEvent HORSE_JUMP -> mO
    net.minecraft.sounds.SoundEvent HORSE_LAND -> mP
    net.minecraft.sounds.SoundEvent HORSE_SADDLE -> mQ
    net.minecraft.sounds.SoundEvent HORSE_STEP -> mR
    net.minecraft.sounds.SoundEvent HORSE_STEP_WOOD -> mS
    net.minecraft.sounds.SoundEvent HOSTILE_BIG_FALL -> mT
    net.minecraft.sounds.SoundEvent HOSTILE_DEATH -> mU
    net.minecraft.sounds.SoundEvent HOSTILE_HURT -> mV
    net.minecraft.sounds.SoundEvent HOSTILE_SMALL_FALL -> mW
    net.minecraft.sounds.SoundEvent HOSTILE_SPLASH -> mX
    net.minecraft.sounds.SoundEvent HOSTILE_SWIM -> mY
    net.minecraft.sounds.SoundEvent HUSK_AMBIENT -> mZ
    net.minecraft.sounds.SoundEvent HUSK_CONVERTED_TO_ZOMBIE -> na
    net.minecraft.sounds.SoundEvent HUSK_DEATH -> nb
    net.minecraft.sounds.SoundEvent HUSK_HURT -> nc
    net.minecraft.sounds.SoundEvent HUSK_STEP -> nd
    net.minecraft.sounds.SoundEvent ILLUSIONER_AMBIENT -> ne
    net.minecraft.sounds.SoundEvent ILLUSIONER_CAST_SPELL -> nf
    net.minecraft.sounds.SoundEvent ILLUSIONER_DEATH -> ng
    net.minecraft.sounds.SoundEvent ILLUSIONER_HURT -> nh
    net.minecraft.sounds.SoundEvent ILLUSIONER_MIRROR_MOVE -> ni
    net.minecraft.sounds.SoundEvent ILLUSIONER_PREPARE_BLINDNESS -> nj
    net.minecraft.sounds.SoundEvent ILLUSIONER_PREPARE_MIRROR -> nk
    net.minecraft.sounds.SoundEvent INK_SAC_USE -> nl
    net.minecraft.sounds.SoundEvent IRON_DOOR_CLOSE -> nm
    net.minecraft.sounds.SoundEvent IRON_DOOR_OPEN -> nn
    net.minecraft.sounds.SoundEvent IRON_GOLEM_ATTACK -> no
    net.minecraft.sounds.SoundEvent IRON_GOLEM_DAMAGE -> np
    net.minecraft.sounds.SoundEvent IRON_GOLEM_DEATH -> nq
    net.minecraft.sounds.SoundEvent IRON_GOLEM_HURT -> nr
    net.minecraft.sounds.SoundEvent IRON_GOLEM_REPAIR -> ns
    net.minecraft.sounds.SoundEvent IRON_GOLEM_STEP -> nt
    net.minecraft.sounds.SoundEvent IRON_TRAPDOOR_CLOSE -> nu
    net.minecraft.sounds.SoundEvent IRON_TRAPDOOR_OPEN -> nv
    net.minecraft.sounds.SoundEvent ITEM_FRAME_ADD_ITEM -> nw
    net.minecraft.sounds.SoundEvent ITEM_FRAME_BREAK -> nx
    net.minecraft.sounds.SoundEvent ITEM_FRAME_PLACE -> ny
    net.minecraft.sounds.SoundEvent ITEM_FRAME_REMOVE_ITEM -> nz
    net.minecraft.sounds.SoundEvent ITEM_FRAME_ROTATE_ITEM -> nA
    net.minecraft.sounds.SoundEvent ITEM_BREAK -> nB
    net.minecraft.sounds.SoundEvent ITEM_PICKUP -> nC
    net.minecraft.sounds.SoundEvent LADDER_BREAK -> nD
    net.minecraft.sounds.SoundEvent LADDER_FALL -> nE
    net.minecraft.sounds.SoundEvent LADDER_HIT -> nF
    net.minecraft.sounds.SoundEvent LADDER_PLACE -> nG
    net.minecraft.sounds.SoundEvent LADDER_STEP -> nH
    net.minecraft.sounds.SoundEvent LANTERN_BREAK -> nI
    net.minecraft.sounds.SoundEvent LANTERN_FALL -> nJ
    net.minecraft.sounds.SoundEvent LANTERN_HIT -> nK
    net.minecraft.sounds.SoundEvent LANTERN_PLACE -> nL
    net.minecraft.sounds.SoundEvent LANTERN_STEP -> nM
    net.minecraft.sounds.SoundEvent LARGE_AMETHYST_BUD_BREAK -> nN
    net.minecraft.sounds.SoundEvent LARGE_AMETHYST_BUD_PLACE -> nO
    net.minecraft.sounds.SoundEvent LAVA_AMBIENT -> nP
    net.minecraft.sounds.SoundEvent LAVA_EXTINGUISH -> nQ
    net.minecraft.sounds.SoundEvent LAVA_POP -> nR
    net.minecraft.sounds.SoundEvent LEASH_KNOT_BREAK -> nS
    net.minecraft.sounds.SoundEvent LEASH_KNOT_PLACE -> nT
    net.minecraft.sounds.SoundEvent LEVER_CLICK -> nU
    net.minecraft.sounds.SoundEvent LIGHTNING_BOLT_IMPACT -> nV
    net.minecraft.sounds.SoundEvent LIGHTNING_BOLT_THUNDER -> nW
    net.minecraft.sounds.SoundEvent LINGERING_POTION_THROW -> nX
    net.minecraft.sounds.SoundEvent LLAMA_AMBIENT -> nY
    net.minecraft.sounds.SoundEvent LLAMA_ANGRY -> nZ
    net.minecraft.sounds.SoundEvent LLAMA_CHEST -> oa
    net.minecraft.sounds.SoundEvent LLAMA_DEATH -> ob
    net.minecraft.sounds.SoundEvent LLAMA_EAT -> oc
    net.minecraft.sounds.SoundEvent LLAMA_HURT -> od
    net.minecraft.sounds.SoundEvent LLAMA_SPIT -> oe
    net.minecraft.sounds.SoundEvent LLAMA_STEP -> of
    net.minecraft.core.Holder LLAMA_SWAG -> og
    net.minecraft.sounds.SoundEvent MAGMA_CUBE_DEATH_SMALL -> oh
    net.minecraft.sounds.SoundEvent LODESTONE_BREAK -> oi
    net.minecraft.sounds.SoundEvent LODESTONE_STEP -> oj
    net.minecraft.sounds.SoundEvent LODESTONE_PLACE -> ok
    net.minecraft.sounds.SoundEvent LODESTONE_HIT -> ol
    net.minecraft.sounds.SoundEvent LODESTONE_FALL -> om
    net.minecraft.sounds.SoundEvent LODESTONE_COMPASS_LOCK -> on
    net.minecraft.sounds.SoundEvent MACE_SMASH_AIR -> oo
    net.minecraft.sounds.SoundEvent MACE_SMASH_GROUND -> op
    net.minecraft.sounds.SoundEvent MACE_SMASH_GROUND_HEAVY -> oq
    net.minecraft.sounds.SoundEvent MAGMA_CUBE_DEATH -> or
    net.minecraft.sounds.SoundEvent MAGMA_CUBE_HURT -> os
    net.minecraft.sounds.SoundEvent MAGMA_CUBE_HURT_SMALL -> ot
    net.minecraft.sounds.SoundEvent MAGMA_CUBE_JUMP -> ou
    net.minecraft.sounds.SoundEvent MAGMA_CUBE_SQUISH -> ov
    net.minecraft.sounds.SoundEvent MAGMA_CUBE_SQUISH_SMALL -> ow
    net.minecraft.sounds.SoundEvent MANGROVE_ROOTS_BREAK -> ox
    net.minecraft.sounds.SoundEvent MANGROVE_ROOTS_FALL -> oy
    net.minecraft.sounds.SoundEvent MANGROVE_ROOTS_HIT -> oz
    net.minecraft.sounds.SoundEvent MANGROVE_ROOTS_PLACE -> oA
    net.minecraft.sounds.SoundEvent MANGROVE_ROOTS_STEP -> oB
    net.minecraft.sounds.SoundEvent MEDIUM_AMETHYST_BUD_BREAK -> oC
    net.minecraft.sounds.SoundEvent MEDIUM_AMETHYST_BUD_PLACE -> oD
    net.minecraft.sounds.SoundEvent METAL_BREAK -> oE
    net.minecraft.sounds.SoundEvent METAL_FALL -> oF
    net.minecraft.sounds.SoundEvent METAL_HIT -> oG
    net.minecraft.sounds.SoundEvent METAL_PLACE -> oH
    net.minecraft.sounds.SoundEvent METAL_PRESSURE_PLATE_CLICK_OFF -> oI
    net.minecraft.sounds.SoundEvent METAL_PRESSURE_PLATE_CLICK_ON -> oJ
    net.minecraft.sounds.SoundEvent METAL_STEP -> oK
    net.minecraft.sounds.SoundEvent MINECART_INSIDE_UNDERWATER -> oL
    net.minecraft.sounds.SoundEvent MINECART_INSIDE -> oM
    net.minecraft.sounds.SoundEvent MINECART_RIDING -> oN
    net.minecraft.sounds.SoundEvent MOOSHROOM_CONVERT -> oO
    net.minecraft.sounds.SoundEvent MOOSHROOM_EAT -> oP
    net.minecraft.sounds.SoundEvent MOOSHROOM_MILK -> oQ
    net.minecraft.sounds.SoundEvent MOOSHROOM_MILK_SUSPICIOUSLY -> oR
    net.minecraft.sounds.SoundEvent MOOSHROOM_SHEAR -> oS
    net.minecraft.sounds.SoundEvent MOSS_CARPET_BREAK -> oT
    net.minecraft.sounds.SoundEvent MOSS_CARPET_FALL -> oU
    net.minecraft.sounds.SoundEvent MOSS_CARPET_HIT -> oV
    net.minecraft.sounds.SoundEvent MOSS_CARPET_PLACE -> oW
    net.minecraft.sounds.SoundEvent MOSS_CARPET_STEP -> oX
    net.minecraft.sounds.SoundEvent PINK_PETALS_BREAK -> oY
    net.minecraft.sounds.SoundEvent PINK_PETALS_FALL -> oZ
    net.minecraft.sounds.SoundEvent PINK_PETALS_HIT -> pa
    net.minecraft.sounds.SoundEvent PINK_PETALS_PLACE -> pb
    net.minecraft.sounds.SoundEvent PINK_PETALS_STEP -> pc
    net.minecraft.sounds.SoundEvent MOSS_BREAK -> pd
    net.minecraft.sounds.SoundEvent MOSS_FALL -> pe
    net.minecraft.sounds.SoundEvent MOSS_HIT -> pf
    net.minecraft.sounds.SoundEvent MOSS_PLACE -> pg
    net.minecraft.sounds.SoundEvent MOSS_STEP -> ph
    net.minecraft.sounds.SoundEvent MUD_BREAK -> pi
    net.minecraft.sounds.SoundEvent MUD_FALL -> pj
    net.minecraft.sounds.SoundEvent MUD_HIT -> pk
    net.minecraft.sounds.SoundEvent MUD_PLACE -> pl
    net.minecraft.sounds.SoundEvent MUD_STEP -> pm
    net.minecraft.sounds.SoundEvent MUD_BRICKS_BREAK -> pn
    net.minecraft.sounds.SoundEvent MUD_BRICKS_FALL -> po
    net.minecraft.sounds.SoundEvent MUD_BRICKS_HIT -> pp
    net.minecraft.sounds.SoundEvent MUD_BRICKS_PLACE -> pq
    net.minecraft.sounds.SoundEvent MUD_BRICKS_STEP -> pr
    net.minecraft.sounds.SoundEvent MUDDY_MANGROVE_ROOTS_BREAK -> ps
    net.minecraft.sounds.SoundEvent MUDDY_MANGROVE_ROOTS_FALL -> pt
    net.minecraft.sounds.SoundEvent MUDDY_MANGROVE_ROOTS_HIT -> pu
    net.minecraft.sounds.SoundEvent MUDDY_MANGROVE_ROOTS_PLACE -> pv
    net.minecraft.sounds.SoundEvent MUDDY_MANGROVE_ROOTS_STEP -> pw
    net.minecraft.sounds.SoundEvent MULE_AMBIENT -> px
    net.minecraft.sounds.SoundEvent MULE_ANGRY -> py
    net.minecraft.sounds.SoundEvent MULE_CHEST -> pz
    net.minecraft.sounds.SoundEvent MULE_DEATH -> pA
    net.minecraft.sounds.SoundEvent MULE_EAT -> pB
    net.minecraft.sounds.SoundEvent MULE_HURT -> pC
    net.minecraft.sounds.SoundEvent MULE_JUMP -> pD
    net.minecraft.core.Holder$Reference MUSIC_CREATIVE -> pE
    net.minecraft.core.Holder$Reference MUSIC_CREDITS -> pF
    net.minecraft.core.Holder$Reference MUSIC_DISC_5 -> pG
    net.minecraft.core.Holder$Reference MUSIC_DISC_11 -> pH
    net.minecraft.core.Holder$Reference MUSIC_DISC_13 -> pI
    net.minecraft.core.Holder$Reference MUSIC_DISC_BLOCKS -> pJ
    net.minecraft.core.Holder$Reference MUSIC_DISC_CAT -> pK
    net.minecraft.core.Holder$Reference MUSIC_DISC_CHIRP -> pL
    net.minecraft.core.Holder$Reference MUSIC_DISC_FAR -> pM
    net.minecraft.core.Holder$Reference MUSIC_DISC_MALL -> pN
    net.minecraft.core.Holder$Reference MUSIC_DISC_MELLOHI -> pO
    net.minecraft.core.Holder$Reference MUSIC_DISC_PIGSTEP -> pP
    net.minecraft.core.Holder$Reference MUSIC_DISC_STAL -> pQ
    net.minecraft.core.Holder$Reference MUSIC_DISC_STRAD -> pR
    net.minecraft.core.Holder$Reference MUSIC_DISC_WAIT -> pS
    net.minecraft.core.Holder$Reference MUSIC_DISC_WARD -> pT
    net.minecraft.core.Holder$Reference MUSIC_DISC_OTHERSIDE -> pU
    net.minecraft.core.Holder$Reference MUSIC_DISC_RELIC -> pV
    net.minecraft.core.Holder$Reference MUSIC_DISC_CREATOR -> pW
    net.minecraft.core.Holder$Reference MUSIC_DISC_CREATOR_MUSIC_BOX -> pX
    net.minecraft.core.Holder$Reference MUSIC_DISC_PRECIPICE -> pY
    net.minecraft.core.Holder$Reference MUSIC_DRAGON -> pZ
    net.minecraft.core.Holder$Reference MUSIC_END -> qa
    net.minecraft.core.Holder$Reference MUSIC_GAME -> qb
    net.minecraft.core.Holder$Reference MUSIC_MENU -> qc
    net.minecraft.core.Holder$Reference MUSIC_BIOME_BASALT_DELTAS -> qd
    net.minecraft.core.Holder$Reference MUSIC_BIOME_CRIMSON_FOREST -> qe
    net.minecraft.core.Holder$Reference MUSIC_BIOME_DEEP_DARK -> qf
    net.minecraft.core.Holder$Reference MUSIC_BIOME_DRIPSTONE_CAVES -> qg
    net.minecraft.core.Holder$Reference MUSIC_BIOME_GROVE -> qh
    net.minecraft.core.Holder$Reference MUSIC_BIOME_JAGGED_PEAKS -> qi
    net.minecraft.core.Holder$Reference MUSIC_BIOME_LUSH_CAVES -> qj
    net.minecraft.core.Holder$Reference MUSIC_BIOME_SWAMP -> qk
    net.minecraft.core.Holder$Reference MUSIC_BIOME_FOREST -> ql
    net.minecraft.core.Holder$Reference MUSIC_BIOME_OLD_GROWTH_TAIGA -> qm
    net.minecraft.core.Holder$Reference MUSIC_BIOME_MEADOW -> qn
    net.minecraft.core.Holder$Reference MUSIC_BIOME_CHERRY_GROVE -> qo
    net.minecraft.core.Holder$Reference MUSIC_BIOME_NETHER_WASTES -> qp
    net.minecraft.core.Holder$Reference MUSIC_BIOME_FROZEN_PEAKS -> qq
    net.minecraft.core.Holder$Reference MUSIC_BIOME_SNOWY_SLOPES -> qr
    net.minecraft.core.Holder$Reference MUSIC_BIOME_SOUL_SAND_VALLEY -> qs
    net.minecraft.core.Holder$Reference MUSIC_BIOME_STONY_PEAKS -> qt
    net.minecraft.core.Holder$Reference MUSIC_BIOME_WARPED_FOREST -> qu
    net.minecraft.core.Holder$Reference MUSIC_BIOME_FLOWER_FOREST -> qv
    net.minecraft.core.Holder$Reference MUSIC_BIOME_DESERT -> qw
    net.minecraft.core.Holder$Reference MUSIC_BIOME_BADLANDS -> qx
    net.minecraft.core.Holder$Reference MUSIC_BIOME_JUNGLE -> qy
    net.minecraft.core.Holder$Reference MUSIC_BIOME_SPARSE_JUNGLE -> qz
    net.minecraft.core.Holder$Reference MUSIC_BIOME_BAMBOO_JUNGLE -> qA
    net.minecraft.core.Holder$Reference MUSIC_UNDER_WATER -> qB
    net.minecraft.sounds.SoundEvent NETHER_BRICKS_BREAK -> qC
    net.minecraft.sounds.SoundEvent NETHER_BRICKS_STEP -> qD
    net.minecraft.sounds.SoundEvent NETHER_BRICKS_PLACE -> qE
    net.minecraft.sounds.SoundEvent NETHER_BRICKS_HIT -> qF
    net.minecraft.sounds.SoundEvent NETHER_BRICKS_FALL -> qG
    net.minecraft.sounds.SoundEvent NETHER_WART_BREAK -> qH
    net.minecraft.sounds.SoundEvent NETHER_WART_PLANTED -> qI
    net.minecraft.sounds.SoundEvent NETHER_WOOD_BREAK -> qJ
    net.minecraft.sounds.SoundEvent NETHER_WOOD_FALL -> qK
    net.minecraft.sounds.SoundEvent NETHER_WOOD_HIT -> qL
    net.minecraft.sounds.SoundEvent NETHER_WOOD_PLACE -> qM
    net.minecraft.sounds.SoundEvent NETHER_WOOD_STEP -> qN
    net.minecraft.sounds.SoundEvent NETHER_WOOD_DOOR_CLOSE -> qO
    net.minecraft.sounds.SoundEvent NETHER_WOOD_DOOR_OPEN -> qP
    net.minecraft.sounds.SoundEvent NETHER_WOOD_TRAPDOOR_CLOSE -> qQ
    net.minecraft.sounds.SoundEvent NETHER_WOOD_TRAPDOOR_OPEN -> qR
    net.minecraft.sounds.SoundEvent NETHER_WOOD_BUTTON_CLICK_OFF -> qS
    net.minecraft.sounds.SoundEvent NETHER_WOOD_BUTTON_CLICK_ON -> qT
    net.minecraft.sounds.SoundEvent NETHER_WOOD_PRESSURE_PLATE_CLICK_OFF -> qU
    net.minecraft.sounds.SoundEvent NETHER_WOOD_PRESSURE_PLATE_CLICK_ON -> qV
    net.minecraft.sounds.SoundEvent NETHER_WOOD_FENCE_GATE_CLOSE -> qW
    net.minecraft.sounds.SoundEvent NETHER_WOOD_FENCE_GATE_OPEN -> qX
    net.minecraft.sounds.SoundEvent EMPTY -> qY
    net.minecraft.sounds.SoundEvent PACKED_MUD_BREAK -> qZ
    net.minecraft.sounds.SoundEvent PACKED_MUD_FALL -> ra
    net.minecraft.sounds.SoundEvent PACKED_MUD_HIT -> rb
    net.minecraft.sounds.SoundEvent PACKED_MUD_PLACE -> rc
    net.minecraft.sounds.SoundEvent PACKED_MUD_STEP -> rd
    net.minecraft.sounds.SoundEvent STEM_BREAK -> re
    net.minecraft.sounds.SoundEvent STEM_STEP -> rf
    net.minecraft.sounds.SoundEvent STEM_PLACE -> rg
    net.minecraft.sounds.SoundEvent STEM_HIT -> rh
    net.minecraft.sounds.SoundEvent STEM_FALL -> ri
    net.minecraft.sounds.SoundEvent NYLIUM_BREAK -> rj
    net.minecraft.sounds.SoundEvent NYLIUM_STEP -> rk
    net.minecraft.sounds.SoundEvent NYLIUM_PLACE -> rl
    net.minecraft.sounds.SoundEvent NYLIUM_HIT -> rm
    net.minecraft.sounds.SoundEvent NYLIUM_FALL -> rn
    net.minecraft.sounds.SoundEvent NETHER_SPROUTS_BREAK -> ro
    net.minecraft.sounds.SoundEvent NETHER_SPROUTS_STEP -> rp
    net.minecraft.sounds.SoundEvent NETHER_SPROUTS_PLACE -> rq
    net.minecraft.sounds.SoundEvent NETHER_SPROUTS_HIT -> rr
    net.minecraft.sounds.SoundEvent NETHER_SPROUTS_FALL -> rs
    net.minecraft.sounds.SoundEvent FUNGUS_BREAK -> rt
    net.minecraft.sounds.SoundEvent FUNGUS_STEP -> ru
    net.minecraft.sounds.SoundEvent FUNGUS_PLACE -> rv
    net.minecraft.sounds.SoundEvent FUNGUS_HIT -> rw
    net.minecraft.sounds.SoundEvent FUNGUS_FALL -> rx
    net.minecraft.sounds.SoundEvent WEEPING_VINES_BREAK -> ry
    net.minecraft.sounds.SoundEvent WEEPING_VINES_STEP -> rz
    net.minecraft.sounds.SoundEvent WEEPING_VINES_PLACE -> rA
    net.minecraft.sounds.SoundEvent WEEPING_VINES_HIT -> rB
    net.minecraft.sounds.SoundEvent WEEPING_VINES_FALL -> rC
    net.minecraft.sounds.SoundEvent WART_BLOCK_BREAK -> rD
    net.minecraft.sounds.SoundEvent WART_BLOCK_STEP -> rE
    net.minecraft.sounds.SoundEvent WART_BLOCK_PLACE -> rF
    net.minecraft.sounds.SoundEvent WART_BLOCK_HIT -> rG
    net.minecraft.sounds.SoundEvent WART_BLOCK_FALL -> rH
    net.minecraft.sounds.SoundEvent NETHERITE_BLOCK_BREAK -> rI
    net.minecraft.sounds.SoundEvent NETHERITE_BLOCK_STEP -> rJ
    net.minecraft.sounds.SoundEvent NETHERITE_BLOCK_PLACE -> rK
    net.minecraft.sounds.SoundEvent NETHERITE_BLOCK_HIT -> rL
    net.minecraft.sounds.SoundEvent NETHERITE_BLOCK_FALL -> rM
    net.minecraft.sounds.SoundEvent NETHERRACK_BREAK -> rN
    net.minecraft.sounds.SoundEvent NETHERRACK_STEP -> rO
    net.minecraft.sounds.SoundEvent NETHERRACK_PLACE -> rP
    net.minecraft.sounds.SoundEvent NETHERRACK_HIT -> rQ
    net.minecraft.sounds.SoundEvent NETHERRACK_FALL -> rR
    net.minecraft.core.Holder$Reference NOTE_BLOCK_BASEDRUM -> rS
    net.minecraft.core.Holder$Reference NOTE_BLOCK_BASS -> rT
    net.minecraft.core.Holder$Reference NOTE_BLOCK_BELL -> rU
    net.minecraft.core.Holder$Reference NOTE_BLOCK_CHIME -> rV
    net.minecraft.core.Holder$Reference NOTE_BLOCK_FLUTE -> rW
    net.minecraft.core.Holder$Reference NOTE_BLOCK_GUITAR -> rX
    net.minecraft.core.Holder$Reference NOTE_BLOCK_HARP -> rY
    net.minecraft.core.Holder$Reference NOTE_BLOCK_HAT -> rZ
    net.minecraft.core.Holder$Reference NOTE_BLOCK_SNARE -> sb
    net.minecraft.core.Holder$Reference NOTE_BLOCK_XYLOPHONE -> sc
    net.minecraft.core.Holder$Reference NOTE_BLOCK_IRON_XYLOPHONE -> sd
    net.minecraft.core.Holder$Reference NOTE_BLOCK_COW_BELL -> se
    net.minecraft.core.Holder$Reference NOTE_BLOCK_DIDGERIDOO -> sf
    net.minecraft.core.Holder$Reference NOTE_BLOCK_BIT -> sg
    net.minecraft.core.Holder$Reference NOTE_BLOCK_BANJO -> sh
    net.minecraft.core.Holder$Reference NOTE_BLOCK_IMITATE_ZOMBIE -> si
    net.minecraft.core.Holder$Reference NOTE_BLOCK_IMITATE_SKELETON -> sj
    net.minecraft.core.Holder$Reference NOTE_BLOCK_IMITATE_CREEPER -> sk
    net.minecraft.core.Holder$Reference NOTE_BLOCK_IMITATE_ENDER_DRAGON -> sl
    net.minecraft.core.Holder$Reference NOTE_BLOCK_IMITATE_WITHER_SKELETON -> sm
    net.minecraft.core.Holder$Reference NOTE_BLOCK_IMITATE_PIGLIN -> sn
    net.minecraft.sounds.SoundEvent OCELOT_HURT -> so
    net.minecraft.sounds.SoundEvent OCELOT_AMBIENT -> sp
    net.minecraft.sounds.SoundEvent OCELOT_DEATH -> sq
    net.minecraft.sounds.SoundEvent OMINOUS_BOTTLE_DISPOSE -> sr
    net.minecraft.sounds.SoundEvent PAINTING_BREAK -> ss
    net.minecraft.sounds.SoundEvent PAINTING_PLACE -> st
    net.minecraft.sounds.SoundEvent PANDA_PRE_SNEEZE -> su
    net.minecraft.sounds.SoundEvent PANDA_SNEEZE -> sv
    net.minecraft.sounds.SoundEvent PANDA_AMBIENT -> sw
    net.minecraft.sounds.SoundEvent PANDA_DEATH -> sx
    net.minecraft.sounds.SoundEvent PANDA_EAT -> sy
    net.minecraft.sounds.SoundEvent PANDA_STEP -> sz
    net.minecraft.sounds.SoundEvent PANDA_CANT_BREED -> sA
    net.minecraft.sounds.SoundEvent PANDA_AGGRESSIVE_AMBIENT -> sB
    net.minecraft.sounds.SoundEvent PANDA_WORRIED_AMBIENT -> sC
    net.minecraft.sounds.SoundEvent PANDA_HURT -> sD
    net.minecraft.sounds.SoundEvent PANDA_BITE -> sE
    net.minecraft.sounds.SoundEvent PARROT_AMBIENT -> sF
    net.minecraft.sounds.SoundEvent PARROT_DEATH -> sG
    net.minecraft.sounds.SoundEvent PARROT_EAT -> sH
    net.minecraft.sounds.SoundEvent PARROT_FLY -> sI
    net.minecraft.sounds.SoundEvent PARROT_HURT -> sJ
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_BLAZE -> sK
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_BOGGED -> sL
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_BREEZE -> sM
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_CREEPER -> sN
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_DROWNED -> sO
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_ELDER_GUARDIAN -> sP
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_ENDER_DRAGON -> sQ
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_ENDERMITE -> sR
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_EVOKER -> sS
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_GHAST -> sT
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_GUARDIAN -> sU
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_HOGLIN -> sV
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_HUSK -> sW
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_ILLUSIONER -> sX
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_MAGMA_CUBE -> sY
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_PHANTOM -> sZ
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_PIGLIN -> ta
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_PIGLIN_BRUTE -> tb
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_PILLAGER -> tc
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_RAVAGER -> td
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_SHULKER -> te
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_SILVERFISH -> tf
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_SKELETON -> tg
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_SLIME -> th
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_SPIDER -> ti
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_STRAY -> tj
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_VEX -> tk
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_VINDICATOR -> tl
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_WARDEN -> tm
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_WITCH -> tn
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_WITHER -> to
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_WITHER_SKELETON -> tp
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_ZOGLIN -> tq
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_ZOMBIE -> tr
    net.minecraft.sounds.SoundEvent PARROT_IMITATE_ZOMBIE_VILLAGER -> ts
    net.minecraft.sounds.SoundEvent PARROT_STEP -> tt
    net.minecraft.sounds.SoundEvent PHANTOM_AMBIENT -> tu
    net.minecraft.sounds.SoundEvent PHANTOM_BITE -> tv
    net.minecraft.sounds.SoundEvent PHANTOM_DEATH -> tw
    net.minecraft.sounds.SoundEvent PHANTOM_FLAP -> tx
    net.minecraft.sounds.SoundEvent PHANTOM_HURT -> ty
    net.minecraft.sounds.SoundEvent PHANTOM_SWOOP -> tz
    net.minecraft.sounds.SoundEvent PIG_AMBIENT -> tA
    net.minecraft.sounds.SoundEvent PIG_DEATH -> tB
    net.minecraft.sounds.SoundEvent PIG_HURT -> tC
    net.minecraft.sounds.SoundEvent PIG_SADDLE -> tD
    net.minecraft.sounds.SoundEvent PIG_STEP -> tE
    net.minecraft.sounds.SoundEvent PIGLIN_ADMIRING_ITEM -> tF
    net.minecraft.sounds.SoundEvent PIGLIN_AMBIENT -> tG
    net.minecraft.sounds.SoundEvent PIGLIN_ANGRY -> tH
    net.minecraft.sounds.SoundEvent PIGLIN_CELEBRATE -> tI
    net.minecraft.sounds.SoundEvent PIGLIN_DEATH -> tJ
    net.minecraft.sounds.SoundEvent PIGLIN_JEALOUS -> tK
    net.minecraft.sounds.SoundEvent PIGLIN_HURT -> tL
    net.minecraft.sounds.SoundEvent PIGLIN_RETREAT -> tM
    net.minecraft.sounds.SoundEvent PIGLIN_STEP -> tN
    net.minecraft.sounds.SoundEvent PIGLIN_CONVERTED_TO_ZOMBIFIED -> tO
    net.minecraft.sounds.SoundEvent PIGLIN_BRUTE_AMBIENT -> tP
    net.minecraft.sounds.SoundEvent PIGLIN_BRUTE_ANGRY -> tQ
    net.minecraft.sounds.SoundEvent PIGLIN_BRUTE_DEATH -> tR
    net.minecraft.sounds.SoundEvent PIGLIN_BRUTE_HURT -> tS
    net.minecraft.sounds.SoundEvent PIGLIN_BRUTE_STEP -> tT
    net.minecraft.sounds.SoundEvent PIGLIN_BRUTE_CONVERTED_TO_ZOMBIFIED -> tU
    net.minecraft.sounds.SoundEvent PILLAGER_AMBIENT -> tV
    net.minecraft.sounds.SoundEvent PILLAGER_CELEBRATE -> tW
    net.minecraft.sounds.SoundEvent PILLAGER_DEATH -> tX
    net.minecraft.sounds.SoundEvent PILLAGER_HURT -> tY
    net.minecraft.sounds.SoundEvent PISTON_CONTRACT -> tZ
    net.minecraft.sounds.SoundEvent PISTON_EXTEND -> ua
    net.minecraft.sounds.SoundEvent PLAYER_ATTACK_CRIT -> ub
    net.minecraft.sounds.SoundEvent PLAYER_ATTACK_KNOCKBACK -> uc
    net.minecraft.sounds.SoundEvent PLAYER_ATTACK_NODAMAGE -> ud
    net.minecraft.sounds.SoundEvent PLAYER_ATTACK_STRONG -> ue
    net.minecraft.sounds.SoundEvent PLAYER_ATTACK_SWEEP -> uf
    net.minecraft.sounds.SoundEvent PLAYER_ATTACK_WEAK -> ug
    net.minecraft.sounds.SoundEvent PLAYER_BIG_FALL -> uh
    net.minecraft.sounds.SoundEvent PLAYER_BREATH -> ui
    net.minecraft.sounds.SoundEvent PLAYER_BURP -> uj
    net.minecraft.sounds.SoundEvent PLAYER_DEATH -> uk
    net.minecraft.sounds.SoundEvent PLAYER_HURT -> ul
    net.minecraft.sounds.SoundEvent PLAYER_HURT_DROWN -> um
    net.minecraft.sounds.SoundEvent PLAYER_HURT_FREEZE -> un
    net.minecraft.sounds.SoundEvent PLAYER_HURT_ON_FIRE -> uo
    net.minecraft.sounds.SoundEvent PLAYER_HURT_SWEET_BERRY_BUSH -> up
    net.minecraft.sounds.SoundEvent PLAYER_LEVELUP -> uq
    net.minecraft.sounds.SoundEvent PLAYER_SMALL_FALL -> ur
    net.minecraft.sounds.SoundEvent PLAYER_SPLASH -> us
    net.minecraft.sounds.SoundEvent PLAYER_SPLASH_HIGH_SPEED -> ut
    net.minecraft.sounds.SoundEvent PLAYER_SWIM -> uu
    net.minecraft.sounds.SoundEvent PLAYER_TELEPORT -> uv
    net.minecraft.sounds.SoundEvent POLAR_BEAR_AMBIENT -> uw
    net.minecraft.sounds.SoundEvent POLAR_BEAR_AMBIENT_BABY -> ux
    net.minecraft.sounds.SoundEvent POLAR_BEAR_DEATH -> uy
    net.minecraft.sounds.SoundEvent POLAR_BEAR_HURT -> uz
    net.minecraft.sounds.SoundEvent POLAR_BEAR_STEP -> uA
    net.minecraft.sounds.SoundEvent POLAR_BEAR_WARNING -> uB
    net.minecraft.sounds.SoundEvent POLISHED_DEEPSLATE_BREAK -> uC
    net.minecraft.sounds.SoundEvent POLISHED_DEEPSLATE_FALL -> uD
    net.minecraft.sounds.SoundEvent POLISHED_DEEPSLATE_HIT -> uE
    net.minecraft.sounds.SoundEvent POLISHED_DEEPSLATE_PLACE -> uF
    net.minecraft.sounds.SoundEvent POLISHED_DEEPSLATE_STEP -> uG
    net.minecraft.sounds.SoundEvent PORTAL_AMBIENT -> uH
    net.minecraft.sounds.SoundEvent PORTAL_TRAVEL -> uI
    net.minecraft.sounds.SoundEvent PORTAL_TRIGGER -> uJ
    net.minecraft.sounds.SoundEvent POWDER_SNOW_BREAK -> uK
    net.minecraft.sounds.SoundEvent POWDER_SNOW_FALL -> uL
    net.minecraft.sounds.SoundEvent POWDER_SNOW_HIT -> uM
    net.minecraft.sounds.SoundEvent POWDER_SNOW_PLACE -> uN
    net.minecraft.sounds.SoundEvent POWDER_SNOW_STEP -> uO
    net.minecraft.sounds.SoundEvent PUFFER_FISH_AMBIENT -> uP
    net.minecraft.sounds.SoundEvent PUFFER_FISH_BLOW_OUT -> uQ
    net.minecraft.sounds.SoundEvent PUFFER_FISH_BLOW_UP -> uR
    net.minecraft.sounds.SoundEvent PUFFER_FISH_DEATH -> uS
    net.minecraft.sounds.SoundEvent PUFFER_FISH_FLOP -> uT
    net.minecraft.sounds.SoundEvent PUFFER_FISH_HURT -> uU
    net.minecraft.sounds.SoundEvent PUFFER_FISH_STING -> uV
    net.minecraft.sounds.SoundEvent PUMPKIN_CARVE -> uW
    net.minecraft.sounds.SoundEvent RABBIT_AMBIENT -> uX
    net.minecraft.sounds.SoundEvent RABBIT_ATTACK -> uY
    net.minecraft.sounds.SoundEvent RABBIT_DEATH -> uZ
    net.minecraft.sounds.SoundEvent RABBIT_HURT -> va
    net.minecraft.sounds.SoundEvent RABBIT_JUMP -> vb
    net.minecraft.core.Holder$Reference RAID_HORN -> vc
    net.minecraft.sounds.SoundEvent RAVAGER_AMBIENT -> vd
    net.minecraft.sounds.SoundEvent RAVAGER_ATTACK -> ve
    net.minecraft.sounds.SoundEvent RAVAGER_CELEBRATE -> vf
    net.minecraft.sounds.SoundEvent RAVAGER_DEATH -> vg
    net.minecraft.sounds.SoundEvent RAVAGER_HURT -> vh
    net.minecraft.sounds.SoundEvent RAVAGER_STEP -> vi
    net.minecraft.sounds.SoundEvent RAVAGER_STUNNED -> vj
    net.minecraft.sounds.SoundEvent RAVAGER_ROAR -> vk
    net.minecraft.sounds.SoundEvent NETHER_GOLD_ORE_BREAK -> vl
    net.minecraft.sounds.SoundEvent NETHER_GOLD_ORE_FALL -> vm
    net.minecraft.sounds.SoundEvent NETHER_GOLD_ORE_HIT -> vn
    net.minecraft.sounds.SoundEvent NETHER_GOLD_ORE_PLACE -> vo
    net.minecraft.sounds.SoundEvent NETHER_GOLD_ORE_STEP -> vp
    net.minecraft.sounds.SoundEvent NETHER_ORE_BREAK -> vq
    net.minecraft.sounds.SoundEvent NETHER_ORE_FALL -> vr
    net.minecraft.sounds.SoundEvent NETHER_ORE_HIT -> vs
    net.minecraft.sounds.SoundEvent NETHER_ORE_PLACE -> vt
    net.minecraft.sounds.SoundEvent NETHER_ORE_STEP -> vu
    net.minecraft.sounds.SoundEvent REDSTONE_TORCH_BURNOUT -> vv
    net.minecraft.sounds.SoundEvent RESPAWN_ANCHOR_AMBIENT -> vw
    net.minecraft.sounds.SoundEvent RESPAWN_ANCHOR_CHARGE -> vx
    net.minecraft.core.Holder$Reference RESPAWN_ANCHOR_DEPLETE -> vy
    net.minecraft.sounds.SoundEvent RESPAWN_ANCHOR_SET_SPAWN -> vz
    net.minecraft.sounds.SoundEvent ROOTED_DIRT_BREAK -> vA
    net.minecraft.sounds.SoundEvent ROOTED_DIRT_FALL -> vB
    net.minecraft.sounds.SoundEvent ROOTED_DIRT_HIT -> vC
    net.minecraft.sounds.SoundEvent ROOTED_DIRT_PLACE -> vD
    net.minecraft.sounds.SoundEvent ROOTED_DIRT_STEP -> vE
    net.minecraft.sounds.SoundEvent SALMON_AMBIENT -> vF
    net.minecraft.sounds.SoundEvent SALMON_DEATH -> vG
    net.minecraft.sounds.SoundEvent SALMON_FLOP -> vH
    net.minecraft.sounds.SoundEvent SALMON_HURT -> vI
    net.minecraft.sounds.SoundEvent SAND_BREAK -> vJ
    net.minecraft.sounds.SoundEvent SAND_FALL -> vK
    net.minecraft.sounds.SoundEvent SAND_HIT -> vL
    net.minecraft.sounds.SoundEvent SAND_PLACE -> vM
    net.minecraft.sounds.SoundEvent SAND_STEP -> vN
    net.minecraft.sounds.SoundEvent SCAFFOLDING_BREAK -> vO
    net.minecraft.sounds.SoundEvent SCAFFOLDING_FALL -> vP
    net.minecraft.sounds.SoundEvent SCAFFOLDING_HIT -> vQ
    net.minecraft.sounds.SoundEvent SCAFFOLDING_PLACE -> vR
    net.minecraft.sounds.SoundEvent SCAFFOLDING_STEP -> vS
    net.minecraft.sounds.SoundEvent SCULK_BLOCK_SPREAD -> vT
    net.minecraft.sounds.SoundEvent SCULK_BLOCK_CHARGE -> vU
    net.minecraft.sounds.SoundEvent SCULK_BLOCK_BREAK -> vV
    net.minecraft.sounds.SoundEvent SCULK_BLOCK_FALL -> vW
    net.minecraft.sounds.SoundEvent SCULK_BLOCK_HIT -> vX
    net.minecraft.sounds.SoundEvent SCULK_BLOCK_PLACE -> vY
    net.minecraft.sounds.SoundEvent SCULK_BLOCK_STEP -> vZ
    net.minecraft.sounds.SoundEvent SCULK_CATALYST_BLOOM -> wa
    net.minecraft.sounds.SoundEvent SCULK_CATALYST_BREAK -> wb
    net.minecraft.sounds.SoundEvent SCULK_CATALYST_FALL -> wc
    net.minecraft.sounds.SoundEvent SCULK_CATALYST_HIT -> wd
    net.minecraft.sounds.SoundEvent SCULK_CATALYST_PLACE -> we
    net.minecraft.sounds.SoundEvent SCULK_CATALYST_STEP -> wf
    net.minecraft.sounds.SoundEvent SCULK_CLICKING -> wg
    net.minecraft.sounds.SoundEvent SCULK_CLICKING_STOP -> wh
    net.minecraft.sounds.SoundEvent SCULK_SENSOR_BREAK -> wi
    net.minecraft.sounds.SoundEvent SCULK_SENSOR_FALL -> wj
    net.minecraft.sounds.SoundEvent SCULK_SENSOR_HIT -> wk
    net.minecraft.sounds.SoundEvent SCULK_SENSOR_PLACE -> wl
    net.minecraft.sounds.SoundEvent SCULK_SENSOR_STEP -> wm
    net.minecraft.sounds.SoundEvent SCULK_SHRIEKER_BREAK -> wn
    net.minecraft.sounds.SoundEvent SCULK_SHRIEKER_FALL -> wo
    net.minecraft.sounds.SoundEvent SCULK_SHRIEKER_HIT -> wp
    net.minecraft.sounds.SoundEvent SCULK_SHRIEKER_PLACE -> wq
    net.minecraft.sounds.SoundEvent SCULK_SHRIEKER_SHRIEK -> wr
    net.minecraft.sounds.SoundEvent SCULK_SHRIEKER_STEP -> ws
    net.minecraft.sounds.SoundEvent SCULK_VEIN_BREAK -> wt
    net.minecraft.sounds.SoundEvent SCULK_VEIN_FALL -> wu
    net.minecraft.sounds.SoundEvent SCULK_VEIN_HIT -> wv
    net.minecraft.sounds.SoundEvent SCULK_VEIN_PLACE -> ww
    net.minecraft.sounds.SoundEvent SCULK_VEIN_STEP -> wx
    net.minecraft.sounds.SoundEvent SHEEP_AMBIENT -> wy
    net.minecraft.sounds.SoundEvent SHEEP_DEATH -> wz
    net.minecraft.sounds.SoundEvent SHEEP_HURT -> wA
    net.minecraft.sounds.SoundEvent SHEEP_SHEAR -> wB
    net.minecraft.sounds.SoundEvent SHEEP_STEP -> wC
    net.minecraft.sounds.SoundEvent SHIELD_BLOCK -> wD
    net.minecraft.sounds.SoundEvent SHIELD_BREAK -> wE
    net.minecraft.sounds.SoundEvent SHROOMLIGHT_BREAK -> wF
    net.minecraft.sounds.SoundEvent SHROOMLIGHT_STEP -> wG
    net.minecraft.sounds.SoundEvent SHROOMLIGHT_PLACE -> wH
    net.minecraft.sounds.SoundEvent SHROOMLIGHT_HIT -> wI
    net.minecraft.sounds.SoundEvent SHROOMLIGHT_FALL -> wJ
    net.minecraft.sounds.SoundEvent SHOVEL_FLATTEN -> wK
    net.minecraft.sounds.SoundEvent SHULKER_AMBIENT -> wL
    net.minecraft.sounds.SoundEvent SHULKER_BOX_CLOSE -> wM
    net.minecraft.sounds.SoundEvent SHULKER_BOX_OPEN -> wN
    net.minecraft.sounds.SoundEvent SHULKER_BULLET_HIT -> wO
    net.minecraft.sounds.SoundEvent SHULKER_BULLET_HURT -> wP
    net.minecraft.sounds.SoundEvent SHULKER_CLOSE -> wQ
    net.minecraft.sounds.SoundEvent SHULKER_DEATH -> wR
    net.minecraft.sounds.SoundEvent SHULKER_HURT -> wS
    net.minecraft.sounds.SoundEvent SHULKER_HURT_CLOSED -> wT
    net.minecraft.sounds.SoundEvent SHULKER_OPEN -> wU
    net.minecraft.sounds.SoundEvent SHULKER_SHOOT -> wV
    net.minecraft.sounds.SoundEvent SHULKER_TELEPORT -> wW
    net.minecraft.sounds.SoundEvent SILVERFISH_AMBIENT -> wX
    net.minecraft.sounds.SoundEvent SILVERFISH_DEATH -> wY
    net.minecraft.sounds.SoundEvent SILVERFISH_HURT -> wZ
    net.minecraft.sounds.SoundEvent SILVERFISH_STEP -> xa
    net.minecraft.sounds.SoundEvent SKELETON_AMBIENT -> xb
    net.minecraft.sounds.SoundEvent SKELETON_CONVERTED_TO_STRAY -> xc
    net.minecraft.sounds.SoundEvent SKELETON_DEATH -> xd
    net.minecraft.sounds.SoundEvent SKELETON_HORSE_AMBIENT -> xe
    net.minecraft.sounds.SoundEvent SKELETON_HORSE_DEATH -> xf
    net.minecraft.sounds.SoundEvent SKELETON_HORSE_HURT -> xg
    net.minecraft.sounds.SoundEvent SKELETON_HORSE_SWIM -> xh
    net.minecraft.sounds.SoundEvent SKELETON_HORSE_AMBIENT_WATER -> xi
    net.minecraft.sounds.SoundEvent SKELETON_HORSE_GALLOP_WATER -> xj
    net.minecraft.sounds.SoundEvent SKELETON_HORSE_JUMP_WATER -> xk
    net.minecraft.sounds.SoundEvent SKELETON_HORSE_STEP_WATER -> xl
    net.minecraft.sounds.SoundEvent SKELETON_HURT -> xm
    net.minecraft.sounds.SoundEvent SKELETON_SHOOT -> xn
    net.minecraft.sounds.SoundEvent SKELETON_STEP -> xo
    net.minecraft.sounds.SoundEvent SLIME_ATTACK -> xp
    net.minecraft.sounds.SoundEvent SLIME_DEATH -> xq
    net.minecraft.sounds.SoundEvent SLIME_HURT -> xr
    net.minecraft.sounds.SoundEvent SLIME_JUMP -> xs
    net.minecraft.sounds.SoundEvent SLIME_SQUISH -> xt
    net.minecraft.sounds.SoundEvent SLIME_BLOCK_BREAK -> xu
    net.minecraft.sounds.SoundEvent SLIME_BLOCK_FALL -> xv
    net.minecraft.sounds.SoundEvent SLIME_BLOCK_HIT -> xw
    net.minecraft.sounds.SoundEvent SLIME_BLOCK_PLACE -> xx
    net.minecraft.sounds.SoundEvent SLIME_BLOCK_STEP -> xy
    net.minecraft.sounds.SoundEvent SMALL_AMETHYST_BUD_BREAK -> xz
    net.minecraft.sounds.SoundEvent SMALL_AMETHYST_BUD_PLACE -> xA
    net.minecraft.sounds.SoundEvent SMALL_DRIPLEAF_BREAK -> xB
    net.minecraft.sounds.SoundEvent SMALL_DRIPLEAF_FALL -> xC
    net.minecraft.sounds.SoundEvent SMALL_DRIPLEAF_HIT -> xD
    net.minecraft.sounds.SoundEvent SMALL_DRIPLEAF_PLACE -> xE
    net.minecraft.sounds.SoundEvent SMALL_DRIPLEAF_STEP -> xF
    net.minecraft.sounds.SoundEvent SOUL_SAND_BREAK -> xG
    net.minecraft.sounds.SoundEvent SOUL_SAND_STEP -> xH
    net.minecraft.sounds.SoundEvent SOUL_SAND_PLACE -> xI
    net.minecraft.sounds.SoundEvent SOUL_SAND_HIT -> xJ
    net.minecraft.sounds.SoundEvent SOUL_SAND_FALL -> xK
    net.minecraft.sounds.SoundEvent SOUL_SOIL_BREAK -> xL
    net.minecraft.sounds.SoundEvent SOUL_SOIL_STEP -> xM
    net.minecraft.sounds.SoundEvent SOUL_SOIL_PLACE -> xN
    net.minecraft.sounds.SoundEvent SOUL_SOIL_HIT -> xO
    net.minecraft.sounds.SoundEvent SOUL_SOIL_FALL -> xP
    net.minecraft.core.Holder$Reference SOUL_ESCAPE -> xQ
    net.minecraft.sounds.SoundEvent SPORE_BLOSSOM_BREAK -> xR
    net.minecraft.sounds.SoundEvent SPORE_BLOSSOM_FALL -> xS
    net.minecraft.sounds.SoundEvent SPORE_BLOSSOM_HIT -> xT
    net.minecraft.sounds.SoundEvent SPORE_BLOSSOM_PLACE -> xU
    net.minecraft.sounds.SoundEvent SPORE_BLOSSOM_STEP -> xV
    net.minecraft.sounds.SoundEvent STRIDER_AMBIENT -> xW
    net.minecraft.sounds.SoundEvent STRIDER_HAPPY -> xX
    net.minecraft.sounds.SoundEvent STRIDER_RETREAT -> xY
    net.minecraft.sounds.SoundEvent STRIDER_DEATH -> xZ
    net.minecraft.sounds.SoundEvent STRIDER_HURT -> ya
    net.minecraft.sounds.SoundEvent STRIDER_STEP -> yb
    net.minecraft.sounds.SoundEvent STRIDER_STEP_LAVA -> yc
    net.minecraft.sounds.SoundEvent STRIDER_EAT -> yd
    net.minecraft.sounds.SoundEvent STRIDER_SADDLE -> ye
    net.minecraft.sounds.SoundEvent SLIME_DEATH_SMALL -> yf
    net.minecraft.sounds.SoundEvent SLIME_HURT_SMALL -> yg
    net.minecraft.sounds.SoundEvent SLIME_JUMP_SMALL -> yh
    net.minecraft.sounds.SoundEvent SLIME_SQUISH_SMALL -> yi
    net.minecraft.sounds.SoundEvent SMITHING_TABLE_USE -> yj
    net.minecraft.sounds.SoundEvent SMOKER_SMOKE -> yk
    net.minecraft.sounds.SoundEvent SNIFFER_STEP -> yl
    net.minecraft.sounds.SoundEvent SNIFFER_EAT -> ym
    net.minecraft.sounds.SoundEvent SNIFFER_IDLE -> yn
    net.minecraft.sounds.SoundEvent SNIFFER_HURT -> yo
    net.minecraft.sounds.SoundEvent SNIFFER_DEATH -> yp
    net.minecraft.sounds.SoundEvent SNIFFER_DROP_SEED -> yq
    net.minecraft.sounds.SoundEvent SNIFFER_SCENTING -> yr
    net.minecraft.sounds.SoundEvent SNIFFER_SNIFFING -> ys
    net.minecraft.sounds.SoundEvent SNIFFER_SEARCHING -> yt
    net.minecraft.sounds.SoundEvent SNIFFER_DIGGING -> yu
    net.minecraft.sounds.SoundEvent SNIFFER_DIGGING_STOP -> yv
    net.minecraft.sounds.SoundEvent SNIFFER_HAPPY -> yw
    net.minecraft.sounds.SoundEvent SNIFFER_EGG_PLOP -> yx
    net.minecraft.sounds.SoundEvent SNIFFER_EGG_CRACK -> yy
    net.minecraft.sounds.SoundEvent SNIFFER_EGG_HATCH -> yz
    net.minecraft.sounds.SoundEvent SNOWBALL_THROW -> yA
    net.minecraft.sounds.SoundEvent SNOW_BREAK -> yB
    net.minecraft.sounds.SoundEvent SNOW_FALL -> yC
    net.minecraft.sounds.SoundEvent SNOW_GOLEM_AMBIENT -> yD
    net.minecraft.sounds.SoundEvent SNOW_GOLEM_DEATH -> yE
    net.minecraft.sounds.SoundEvent SNOW_GOLEM_HURT -> yF
    net.minecraft.sounds.SoundEvent SNOW_GOLEM_SHOOT -> yG
    net.minecraft.sounds.SoundEvent SNOW_GOLEM_SHEAR -> yH
    net.minecraft.sounds.SoundEvent SNOW_HIT -> yI
    net.minecraft.sounds.SoundEvent SNOW_PLACE -> yJ
    net.minecraft.sounds.SoundEvent SNOW_STEP -> yK
    net.minecraft.sounds.SoundEvent SPIDER_AMBIENT -> yL
    net.minecraft.sounds.SoundEvent SPIDER_DEATH -> yM
    net.minecraft.sounds.SoundEvent SPIDER_HURT -> yN
    net.minecraft.sounds.SoundEvent SPIDER_STEP -> yO
    net.minecraft.sounds.SoundEvent SPLASH_POTION_BREAK -> yP
    net.minecraft.sounds.SoundEvent SPLASH_POTION_THROW -> yQ
    net.minecraft.sounds.SoundEvent SPONGE_BREAK -> yR
    net.minecraft.sounds.SoundEvent SPONGE_FALL -> yS
    net.minecraft.sounds.SoundEvent SPONGE_HIT -> yT
    net.minecraft.sounds.SoundEvent SPONGE_PLACE -> yU
    net.minecraft.sounds.SoundEvent SPONGE_STEP -> yV
    net.minecraft.sounds.SoundEvent SPONGE_ABSORB -> yW
    net.minecraft.sounds.SoundEvent SPYGLASS_USE -> yX
    net.minecraft.sounds.SoundEvent SPYGLASS_STOP_USING -> yY
    net.minecraft.sounds.SoundEvent SQUID_AMBIENT -> yZ
    net.minecraft.sounds.SoundEvent SQUID_DEATH -> za
    net.minecraft.sounds.SoundEvent SQUID_HURT -> zb
    net.minecraft.sounds.SoundEvent SQUID_SQUIRT -> zc
    net.minecraft.sounds.SoundEvent STONE_BREAK -> zd
    net.minecraft.sounds.SoundEvent STONE_BUTTON_CLICK_OFF -> ze
    net.minecraft.sounds.SoundEvent STONE_BUTTON_CLICK_ON -> zf
    net.minecraft.sounds.SoundEvent STONE_FALL -> zg
    net.minecraft.sounds.SoundEvent STONE_HIT -> zh
    net.minecraft.sounds.SoundEvent STONE_PLACE -> zi
    net.minecraft.sounds.SoundEvent STONE_PRESSURE_PLATE_CLICK_OFF -> zj
    net.minecraft.sounds.SoundEvent STONE_PRESSURE_PLATE_CLICK_ON -> zk
    net.minecraft.sounds.SoundEvent STONE_STEP -> zl
    net.minecraft.sounds.SoundEvent STRAY_AMBIENT -> zm
    net.minecraft.sounds.SoundEvent STRAY_DEATH -> zn
    net.minecraft.sounds.SoundEvent STRAY_HURT -> zo
    net.minecraft.sounds.SoundEvent STRAY_STEP -> zp
    net.minecraft.sounds.SoundEvent SWEET_BERRY_BUSH_BREAK -> zq
    net.minecraft.sounds.SoundEvent SWEET_BERRY_BUSH_PLACE -> zr
    net.minecraft.sounds.SoundEvent SWEET_BERRY_BUSH_PICK_BERRIES -> zs
    net.minecraft.sounds.SoundEvent TADPOLE_DEATH -> zt
    net.minecraft.sounds.SoundEvent TADPOLE_FLOP -> zu
    net.minecraft.sounds.SoundEvent TADPOLE_GROW_UP -> zv
    net.minecraft.sounds.SoundEvent TADPOLE_HURT -> zw
    net.minecraft.sounds.SoundEvent THORNS_HIT -> zx
    net.minecraft.sounds.SoundEvent TNT_PRIMED -> zy
    net.minecraft.sounds.SoundEvent TOTEM_USE -> zz
    net.minecraft.sounds.SoundEvent TRIDENT_HIT -> zA
    net.minecraft.sounds.SoundEvent TRIDENT_HIT_GROUND -> zB
    net.minecraft.sounds.SoundEvent TRIDENT_RETURN -> zC
    net.minecraft.core.Holder TRIDENT_RIPTIDE_1 -> zD
    net.minecraft.core.Holder TRIDENT_RIPTIDE_2 -> zE
    net.minecraft.core.Holder TRIDENT_RIPTIDE_3 -> zF
    net.minecraft.core.Holder TRIDENT_THROW -> zG
    net.minecraft.core.Holder TRIDENT_THUNDER -> zH
    net.minecraft.sounds.SoundEvent TRIPWIRE_ATTACH -> zI
    net.minecraft.sounds.SoundEvent TRIPWIRE_CLICK_OFF -> zJ
    net.minecraft.sounds.SoundEvent TRIPWIRE_CLICK_ON -> zK
    net.minecraft.sounds.SoundEvent TRIPWIRE_DETACH -> zL
    net.minecraft.sounds.SoundEvent TROPICAL_FISH_AMBIENT -> zM
    net.minecraft.sounds.SoundEvent TROPICAL_FISH_DEATH -> zN
    net.minecraft.sounds.SoundEvent TROPICAL_FISH_FLOP -> zO
    net.minecraft.sounds.SoundEvent TROPICAL_FISH_HURT -> zP
    net.minecraft.sounds.SoundEvent TUFF_BREAK -> zQ
    net.minecraft.sounds.SoundEvent TUFF_STEP -> zR
    net.minecraft.sounds.SoundEvent TUFF_PLACE -> zS
    net.minecraft.sounds.SoundEvent TUFF_HIT -> zT
    net.minecraft.sounds.SoundEvent TUFF_FALL -> zU
    net.minecraft.sounds.SoundEvent TUFF_BRICKS_BREAK -> zV
    net.minecraft.sounds.SoundEvent TUFF_BRICKS_FALL -> zW
    net.minecraft.sounds.SoundEvent TUFF_BRICKS_HIT -> zX
    net.minecraft.sounds.SoundEvent TUFF_BRICKS_PLACE -> zY
    net.minecraft.sounds.SoundEvent TUFF_BRICKS_STEP -> zZ
    net.minecraft.sounds.SoundEvent POLISHED_TUFF_BREAK -> Aa
    net.minecraft.sounds.SoundEvent POLISHED_TUFF_FALL -> Ab
    net.minecraft.sounds.SoundEvent POLISHED_TUFF_HIT -> Ac
    net.minecraft.sounds.SoundEvent POLISHED_TUFF_PLACE -> Ad
    net.minecraft.sounds.SoundEvent POLISHED_TUFF_STEP -> Ae
    net.minecraft.sounds.SoundEvent TURTLE_AMBIENT_LAND -> Af
    net.minecraft.sounds.SoundEvent TURTLE_DEATH -> Ag
    net.minecraft.sounds.SoundEvent TURTLE_DEATH_BABY -> Ah
    net.minecraft.sounds.SoundEvent TURTLE_EGG_BREAK -> Ai
    net.minecraft.sounds.SoundEvent TURTLE_EGG_CRACK -> Aj
    net.minecraft.sounds.SoundEvent TURTLE_EGG_HATCH -> Ak
    net.minecraft.sounds.SoundEvent TURTLE_HURT -> Al
    net.minecraft.sounds.SoundEvent TURTLE_HURT_BABY -> Am
    net.minecraft.sounds.SoundEvent TURTLE_LAY_EGG -> An
    net.minecraft.sounds.SoundEvent TURTLE_SHAMBLE -> Ao
    net.minecraft.sounds.SoundEvent TURTLE_SHAMBLE_BABY -> Ap
    net.minecraft.sounds.SoundEvent TURTLE_SWIM -> Aq
    net.minecraft.core.Holder$Reference UI_BUTTON_CLICK -> Ar
    net.minecraft.sounds.SoundEvent UI_LOOM_SELECT_PATTERN -> As
    net.minecraft.sounds.SoundEvent UI_LOOM_TAKE_RESULT -> At
    net.minecraft.sounds.SoundEvent UI_CARTOGRAPHY_TABLE_TAKE_RESULT -> Au
    net.minecraft.sounds.SoundEvent UI_STONECUTTER_TAKE_RESULT -> Av
    net.minecraft.sounds.SoundEvent UI_STONECUTTER_SELECT_RECIPE -> Aw
    net.minecraft.sounds.SoundEvent UI_TOAST_CHALLENGE_COMPLETE -> Ax
    net.minecraft.sounds.SoundEvent UI_TOAST_IN -> Ay
    net.minecraft.sounds.SoundEvent UI_TOAST_OUT -> Az
    net.minecraft.sounds.SoundEvent VAULT_ACTIVATE -> AA
    net.minecraft.sounds.SoundEvent VAULT_AMBIENT -> AB
    net.minecraft.sounds.SoundEvent VAULT_BREAK -> AC
    net.minecraft.sounds.SoundEvent VAULT_CLOSE_SHUTTER -> AD
    net.minecraft.sounds.SoundEvent VAULT_DEACTIVATE -> AE
    net.minecraft.sounds.SoundEvent VAULT_EJECT_ITEM -> AF
    net.minecraft.sounds.SoundEvent VAULT_REJECT_REWARDED_PLAYER -> AG
    net.minecraft.sounds.SoundEvent VAULT_FALL -> AH
    net.minecraft.sounds.SoundEvent VAULT_HIT -> AI
    net.minecraft.sounds.SoundEvent VAULT_INSERT_ITEM -> AJ
    net.minecraft.sounds.SoundEvent VAULT_INSERT_ITEM_FAIL -> AK
    net.minecraft.sounds.SoundEvent VAULT_OPEN_SHUTTER -> AL
    net.minecraft.sounds.SoundEvent VAULT_PLACE -> AM
    net.minecraft.sounds.SoundEvent VAULT_STEP -> AN
    net.minecraft.sounds.SoundEvent VEX_AMBIENT -> AO
    net.minecraft.sounds.SoundEvent VEX_CHARGE -> AP
    net.minecraft.sounds.SoundEvent VEX_DEATH -> AQ
    net.minecraft.sounds.SoundEvent VEX_HURT -> AR
    net.minecraft.sounds.SoundEvent VILLAGER_AMBIENT -> AS
    net.minecraft.sounds.SoundEvent VILLAGER_CELEBRATE -> AT
    net.minecraft.sounds.SoundEvent VILLAGER_DEATH -> AU
    net.minecraft.sounds.SoundEvent VILLAGER_HURT -> AV
    net.minecraft.sounds.SoundEvent VILLAGER_NO -> AW
    net.minecraft.sounds.SoundEvent VILLAGER_TRADE -> AX
    net.minecraft.sounds.SoundEvent VILLAGER_YES -> AY
    net.minecraft.sounds.SoundEvent VILLAGER_WORK_ARMORER -> AZ
    net.minecraft.sounds.SoundEvent VILLAGER_WORK_BUTCHER -> Ba
    net.minecraft.sounds.SoundEvent VILLAGER_WORK_CARTOGRAPHER -> Bb
    net.minecraft.sounds.SoundEvent VILLAGER_WORK_CLERIC -> Bc
    net.minecraft.sounds.SoundEvent VILLAGER_WORK_FARMER -> Bd
    net.minecraft.sounds.SoundEvent VILLAGER_WORK_FISHERMAN -> Be
    net.minecraft.sounds.SoundEvent VILLAGER_WORK_FLETCHER -> Bf
    net.minecraft.sounds.SoundEvent VILLAGER_WORK_LEATHERWORKER -> Bg
    net.minecraft.sounds.SoundEvent VILLAGER_WORK_LIBRARIAN -> Bh
    net.minecraft.sounds.SoundEvent VILLAGER_WORK_MASON -> Bi
    net.minecraft.sounds.SoundEvent VILLAGER_WORK_SHEPHERD -> Bj
    net.minecraft.sounds.SoundEvent VILLAGER_WORK_TOOLSMITH -> Bk
    net.minecraft.sounds.SoundEvent VILLAGER_WORK_WEAPONSMITH -> Bl
    net.minecraft.sounds.SoundEvent VINDICATOR_AMBIENT -> Bm
    net.minecraft.sounds.SoundEvent VINDICATOR_CELEBRATE -> Bn
    net.minecraft.sounds.SoundEvent VINDICATOR_DEATH -> Bo
    net.minecraft.sounds.SoundEvent VINDICATOR_HURT -> Bp
    net.minecraft.sounds.SoundEvent VINE_BREAK -> Bq
    net.minecraft.sounds.SoundEvent VINE_FALL -> Br
    net.minecraft.sounds.SoundEvent VINE_HIT -> Bs
    net.minecraft.sounds.SoundEvent VINE_PLACE -> Bt
    net.minecraft.sounds.SoundEvent VINE_STEP -> Bu
    net.minecraft.sounds.SoundEvent LILY_PAD_PLACE -> Bv
    net.minecraft.sounds.SoundEvent WANDERING_TRADER_AMBIENT -> Bw
    net.minecraft.sounds.SoundEvent WANDERING_TRADER_DEATH -> Bx
    net.minecraft.sounds.SoundEvent WANDERING_TRADER_DISAPPEARED -> By
    net.minecraft.sounds.SoundEvent WANDERING_TRADER_DRINK_MILK -> Bz
    net.minecraft.sounds.SoundEvent WANDERING_TRADER_DRINK_POTION -> BA
    net.minecraft.sounds.SoundEvent WANDERING_TRADER_HURT -> BB
    net.minecraft.sounds.SoundEvent WANDERING_TRADER_NO -> BC
    net.minecraft.sounds.SoundEvent WANDERING_TRADER_REAPPEARED -> BD
    net.minecraft.sounds.SoundEvent WANDERING_TRADER_TRADE -> BE
    net.minecraft.sounds.SoundEvent WANDERING_TRADER_YES -> BF
    net.minecraft.sounds.SoundEvent WARDEN_AGITATED -> BG
    net.minecraft.sounds.SoundEvent WARDEN_AMBIENT -> BH
    net.minecraft.sounds.SoundEvent WARDEN_ANGRY -> BI
    net.minecraft.sounds.SoundEvent WARDEN_ATTACK_IMPACT -> BJ
    net.minecraft.sounds.SoundEvent WARDEN_DEATH -> BK
    net.minecraft.sounds.SoundEvent WARDEN_DIG -> BL
    net.minecraft.sounds.SoundEvent WARDEN_EMERGE -> BM
    net.minecraft.sounds.SoundEvent WARDEN_HEARTBEAT -> BN
    net.minecraft.sounds.SoundEvent WARDEN_HURT -> BO
    net.minecraft.sounds.SoundEvent WARDEN_LISTENING -> BP
    net.minecraft.sounds.SoundEvent WARDEN_LISTENING_ANGRY -> BQ
    net.minecraft.sounds.SoundEvent WARDEN_NEARBY_CLOSE -> BR
    net.minecraft.sounds.SoundEvent WARDEN_NEARBY_CLOSER -> BS
    net.minecraft.sounds.SoundEvent WARDEN_NEARBY_CLOSEST -> BT
    net.minecraft.sounds.SoundEvent WARDEN_ROAR -> BU
    net.minecraft.sounds.SoundEvent WARDEN_SNIFF -> BV
    net.minecraft.sounds.SoundEvent WARDEN_SONIC_BOOM -> BW
    net.minecraft.sounds.SoundEvent WARDEN_SONIC_CHARGE -> BX
    net.minecraft.sounds.SoundEvent WARDEN_STEP -> BY
    net.minecraft.sounds.SoundEvent WARDEN_TENDRIL_CLICKS -> BZ
    net.minecraft.sounds.SoundEvent WAXED_HANGING_SIGN_INTERACT_FAIL -> Ca
    net.minecraft.sounds.SoundEvent WAXED_SIGN_INTERACT_FAIL -> Cb
    net.minecraft.sounds.SoundEvent WATER_AMBIENT -> Cc
    net.minecraft.sounds.SoundEvent WEATHER_RAIN -> Cd
    net.minecraft.sounds.SoundEvent WEATHER_RAIN_ABOVE -> Ce
    net.minecraft.sounds.SoundEvent WET_GRASS_BREAK -> Cf
    net.minecraft.sounds.SoundEvent WET_GRASS_FALL -> Cg
    net.minecraft.sounds.SoundEvent WET_GRASS_HIT -> Ch
    net.minecraft.sounds.SoundEvent WET_GRASS_PLACE -> Ci
    net.minecraft.sounds.SoundEvent WET_GRASS_STEP -> Cj
    net.minecraft.sounds.SoundEvent WET_SPONGE_BREAK -> Ck
    net.minecraft.sounds.SoundEvent WET_SPONGE_DRIES -> Cl
    net.minecraft.sounds.SoundEvent WET_SPONGE_FALL -> Cm
    net.minecraft.sounds.SoundEvent WET_SPONGE_HIT -> Cn
    net.minecraft.sounds.SoundEvent WET_SPONGE_PLACE -> Co
    net.minecraft.sounds.SoundEvent WET_SPONGE_STEP -> Cp
    net.minecraft.core.Holder$Reference WIND_CHARGE_BURST -> Cq
    net.minecraft.sounds.SoundEvent WIND_CHARGE_THROW -> Cr
    net.minecraft.sounds.SoundEvent WITCH_AMBIENT -> Cs
    net.minecraft.sounds.SoundEvent WITCH_CELEBRATE -> Ct
    net.minecraft.sounds.SoundEvent WITCH_DEATH -> Cu
    net.minecraft.sounds.SoundEvent WITCH_DRINK -> Cv
    net.minecraft.sounds.SoundEvent WITCH_HURT -> Cw
    net.minecraft.sounds.SoundEvent WITCH_THROW -> Cx
    net.minecraft.sounds.SoundEvent WITHER_AMBIENT -> Cy
    net.minecraft.sounds.SoundEvent WITHER_BREAK_BLOCK -> Cz
    net.minecraft.sounds.SoundEvent WITHER_DEATH -> CA
    net.minecraft.sounds.SoundEvent WITHER_HURT -> CB
    net.minecraft.sounds.SoundEvent WITHER_SHOOT -> CC
    net.minecraft.sounds.SoundEvent WITHER_SKELETON_AMBIENT -> CD
    net.minecraft.sounds.SoundEvent WITHER_SKELETON_DEATH -> CE
    net.minecraft.sounds.SoundEvent WITHER_SKELETON_HURT -> CF
    net.minecraft.sounds.SoundEvent WITHER_SKELETON_STEP -> CG
    net.minecraft.sounds.SoundEvent WITHER_SPAWN -> CH
    net.minecraft.sounds.SoundEvent WOLF_ARMOR_BREAK -> CI
    net.minecraft.sounds.SoundEvent WOLF_ARMOR_CRACK -> CJ
    net.minecraft.sounds.SoundEvent WOLF_ARMOR_DAMAGE -> CK
    net.minecraft.sounds.SoundEvent WOLF_ARMOR_REPAIR -> CL
    net.minecraft.sounds.SoundEvent WOLF_AMBIENT -> CM
    net.minecraft.sounds.SoundEvent WOLF_DEATH -> CN
    net.minecraft.sounds.SoundEvent WOLF_GROWL -> CO
    net.minecraft.sounds.SoundEvent WOLF_HOWL -> CP
    net.minecraft.sounds.SoundEvent WOLF_HURT -> CQ
    net.minecraft.sounds.SoundEvent WOLF_PANT -> CR
    net.minecraft.sounds.SoundEvent WOLF_SHAKE -> CS
    net.minecraft.sounds.SoundEvent WOLF_STEP -> CT
    net.minecraft.sounds.SoundEvent WOLF_WHINE -> CU
    net.minecraft.sounds.SoundEvent WOODEN_DOOR_CLOSE -> CV
    net.minecraft.sounds.SoundEvent WOODEN_DOOR_OPEN -> CW
    net.minecraft.sounds.SoundEvent WOODEN_TRAPDOOR_CLOSE -> CX
    net.minecraft.sounds.SoundEvent WOODEN_TRAPDOOR_OPEN -> CY
    net.minecraft.sounds.SoundEvent WOODEN_BUTTON_CLICK_OFF -> CZ
    net.minecraft.sounds.SoundEvent WOODEN_BUTTON_CLICK_ON -> Da
    net.minecraft.sounds.SoundEvent WOODEN_PRESSURE_PLATE_CLICK_OFF -> Db
    net.minecraft.sounds.SoundEvent WOODEN_PRESSURE_PLATE_CLICK_ON -> Dc
    net.minecraft.sounds.SoundEvent WOOD_BREAK -> Dd
    net.minecraft.sounds.SoundEvent WOOD_FALL -> De
    net.minecraft.sounds.SoundEvent WOOD_HIT -> Df
    net.minecraft.sounds.SoundEvent WOOD_PLACE -> Dg
    net.minecraft.sounds.SoundEvent WOOD_STEP -> Dh
    net.minecraft.sounds.SoundEvent WOOL_BREAK -> Di
    net.minecraft.sounds.SoundEvent WOOL_FALL -> Dj
    net.minecraft.sounds.SoundEvent WOOL_HIT -> Dk
    net.minecraft.sounds.SoundEvent WOOL_PLACE -> Dl
    net.minecraft.sounds.SoundEvent WOOL_STEP -> Dm
    net.minecraft.sounds.SoundEvent ZOGLIN_AMBIENT -> Dn
    net.minecraft.sounds.SoundEvent ZOGLIN_ANGRY -> Do
    net.minecraft.sounds.SoundEvent ZOGLIN_ATTACK -> Dp
    net.minecraft.sounds.SoundEvent ZOGLIN_DEATH -> Dq
    net.minecraft.sounds.SoundEvent ZOGLIN_HURT -> Dr
    net.minecraft.sounds.SoundEvent ZOGLIN_STEP -> Ds
    net.minecraft.sounds.SoundEvent ZOMBIE_AMBIENT -> Dt
    net.minecraft.sounds.SoundEvent ZOMBIE_ATTACK_WOODEN_DOOR -> Du
    net.minecraft.sounds.SoundEvent ZOMBIE_ATTACK_IRON_DOOR -> Dv
    net.minecraft.sounds.SoundEvent ZOMBIE_BREAK_WOODEN_DOOR -> Dw
    net.minecraft.sounds.SoundEvent ZOMBIE_CONVERTED_TO_DROWNED -> Dx
    net.minecraft.sounds.SoundEvent ZOMBIE_DEATH -> Dy
    net.minecraft.sounds.SoundEvent ZOMBIE_DESTROY_EGG -> Dz
    net.minecraft.sounds.SoundEvent ZOMBIE_HORSE_AMBIENT -> DA
    net.minecraft.sounds.SoundEvent ZOMBIE_HORSE_DEATH -> DB
    net.minecraft.sounds.SoundEvent ZOMBIE_HORSE_HURT -> DC
    net.minecraft.sounds.SoundEvent ZOMBIE_HURT -> DD
    net.minecraft.sounds.SoundEvent ZOMBIE_INFECT -> DE
    net.minecraft.sounds.SoundEvent ZOMBIFIED_PIGLIN_AMBIENT -> DF
    net.minecraft.sounds.SoundEvent ZOMBIFIED_PIGLIN_ANGRY -> DG
    net.minecraft.sounds.SoundEvent ZOMBIFIED_PIGLIN_DEATH -> DH
    net.minecraft.sounds.SoundEvent ZOMBIFIED_PIGLIN_HURT -> DI
    net.minecraft.sounds.SoundEvent ZOMBIE_STEP -> DJ
    net.minecraft.sounds.SoundEvent ZOMBIE_VILLAGER_AMBIENT -> DK
    net.minecraft.sounds.SoundEvent ZOMBIE_VILLAGER_CONVERTED -> DL
    net.minecraft.sounds.SoundEvent ZOMBIE_VILLAGER_CURE -> DM
    net.minecraft.sounds.SoundEvent ZOMBIE_VILLAGER_DEATH -> DN
    net.minecraft.sounds.SoundEvent ZOMBIE_VILLAGER_HURT -> DO
    net.minecraft.sounds.SoundEvent ZOMBIE_VILLAGER_STEP -> DP
    net.minecraft.sounds.SoundEvent APPLY_EFFECT_BAD_OMEN -> DQ
    net.minecraft.sounds.SoundEvent APPLY_EFFECT_TRIAL_OMEN -> DR
    net.minecraft.sounds.SoundEvent APPLY_EFFECT_RAID_OMEN -> DS
    11:11:void <init>() -> <init>
    1626:1626:net.minecraft.core.Holder register(net.minecraft.resources.ResourceLocation,net.minecraft.resources.ResourceLocation,float) -> a
    1630:1630:net.minecraft.sounds.SoundEvent register(java.lang.String) -> a
    1634:1634:net.minecraft.sounds.SoundEvent register(net.minecraft.resources.ResourceLocation) -> a
    1638:1638:net.minecraft.core.Holder$Reference registerForHolder(java.lang.String) -> b
    1642:1642:net.minecraft.core.Holder$Reference registerForHolder(net.minecraft.resources.ResourceLocation) -> b
    1646:1646:net.minecraft.sounds.SoundEvent register(net.minecraft.resources.ResourceLocation,net.minecraft.resources.ResourceLocation) -> a
    1650:1650:net.minecraft.core.Holder$Reference registerForHolder(net.minecraft.resources.ResourceLocation,net.minecraft.resources.ResourceLocation) -> b
    1654:1656:com.google.common.collect.ImmutableList registerGoatHornSoundVariants() -> a
    1655:1655:net.minecraft.core.Holder$Reference lambda$registerGoatHornSoundVariants$0(int) -> a
    12:1619:void <clinit>() -> <clinit>
 */
class SoundEvents(around: Any) : MimickedClass(around) {
	companion object : ClassInfo {
		override val clazz: Class<*> = loadClass(net_minecraft_sounds_SoundEvents)
		override val classDesc: ClassDesc = clazz.classDesc
		override val mimicClassDesc: ClassDesc = SoundEvents::class.classDesc

		val NOTE_BLOCK_PLING: Holder.Reference<SoundEvent> = Holder.Reference(
			SoundEvent::class.java,
			clazz.getField("sa").get(null)
		)
	}
}