package org.bread_experts_group.eam.minecraft.version_impl.v1x21x1.net.minecraft.world.entity.player

import org.bread_experts_group.eam.classDesc
import org.bread_experts_group.eam.loadClass
import org.bread_experts_group.eam.minecraft.ClassInfo
import org.bread_experts_group.eam.minecraft.version_impl.v1x21x1.net.minecraft.world.entity.LivingEntity
import org.bread_experts_group.eam.minecraft.version_impl.v1x21x1.net_minecraft_world_entity_player_Player
import java.lang.constant.ClassDesc

/*
net.minecraft.world.entity.player.Player -> cmx:
# {"fileName":"Player.java","id":"sourceFile"}
    org.slf4j.Logger LOGGER -> b
    net.minecraft.world.entity.HumanoidArm DEFAULT_MAIN_HAND -> bH
    int DEFAULT_MODEL_CUSTOMIZATION -> bI
    int MAX_HEALTH -> bJ
    int SLEEP_DURATION -> bK
    int WAKE_UP_DURATION -> bL
    int ENDER_SLOT_OFFSET -> bM
    int HELD_ITEM_SLOT -> bN
    int CRAFTING_SLOT_OFFSET -> bO
    float DEFAULT_BLOCK_INTERACTION_RANGE -> bP
    float DEFAULT_ENTITY_INTERACTION_RANGE -> bQ
    float CROUCH_BB_HEIGHT -> bR
    float SWIMMING_BB_WIDTH -> bS
    float SWIMMING_BB_HEIGHT -> bT
    float DEFAULT_EYE_HEIGHT -> bU
    int CURRENT_IMPULSE_CONTEXT_RESET_GRACE_TIME_TICKS -> c
    net.minecraft.world.phys.Vec3 DEFAULT_VEHICLE_ATTACHMENT -> bV
    net.minecraft.world.entity.EntityDimensions STANDING_DIMENSIONS -> bW
    java.util.Map POSES -> d
    net.minecraft.network.syncher.EntityDataAccessor DATA_PLAYER_ABSORPTION_ID -> e
    net.minecraft.network.syncher.EntityDataAccessor DATA_SCORE_ID -> f
    net.minecraft.network.syncher.EntityDataAccessor DATA_PLAYER_MODE_CUSTOMISATION -> bX
    net.minecraft.network.syncher.EntityDataAccessor DATA_PLAYER_MAIN_HAND -> bY
    net.minecraft.network.syncher.EntityDataAccessor DATA_SHOULDER_LEFT -> bZ
    net.minecraft.network.syncher.EntityDataAccessor DATA_SHOULDER_RIGHT -> ca
    long timeEntitySatOnShoulder -> g
    net.minecraft.world.entity.player.Inventory inventory -> h
    net.minecraft.world.inventory.PlayerEnderChestContainer enderChestInventory -> cb
    net.minecraft.world.inventory.InventoryMenu inventoryMenu -> cc
    net.minecraft.world.inventory.AbstractContainerMenu containerMenu -> cd
    net.minecraft.world.food.FoodData foodData -> ce
    int jumpTriggerTime -> cf
    float oBob -> cg
    float bob -> ch
    int takeXpDelay -> ci
    double xCloakO -> cj
    double yCloakO -> ck
    double zCloakO -> cl
    double xCloak -> cm
    double yCloak -> cn
    double zCloak -> co
    int sleepCounter -> cz
    boolean wasUnderwater -> cp
    net.minecraft.world.entity.player.Abilities abilities -> cA
    int experienceLevel -> cq
    int totalExperience -> cr
    float experienceProgress -> cs
    int enchantmentSeed -> ct
    float defaultFlySpeed -> cu
    int lastLevelUpTime -> cB
    com.mojang.authlib.GameProfile gameProfile -> cD
    boolean reducedDebugInfo -> cE
    net.minecraft.world.item.ItemStack lastItemInMainHand -> cF
    net.minecraft.world.item.ItemCooldowns cooldowns -> cG
    java.util.Optional lastDeathLocation -> cH
    net.minecraft.world.entity.projectile.FishingHook fishing -> cv
    float hurtDir -> cw
    net.minecraft.world.phys.Vec3 currentImpulseImpactPos -> cx
    net.minecraft.world.entity.Entity currentExplosionCause -> cy
    boolean ignoreFallDamageFromCurrentImpulse -> cI
    int currentImpulseContextResetGraceTime -> cJ
    175:241:void <init>(net.minecraft.world.level.Level,net.minecraft.core.BlockPos,float,com.mojang.authlib.GameProfile) -> <init>
    244:254:boolean blockActionRestricted(net.minecraft.world.level.Level,net.minecraft.core.BlockPos,net.minecraft.world.level.GameType) -> a
    258:269:net.minecraft.world.entity.ai.attributes.AttributeSupplier$Builder createAttributes() -> fM
    274:282:void defineSynchedData(net.minecraft.network.syncher.SynchedEntityData$Builder) -> a
    286:365:void tick() -> l
    369:372:float getMaxHeadRotationRelativeToBody() -> fk
    382:382:boolean isSecondaryUseActive() -> fN
    386:386:boolean wantsToStopRiding() -> fO
    394:394:boolean isStayingOnGroundSurface() -> fP
    398:399:boolean updateIsUnderwater() -> fQ
    403:407:void turtleHelmetTick() -> v
    410:410:net.minecraft.world.item.ItemCooldowns createItemCooldowns() -> k
    414:451:void moveCloak() -> x
    454:488:void updatePlayerPose() -> fR
    491:491:boolean canPlayerFitWithinBlocksAndEntitiesWhen(net.minecraft.world.entity.Pose) -> h
    496:496:net.minecraft.sounds.SoundEvent getSwimSound() -> aQ
    501:501:net.minecraft.sounds.SoundEvent getSwimSplashSound() -> aR
    506:506:net.minecraft.sounds.SoundEvent getSwimHighSpeedSplashSound() -> aS
    511:511:int getDimensionChangingDelay() -> bQ
    517:518:void playSound(net.minecraft.sounds.SoundEvent,float,float) -> a
    521:521:void playNotifySound(net.minecraft.sounds.SoundEvent,net.minecraft.sounds.SoundSource,float,float) -> a
    525:525:net.minecraft.sounds.SoundSource getSoundSource() -> de
    530:530:int getFireImmuneTicks() -> df
    535:544:void handleEntityEvent(byte) -> b
    547:548:void closeContainer() -> s
    551:551:void doCloseContainer() -> t
    555:563:void rideTick() -> u
    567:571:void serverAiStep() -> fm
    575:640:void aiStep() -> m_
    643:651:void playShoulderEntityAmbientSound(net.minecraft.nbt.CompoundTag) -> c
    654:655:void touch(net.minecraft.world.entity.Entity) -> d
    658:658:int getScore() -> fS
    662:663:void setScore(int) -> r
    666:668:void increaseScore(int) -> s
    671:678:void startAutoSpinAttack(int,float,net.minecraft.world.item.ItemStack) -> a
    683:686:net.minecraft.world.item.ItemStack getWeaponItem() -> dS
    692:715:void die(net.minecraft.world.damagesource.DamageSource) -> a
    719:724:void dropEquipment() -> ez
    727:733:void destroyVanishingCursedItems() -> fT
    737:737:net.minecraft.sounds.SoundEvent getHurtSound(net.minecraft.world.damagesource.DamageSource) -> d
    742:742:net.minecraft.sounds.SoundEvent getDeathSound() -> n_
    747:747:net.minecraft.world.entity.item.ItemEntity drop(net.minecraft.world.item.ItemStack,boolean) -> a
    752:793:net.minecraft.world.entity.item.ItemEntity drop(net.minecraft.world.item.ItemStack,boolean,boolean) -> a
    797:836:float getDestroySpeed(net.minecraft.world.level.block.state.BlockState) -> c
    840:840:boolean hasCorrectToolForDrops(net.minecraft.world.level.block.state.BlockState) -> d
    845:889:void readAdditionalSaveData(net.minecraft.nbt.CompoundTag) -> a
    893:923:void addAdditionalSaveData(net.minecraft.nbt.CompoundTag) -> b
    927:940:boolean isInvulnerableTo(net.minecraft.world.damagesource.DamageSource) -> b
    945:977:boolean hurt(net.minecraft.world.damagesource.DamageSource,float) -> a
    982:987:void blockUsingShield(net.minecraft.world.entity.LivingEntity) -> d
    991:991:boolean canBeSeenAsEnemy() -> ep
    995:1004:boolean canHarmPlayer(net.minecraft.world.entity.player.Player) -> a
    1009:1010:void hurtArmor(net.minecraft.world.damagesource.DamageSource,float) -> b
    1014:1015:void hurtHelmet(net.minecraft.world.damagesource.DamageSource,float) -> c
    1019:1040:void hurtCurrentlyUsedShield(float) -> x
    1044:1070:void actuallyHurt(net.minecraft.world.damagesource.DamageSource,float) -> f
    1073:1073:boolean isTextFilteringEnabled() -> Z
    1077:1077:void openTextEdit(net.minecraft.world.level.block.entity.SignBlockEntity,boolean) -> a
    1080:1080:void openMinecartCommandBlock(net.minecraft.world.level.BaseCommandBlock) -> a
    1083:1083:void openCommandBlock(net.minecraft.world.level.block.entity.CommandBlockEntity) -> a
    1086:1086:void openStructureBlock(net.minecraft.world.level.block.entity.StructureBlockEntity) -> a
    1089:1089:void openJigsawBlock(net.minecraft.world.level.block.entity.JigsawBlockEntity) -> a
    1092:1092:void openHorseInventory(net.minecraft.world.entity.animal.horse.AbstractHorse,net.minecraft.world.Container) -> a
    1095:1095:java.util.OptionalInt openMenu(net.minecraft.world.MenuProvider) -> a
    1099:1099:void sendMerchantOffers(int,net.minecraft.world.item.trading.MerchantOffers,int,int,boolean,boolean) -> a
    1108:1108:void openItemGui(net.minecraft.world.item.ItemStack,net.minecraft.world.InteractionHand) -> a
    1111:1144:net.minecraft.world.InteractionResult interactOn(net.minecraft.world.entity.Entity,net.minecraft.world.InteractionHand) -> a
    1149:1152:void removeVehicle() -> bJ
    1156:1156:boolean isImmobile() -> fc
    1161:1161:boolean isAffectedByFluids() -> ec
    1171:1216:net.minecraft.world.phys.Vec3 maybeBackOffFromEdge(net.minecraft.world.phys.Vec3,net.minecraft.world.entity.MoverType) -> a
    1220:1220:boolean isAboveGround(float) -> G
    1224:1225:boolean canFallAtLeast(double,double,float) -> b
    1232:1412:void attack(net.minecraft.world.entity.Entity) -> e
    1416:1416:float getEnchantedDamage(net.minecraft.world.entity.Entity,float,net.minecraft.world.damagesource.DamageSource) -> a
    1421:1422:void doAutoAttackOnTouch(net.minecraft.world.entity.LivingEntity) -> g
    1425:1428:void disableShield() -> fU
    1431:1431:void crit(net.minecraft.world.entity.Entity) -> b
    1434:1434:void magicCrit(net.minecraft.world.entity.Entity) -> c
    1438:1443:void sweepAttack() -> fV
    1446:1446:void respawn() -> fW
    1450:1456:void remove(net.minecraft.world.entity.Entity$RemovalReason) -> a
    1459:1459:boolean isLocalPlayer() -> g
    1463:1463:com.mojang.authlib.GameProfile getGameProfile() -> fX
    1467:1467:net.minecraft.world.entity.player.Inventory getInventory() -> fY
    1471:1471:net.minecraft.world.entity.player.Abilities getAbilities() -> fZ
    1477:1477:boolean hasInfiniteMaterials() -> fL
    1482:1482:void updateTutorialInventoryAction(net.minecraft.world.item.ItemStack,net.minecraft.world.item.ItemStack,net.minecraft.world.inventory.ClickAction) -> a
    1485:1485:boolean hasContainerOpen() -> ga
    1514:1518:com.mojang.datafixers.util.Either startSleepInBed(net.minecraft.core.BlockPos) -> a
    1529:1536:void stopSleepInBed(boolean,boolean) -> a
    1540:1541:void stopSleeping() -> fI
    1544:1544:boolean isSleepingLongEnough() -> gb
    1548:1548:int getSleepTimer() -> gc
    1560:1560:void displayClientMessage(net.minecraft.network.chat.Component,boolean) -> a
    1563:1564:void awardStat(net.minecraft.resources.ResourceLocation) -> a
    1567:1568:void awardStat(net.minecraft.resources.ResourceLocation,int) -> a
    1571:1572:void awardStat(net.minecraft.stats.Stat) -> b
    1575:1575:void awardStat(net.minecraft.stats.Stat,int) -> a
    1578:1578:void resetStat(net.minecraft.stats.Stat) -> a
    1581:1581:int awardRecipes(java.util.Collection) -> a
    1585:1585:void triggerRecipeCrafted(net.minecraft.world.item.crafting.RecipeHolder,java.util.List) -> a
    1588:1588:void awardRecipesByKey(java.util.List) -> b
    1591:1591:int resetRecipes(java.util.Collection) -> b
    1596:1604:void jumpFromGround() -> ff
    1608:1630:void travel(net.minecraft.world.phys.Vec3) -> a
    1634:1639:void updateSwimming() -> bl
    1642:1642:boolean freeAt(net.minecraft.core.BlockPos) -> h
    1647:1647:float getSpeed() -> fj
    1655:1680:boolean causeFallDamage(float,float,net.minecraft.world.damagesource.DamageSource) -> a
    1684:1691:boolean tryToStartFallFlying() -> gd
    1695:1696:void startFallFlying() -> ge
    1700:1702:void stopFallFlying() -> gf
    1706:1709:void doWaterSplashEffect() -> bo
    1713:1729:void playStepSound(net.minecraft.core.BlockPos,net.minecraft.world.level.block.state.BlockState) -> b
    1733:1733:net.minecraft.world.entity.LivingEntity$Fallsounds getFallSounds() -> eH
    1738:1739:boolean killedEntity(net.minecraft.server.level.ServerLevel,net.minecraft.world.entity.LivingEntity) -> a
    1744:1748:void makeStuckInBlock(net.minecraft.world.level.block.state.BlockState,net.minecraft.world.phys.Vec3) -> a
    1751:1769:void giveExperiencePoints(int) -> d
    1772:1772:int getEnchantmentSeed() -> gg
    1776:1783:void onEnchantmentPerformed(net.minecraft.world.item.ItemStack,int) -> a
    1786:1798:void giveExperienceLevels(int) -> c
    1801:1807:int getXpNeededForNextLevel() -> gh
    1819:1826:void causeFoodExhaustion(float) -> E
    1829:1829:java.util.Optional getWardenSpawnTracker() -> ab
    1833:1833:net.minecraft.world.food.FoodData getFoodData() -> gi
    1837:1837:boolean canEat(boolean) -> u
    1841:1841:boolean isHurt() -> gj
    1845:1845:boolean mayBuild() -> gk
    1850:1856:boolean mayUseItemAt(net.minecraft.core.BlockPos,net.minecraft.core.Direction,net.minecraft.world.item.ItemStack) -> a
    1861:1869:int getBaseExperienceReward() -> eg
    1875:1875:boolean isAlwaysExperienceDropper() -> eh
    1880:1880:boolean shouldShowName() -> cF
    1887:1887:net.minecraft.world.entity.Entity$MovementEmission getMovementEmission() -> bc
    1891:1891:void onUpdateAbilities() -> z
    1895:1895:net.minecraft.network.chat.Component getName() -> ah
    1899:1899:net.minecraft.world.inventory.PlayerEnderChestContainer getEnderChestInventory() -> gl
    1904:1911:net.minecraft.world.item.ItemStack getItemBySlot(net.minecraft.world.entity.EquipmentSlot) -> a
    1918:1918:boolean doesEmitEquipEvent(net.minecraft.world.entity.EquipmentSlot) -> b
    1923:1931:void setItemSlot(net.minecraft.world.entity.EquipmentSlot,net.minecraft.world.item.ItemStack) -> a
    1934:1934:boolean addItem(net.minecraft.world.item.ItemStack) -> i
    1939:1939:java.lang.Iterable getHandSlots() -> eW
    1944:1944:java.lang.Iterable getArmorSlots() -> eV
    1949:1949:boolean canUseSlot(net.minecraft.world.entity.EquipmentSlot) -> d
    1953:1968:boolean setEntityOnShoulder(net.minecraft.nbt.CompoundTag) -> h
    1972:1978:void removeEntitiesOnShoulder() -> gm
    1981:1992:void respawnEntityOnShoulder(net.minecraft.nbt.CompoundTag) -> k
    boolean isSpectator() -> R_
    1999:1999:boolean canBeHitByProjectile() -> bz
    2004:2004:boolean isSwimming() -> cd
    boolean isCreative() -> f
    2011:2011:boolean isPushedByFluid() -> cC
    2015:2015:net.minecraft.world.scores.Scoreboard getScoreboard() -> gn
    2020:2021:net.minecraft.network.chat.Component getDisplayName() -> S_
    2025:2027:net.minecraft.network.chat.MutableComponent decorateDisplayNameComponent(net.minecraft.network.chat.MutableComponent) -> a
    2036:2036:java.lang.String getScoreboardName() -> cB
    2041:2042:void internalSetAbsorptionAmount(float) -> D
    2046:2046:float getAbsorptionAmount() -> fo
    2050:2050:boolean isModelPartShown(net.minecraft.world.entity.player.PlayerModelPart) -> a
    2055:2092:net.minecraft.world.entity.SlotAccess getSlot(int) -> a_
    2096:2096:boolean isReducedDebugInfo() -> go
    2100:2101:void setReducedDebugInfo(boolean) -> v
    2105:2106:void setRemainingFireTicks(int) -> h
    2110:2110:net.minecraft.world.entity.HumanoidArm getMainArm() -> fq
    2114:2115:void setMainArm(net.minecraft.world.entity.HumanoidArm) -> a
    2118:2118:net.minecraft.nbt.CompoundTag getShoulderEntityLeft() -> gp
    2122:2123:void setShoulderEntityLeft(net.minecraft.nbt.CompoundTag) -> i
    2126:2126:net.minecraft.nbt.CompoundTag getShoulderEntityRight() -> gq
    2130:2131:void setShoulderEntityRight(net.minecraft.nbt.CompoundTag) -> j
    2134:2134:float getCurrentItemAttackStrengthDelay() -> gr
    2138:2138:float getAttackStrengthScale(float) -> F
    2142:2143:void resetAttackStrengthTicker() -> gs
    2146:2146:net.minecraft.world.item.ItemCooldowns getCooldowns() -> gt
    2151:2151:float getBlockSpeedFactor() -> aO
    2155:2155:float getLuck() -> gu
    2159:2159:boolean canUseGameMasterBlocks() -> gv
    2164:2165:boolean canTakeItem(net.minecraft.world.item.ItemStack) -> f
    2170:2170:net.minecraft.world.entity.EntityDimensions getDefaultDimensions(net.minecraft.world.entity.Pose) -> e
    2175:2175:com.google.common.collect.ImmutableList getDismountPoses() -> fE
    2180:2197:net.minecraft.world.item.ItemStack getProjectile(net.minecraft.world.item.ItemStack) -> g
    2202:2221:net.minecraft.world.item.ItemStack eat(net.minecraft.world.level.Level,net.minecraft.world.item.ItemStack,net.minecraft.world.food.FoodProperties) -> a
    2226:2249:net.minecraft.world.phys.Vec3 getRopeHoldPosition(float) -> s
    2255:2255:boolean isAlwaysTicking() -> dN
    2259:2259:boolean isScoping() -> gw
    2264:2264:boolean shouldBeSaved() -> dM
    2268:2268:java.util.Optional getLastDeathLocation() -> gx
    2272:2273:void setLastDeathLocation(java.util.Optional) -> a
    2277:2277:float getHurtDir() -> eE
    2282:2284:void animateHurt(float) -> n
    2288:2288:boolean canSprint() -> dH
    2293:2296:float getFlyingSpeed() -> fi
    2301:2301:double blockInteractionRange() -> gy
    2305:2305:double entityInteractionRange() -> gz
    2309:2312:boolean canInteractWithEntity(net.minecraft.world.entity.Entity,double) -> b
    2316:2317:boolean canInteractWithEntity(net.minecraft.world.phys.AABB,double) -> a
    2321:2322:boolean canInteractWithBlock(net.minecraft.core.BlockPos,double) -> a
    2326:2332:void setIgnoreFallDamageFromCurrentImpulse(boolean) -> w
    2335:2335:boolean isIgnoringFallDamageFromCurrentImpulse() -> gA
    2339:2342:void tryResetCurrentImpulseContext() -> gB
    2345:2349:void resetCurrentImpulseContext() -> gC
    2027:2030:net.minecraft.network.chat.Style lambda$decorateDisplayNameComponent$6(java.lang.String,net.minecraft.network.chat.Style) -> a
    1983:1990:void lambda$respawnEntityOnShoulder$5(net.minecraft.world.entity.Entity) -> G
    916:916:void lambda$addAdditionalSaveData$4(net.minecraft.nbt.CompoundTag,net.minecraft.nbt.Tag) -> a
    916:916:java.util.Optional lambda$addAdditionalSaveData$3(net.minecraft.core.GlobalPos) -> a
    884:884:void lambda$readAdditionalSaveData$2(net.minecraft.world.phys.Vec3) -> b
    646:649:void lambda$playShoulderEntityAmbientSound$1(net.minecraft.world.entity.EntityType) -> b
    645:645:boolean lambda$playShoulderEntityAmbientSound$0(net.minecraft.world.entity.EntityType) -> c
    123:172:void <clinit>() -> <clinit>
 */
// todo switch to extending LivingEntity
open class Player(around: Any) : LivingEntity(around) {
	companion object : ClassInfo {
		override val clazz: Class<*> = loadClass(net_minecraft_world_entity_player_Player)
		override val classDesc: ClassDesc = clazz.classDesc
		override val mimicClassDesc: ClassDesc = Player::class.classDesc
	}
}